### ISSUE TITLE
docker image build

### ISSUE THREAD

**Issue by rbuckland** [RackHD/RackHD#100]
There is a docker image build script which walks through a set of the profects and builds the docker images.

This script can be done away with with the newer `docker-compose` 1.6.0 which allows you to have defined

```
image: rackhd/on-foo
build: ../on-foo
```
and issue the commands

```
docker-compose build
docker-compose up
```

This makes it a little tidier for build other images also
Ensure you use the new `version: "2"` format https://docs.docker.com/compose/compose-file/#version-2

**Comment by rolandpoulter** [comment]
Good point. I've started a branch where I'm trying to use the new version of docker-compose to bring up the services in a more correct order.

I remember you can now define both a `image` and `build` step which would allow us to remove the `build-images.bash` script.

**Comment by rolandpoulter** [comment]
@heckj I think this issue is resolved now. With PR #109
