### ISSUE TITLE
New Task/Job for making REST requests

### ISSUE THREAD

**Issue by stevemendes** [RackHD/RackHD#103]
A task/job that can make a REST request out to an external system and then collect the response would be most useful.  (Currently we do this with the Ansible Task and use Ansible's 'uri' module to make the REST request, but if we can cut out Ansible it would be more straight-forward.)

Note that it would require some way to parse the response and store results in variables.  Currently we get XML and/or JSON in our responses (from ViPR) which we would need to parse into vars.  Probably being able to insert specific values in the XML into individual vars would work - so that the values would end up back in the workflow as options vars, and other tasks in the WF could use them as inputs.

An example would be a task that makes a REST request to create a volume and returns the ID of the new volume.  Another task would then need that ID in order to export it to a host.

**Comment by zhangy42** [comment]
Hi,steve. I am looking at this issue. But I need some detailed info in your request:

1. Are there any detailed requirements in response format?

2. I will assume you want us include all 4 REST behaviors. Do you want us include file IO with these 4 methods (ie Download a file and upload a file by given path to file)?

**Comment by stevemendes** [comment]
Our current requirements center around supporting communication with ViPR's REST API, which can be found here:  http://www.emc.com/techpubs/api/vipr/v2-4-1-0/index.htm  

It definitely includes GET/PUT/POST/DELETE, but I don't see any file transfer requirements.

The part of the spec that needs definition is how to get the response back to the workflow.  I expect the best way is to include the response (which will be either XML or JSON, depending on the content type) and load it into the workflow's context.  The response should be parsed such that successive tasks in the workflow can access the data as variables in the workflow.

**Comment by zhangy42** [comment]
When I was trying to implement the function you want, can you give me a usage case that you are doing with each of the 4 methods of REST api? I just want to make sure that my design can cover your need.

**Comment by stevemendes** [comment]
Here you are.

Note – we’ll also need support for token based authentication (even if it’s just getting a token from the response header after a /login call, and then being able to pass that token in on the request header of successive requests).


--- GET   ---

http://www.emc.com/techpubs/api/vipr/v2-4-1-0/VirtualArrayService_getBulkIds_f4626015c309025c99b4ab1d0dc86577_ca374f6813ae52fdd5c80166d4b2e53e_detail.htm 
Request
GET https://192.168.0.0:4443/vdc/varrays/bulk HTTP/1.1

Content-Type: application/xml
X-SDS-AUTH-TOKEN: <AUTH_TOKEN>
Response
HTTP/1.1 200 OK
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ids>
	<id>urn:storageos:VirtualArray:110acf4a-2459-4025-adff-ce429fc4c5c3:</id>
	<id>urn:storageos:VirtualArray:88543171-9a1b-4133-ac71-d93990d3bebd:</id>
	<id>urn:storageos:VirtualArray:ae316135-5742-4f40-b4b0-8d38d9604917:</id>
</ids>


--- POST   ---

http://www.emc.com/techpubs/api/vipr/v2-4-1-0/VirtualArrayService_getBulkResources_25c0ad8911afc997f25cce883bc6de56_ca374f6813ae52fdd5c80166d4b2e53e_detail.htm 

Request
POST https://192.168.0.0:4443/block/vpools/bulk HTTP/1.1

Content-Type: application/xml
X-SDS-AUTH-TOKEN: <AUTH_TOKEN>

<ids>
    <id>urn:storageos:VirtualPool:48a74fce-c654-4272-b407-2aa14c2b1095:</id>
</ids>
Response
HTTP/1.1 200 OK
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bulk_block_vpools>
    <block_vpool>
        <creation_time>1379678422602</creation_time>
        <id>urn:storageos:VirtualPool:48a74fce-c654-4272-b407-2aa14c2b1095:</id>
        <inactive>false</inactive>
        <link href="/block/vpools/urn:storageos:VirtualPool:48a74fce-c654-4272-b407-2aa14c2b1095:" rel="self"/>
        <name>Basic VPool with Consistency Group</name>
        <tags/>
        <assigned_storage_pools/>
        <description>Consistency Group Feature</description>
        <invalid_matched_pools>
            <storage_pool>
                <id>urn:storageos:StoragePool:6d6956c6-8bd8-4507-adc5-62c4d2ec8ce7:</id>
                <link href="/vdc/storage-systems/urn:storageos:StorageSystem:033e2902-7fa6-4a89-b38e-1825bd801434:/storage-pools/urn:storageos:StoragePool:6d6956c6-8bd8-4507-adc5-62c4d2ec8ce7:" rel="self"/>
            </storage_pool>
...
            <storage_pool>
                <id>urn:storageos:StoragePool:6b161dc8-a5c3-4c0b-9434-5a7f5508e8a2:</id>
                <link href="/vdc/storage-systems/urn:storageos:StorageSystem:3d7afbb5-1c41-4cd4-a571-f61ba34f39e4:/storage-pools/urn:storageos:StoragePool:6b161dc8-a5c3-4c0b-9434-5a7f5508e8a2:" rel="self"/>
            </storage_pool>
        </invalid_matched_pools>
        <matched_storage_pools>
            <storage_pool>
                <id>urn:storageos:StoragePool:bf22aabb-cccf-46b8-9c91-d31c82e4e72f:</id>
                <link href="/vdc/storage-systems/urn:storageos:StorageSystem:b03f9168-a7c8-49e1-a395-9d23a9999617:/storage-pools/urn:storageos:StoragePool:bf22aabb-cccf-46b8-9c91-d31c82e4e72f:" rel="self"/>
            </storage_pool>
...
            <storage_pool>
                <id>urn:storageos:StoragePool:53e905a7-9b4c-4e57-9a77-f98ddb67b66e:</id>
                <link href="/vdc/storage-systems/urn:storageos:StorageSystem:b03f9168-a7c8-49e1-a395-9d23a9999617:/storage-pools/urn:storageos:StoragePool:53e905a7-9b4c-4e57-9a77-f98ddb67b66e:" rel="self"/>
            </storage_pool>
        </matched_storage_pools>
        <num_paths>1</num_paths>
        <num_resources>3</num_resources>
        <protocols>
            <protocol>FC</protocol>
        </protocols>
        <provisioning_type>Thin</provisioning_type>
        <system_type>NONE</system_type>
        <type>block</type>
        <use_matched_pools>true</use_matched_pools>
        <varrays>
            <varray>
                <id>urn:storageos:VirtualArray:110acf4a-2459-4025-adff-ce429fc4c5c3:</id>
                <link href="/vdc/varrays/urn:storageos:VirtualArray:110acf4a-2459-4025-adff-ce429fc4c5c3:" rel="self"/>
            </varray>
        </varrays>
        <drive_type>NONE</drive_type>
        <expandable>true</expandable>
        <multi_volume_consistency>true</multi_volume_consistency>
        <protection>
            <snapshots>
                <max_native_snapshots>10</max_native_snapshots>
            </snapshots>
            <continuous_copies>
                <max_native_continuous_copies>0</max_native_continuous_copies>
            </continuous_copies>
        </protection>
        <raid_levels/>
        <unique_auto_tier_policy_names>false</unique_auto_tier_policy_names>
    </block_vpool>
</bulk_block_vpools>


--- PUT   ---

http://www.emc.com/techpubs/api/vipr/v2-4-1-0/BlockVirtualPoolService_updateBlockVirtualPool_d2f934217798a486843db67c9fbdccf2_ca374f6813ae52fdd5c80166d4b2e53e_detail.htm 

Request
PUT https://192.168.0.0:4443/block/vpools/urn:storageos:VirtualPool:2567045e-e16f-4aa1-930a-dfbc09917c97: HTTP/1.1

Content-Type: application/xml
X-SDS-AUTH-TOKEN: <AUTH_TOKEN>

<block_vpool_update>
     <protection>
          <continuous_copies>
               <max_native_continuous_copies>1</max_native_continuous_copies>
          </continuous_copies>
    </protection>
</block_vpool_update>
Response
HTTP/1.1 200 OK
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<block_vpool>
    <creation_time>1379169062568</creation_time>
    <id>urn:storageos:VirtualPool:2567045e-e16f-4aa1-930a-dfbc09917c97:</id>
    <inactive>false</inactive>
    <link href="/block/vpools/urn:storageos:VirtualPool:2567045e-e16f-4aa1-930a-dfbc09917c97:" rel="self"/>
    <name>Basic Block Storage</name>
    <tags/>
    <assigned_storage_pools/>
    <description>Base CoS for RP Protection</description>
    <invalid_matched_pools>
        <storage_pool>
            <id>urn:storageos:StoragePool:6d6956c6-8bd8-4507-adc5-62c4d2ec8ce7:</id>
            <link href="/vdc/storage-systems/urn:storageos:StorageSystem:033e2902-7fa6-4a89-b38e-1825bd801434:/storage-pools/urn:storageos:StoragePool:6d6956c6-8bd8-4507-adc5-62c4d2ec8ce7:" rel="self"/>
        </storage_pool>
...
        <storage_pool>
            <id>urn:storageos:StoragePool:6b161dc8-a5c3-4c0b-9434-5a7f5508e8a2:</id>
            <link href="/vdc/storage-systems/urn:storageos:StorageSystem:3d7afbb5-1c41-4cd4-a571-f61ba34f39e4:/storage-pools/urn:storageos:StoragePool:6b161dc8-a5c3-4c0b-9434-5a7f5508e8a2:" rel="self"/>
        </storage_pool>
    </invalid_matched_pools>
    <matched_storage_pools>
        <storage_pool>
            <id>urn:storageos:StoragePool:bf22aabb-cccf-46b8-9c91-d31c82e4e72f:</id>
            <link href="/vdc/storage-systems/urn:storageos:StorageSystem:b03f9168-a7c8-49e1-a395-9d23a9999617:/storage-pools/urn:storageos:StoragePool:bf22aabb-cccf-46b8-9c91-d31c82e4e72f:" rel="self"/>
...
        <storage_pool>
            <id>urn:storageos:StoragePool:53e905a7-9b4c-4e57-9a77-f98ddb67b66e:</id>
            <link href="/vdc/storage-systems/urn:storageos:StorageSystem:b03f9168-a7c8-49e1-a395-9d23a9999617:/storage-pools/urn:storageos:StoragePool:53e905a7-9b4c-4e57-9a77-f98ddb67b66e:" rel="self"/>
        </storage_pool>
    </matched_storage_pools>
    <num_paths>1</num_paths>
    <protocols>
        <protocol>FC</protocol>
    </protocols>
    <provisioning_type>Thin</provisioning_type>
    <type>block</type>
    <use_matched_pools>true</use_matched_pools>
    <varrays>
        <varray>
            <id>urn:storageos:VirtualArray:110acf4a-2459-4025-adff-ce429fc4c5c3:</id>
            <link href="/vdc/varrays/urn:storageos:VirtualArray:110acf4a-2459-4025-adff-ce429fc4c5c3:" rel="self"/>
        </varray>
    </varrays>
    <expandable>false</expandable>
    <protection>
        <snapshots>
            <max_native_snapshots>10</max_native_snapshots>
        </snapshots>
        <continuous_copies>
            <max_native_continuous_copies>1</max_native_continuous_copies>
        </continuous_copies>
    </protection>
    <raid_levels/>
    <unique_auto_tier_policy_names>false</unique_auto_tier_policy_names>
</block_vpool>


--- DELETE   ---

http://www.emc.com/techpubs/api/vipr/v2-4-1-0/FileService_deleteFileSystemACL_43d1ebb5d2a527e979d31615cd084dd5_ca374f6813ae52fdd5c80166d4b2e53e_detail.htm 

Note: DELETE is a rare case, and we don’t have any in our current integration use cases, but it exists in the ViPR API:

        DELETE /file/filesystems/{id}/acl

**Comment by stevemendes** [comment]
Sorry - XML got stripped out of last message.  See embedded links for details.

**Comment by benbp** [comment]
Resolved by https://github.com/RackHD/on-tasks/issues/217
