### ISSUE TITLE
Allow for "default" pxe boot, via action or profile.

### ISSUE THREAD

**Issue by ytjohn** [RackHD/RackHD#104]
Unknown nodes get pxe booted into the monorail discovery system. Then, their sku is matched into a workflow and it boots into the workflow's tasks. Afterwards, the node has no defined action.

During no defined action, on-dhcp will ignore dhcp requests from that node and the node will have to time out on pxe before proceeding.

We would like to be able to define a default action or "defaultProfile" that would let on-dhcp provide an ip address and boot to a specific pxe "image".  One use for this would be to force boot to the local drive, or provide a menu for on-site to utilize (boot local, rescue image, memtest, etc).  Additionally, I have seen systems that **never** time out from pxe boot. A system configured to first pxe boot could hang indefinitely. 

An example could be:

```
DEFAULT local-boot

LABEL local-boot
 localboot 0
```

**Comment by anhou** [comment]
@ytjohn Thanks for proposal, several months ago, I have a discussion about default ipxe booting with @benbp to support a internal project,  it's not a hard requirement of OnRack then, so it's not submitted to master, the patch is almost standby. I'll submit it recently.

**Comment by anhou** [comment]
@ytjohn I go back to see what I've done before, find that it's a little bit different with what you've mentioned, the 'defaultprofile' is under 'bootSettings' and 'bootSettings' need to be PATCH  when users need , just like 'obmSettings''s setting. so there isn't a default profile under a node, but if want to achieve the functionality you mentioned, the user can set(PATCH) the 'bootSettings' in demand. how do you think?

    "bootSettings":[
    {
        "profile":"defaultboot.ipxe",
        "options":{
            "kernel":"common/vmlinuz-2.6.34-platypus",
            "initrd":"common/ramfs.lzma",
            "imgargs":"console=tty0 console=ttyS0,115200n8"
        }
    }
    ]
