### ISSUE TITLE
monorail_rack results don't discover the VM

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#11]
@benbp @DavidjohnBlodgett  - updated details from a fresh run (as of 17nov AM)

I went through and cleaned out everything, resetting to run the instructions as per http://rackhd.readthedocs.org/en/latest/getting_started.html. The resulting system was functional, but the PXE.1 VM that the monorail_rack script created didn't get discovered.

VM PXE booted and got iPXE down, and then failed when requesting `/api/common/profiles`

![screen shot 2015-11-17 at 12 07 35 pm](https://cloud.githubusercontent.com/assets/43388/11223260/eaaeb23a-8d23-11e5-9e00-e78a949d2ef4.png)

Is the service in this example running on port 8080? Is the iPXE script configured incorrectly for this setup?

In the logs, there's an HTTP 502 response to that URL request as well:

```
20:04:09 http.1   |  E 2015-11-17T20:04:09.634Z [on-http] [common-api-presenter] [Server] Lookup Record Not Found (findOneByTerm)
20:04:09 http.1   |   -> /lib/services/common-api-presenter.js:197
20:04:09 http.1   |  error:
20:04:09 http.1   |    message: Lookup Record Not Found (findOneByTerm)
20:04:09 http.1   |    name:    NotFoundError
20:04:09 http.1   |    context:
20:04:09 http.1   |      status: 404
20:04:09 http.1   |    status:  404
20:04:09 http.1   |  path:  /profiles
20:04:09 http.1   |  N 2015-11-17T20:04:09.650Z [on-http] [Services.ErrorPublisher] [Server] Event Loop Blocked
20:04:09 http.1   |   -> /node_modules/on-core/lib/services/error-publisher.js:93
20:04:09 http.1   |  host:     vagrant-ubuntu-trusty-64
20:04:09 http.1   |  name:     on-http
20:04:09 http.1   |  severity: notice
20:04:09 http.1   |  ms:       13
20:04:09 http.1   |  S 2015-11-17T20:04:09.653Z [on-http] [Http.Server] [Server] http: GET 404 18.502 - /api/common/profiles
20:04:09 http.1   |   -> /lib/services/http-service.js:113
20:04:09 http.1   |  ipAddress: 172.31.128.2
```

which makes me think we might be seeing a race condition on looking up the relevant IP address to be able to render out the correct "profiles" response.

**Comment by jlongever** [comment]
@keedya this was the same failure scenario you looked at with Marcos? 
I've run into a similar race condition scenario with on-tftp but worked after a subsequent reboot.

**Comment by benbp** [comment]
Yep this seems to be an older version of the ipxe binary without Andre's fix actually.

**Comment by jlongever** [comment]
Did @keedya's change only go into on-tftp binary and not on-imagebuilder ipxe task?

**Comment by jlongever** [comment]
Looks like it's in the on-imagebuilder embedded script:

#!ipxe
echo MonoRail iPXE
set user-class MonoRail
echo "Sleeping for 10s to allow data updates"
sleep 10
autoboot

**Comment by heckj** [comment]
@jlongever  yeah, just verified that too: the sleep is in the on-imagebuilder repo: https://github.com/RackHD/on-imagebuilder/blob/master/roles/ipxe/files/default.ipxe

**Comment by heckj** [comment]
found it - 

It look like how we're pulling down the file from bintray is somehow corrupted or screwing us over.

md5 of the direct download from bintray for monorail.ipxe: 602520a1c6b5bf62eb6f27b3755c8890
md5 of the download with get_url from bintray: ed0b3d278a57ce95d11f56d2b852192f
md5 of the source file committed into on-tftp: 7052c8453d91d22229899c327a6def83

working on a functional alternative now...
I replaced the one downloaded by the fully automated setup with Vagrant/Ansible with the bintray direct download, and the discovery process worked full bore and correctly.

**Comment by DavidjohnBlodgett** [comment]
wrapped up a fix for this in https://github.com/RackHD/RackHD/pull/12
