### ISSUE TITLE
"Request Timed Out" while Trigger Workflow

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#110]
I download the latest code (after @benbp merged the workflow enhancement design), and try to trigger a workflow, it always reported "Request Timed Out" no matter which workflow I sent. @sunnyqianzhang finds the same issue.

This is the error information:
```
http post :8080/api/common/nodes/568f1ff9d786788607c7dbab/workflows?name=Graph.InstallCoreOS
{
    "message": "Request Timed Out (on.task-graph-runner:methods.runTaskGraph:Object)."
}
```

**Comment by heckj** [comment]
FYI . @benbp

**Comment by benbp** [comment]
Ack! I'll take a look

**Comment by benbp** [comment]
@yyscamper I'm not able to reproduce this locally, can you attach the on-http and on-taskgraph logs please?

**Comment by benbp** [comment]
Also, is there a document in the mongo graphobjects collection, or literally nothing?

**Comment by yyscamper** [comment]
@sunnyqianzhang tried to clear the db before running workflow, but still failed. I will collect some log today.

**Comment by benbp** [comment]
Ok, yeah I ask because with the new code it should create a workflow document regardless of the AMQP success or not. I think the problem here is we shouldn't be waiting for a response anymore from AMQP at all before returning success to the user. If it got into Mongo, then that should be good enough. I'll take a deeper look at the code here.

**Comment by yyscamper** [comment]
@benbp: I have found the reason, it's my fault, I run the latest on-taskgraph service (after your workflow enhancement) but with an old on-http service (before your workflow enhancement). So ...

Anyway, this is the error message:
```
E 2016-02-26T14:09:45.955Z [on-http] [Http.Services.RestApi] [Server] Request Timed Out (on.task-graph-runner:methods.runTaskGraph:Object).
 -> /lib/services/rest-api-service.js:320
error:
  message: Request Timed Out (on.task-graph-runner:methods.runTaskGraph:Object).
  name:    RequestTimedOutError
  context:

path:  /nodes/568f1ff9d786788607c7dbab/workflows
D 2016-02-26T14:09:45.962Z [on-http] [Http.Server] [Server] http: POST 500 1020.531 - /api/common/nodes/568f1ff9d786788607c7dbab/workflows?name=G#
 -> /lib/services/http-service.js:110
ipAddress: 127.0.0.1
RequestTimedOutError: Request Timed Out (on.task-graph-runner:methods.runTaskGraph:Object).
    at null.<anonymous> (/var/renasar/on-http/node_modules/on-core/lib/common/messenger.js:317:29)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by benbp** [comment]
Ah ok :) I went back into the code and remembered that we actually don't wait for an AMQP success response at all now as intended (https://github.com/RackHD/on-http/blob/master/lib/services/workflow-api-service.js#L68), even though we do publish one. So we shouldn't have to see failures like this going forward.
