### ISSUE TITLE
POSTing SKUs always creates a duplicate

### ISSUE THREAD

**Issue by ytjohn** [RackHD/RackHD#113]
If you take a sku and POST it, it will keep creating a new sku. I would request that instead, this is reworked to operate like PUT /workflows does. If that matches on the name/injectablename, it will update the existing definition.

@benbp 

```
root@rackhd01:/vagrant/scratch/examples# curl -H "Content-Type: application/json" -X POST --data @skus/virtualbox_sku_ubuntu.json http://localhost:8080/api/1.1/skus
{"name":"Noop OBM settings for VirtualBox nodes","discoveryGraphName":"Graph.DefaultVirtualBox.InstallTrusty","discoveryGraphOptions":{},"rules":[{"path":"dmi.System Information.Product Name","equals":"VirtualBox"}],"createdAt":"2016-02-26T21:47:41.549Z","updatedAt":"2016-02-26T21:47:41.549Z","id":"56d0c7fd2113e7c76b92b5dd"}

root@rackhd01:/vagrant/scratch/examples# curl -H "Content-Type: application/json" -X POST --data @skus/virtualbox_sku_ubuntu.json http://localhost:8080/api/1.1/skus
{"name":"Noop OBM settings for VirtualBox nodes","discoveryGraphName":"Graph.DefaultVirtualBox.InstallTrusty","discoveryGraphOptions":{},"rules":[{"path":"dmi.System Information.Product Name","equals":"VirtualBox"}],"createdAt":"2016-02-26T21:47:45.140Z","updatedAt":"2016-02-26T21:47:45.140Z","id":"56d0c8012113e7c76b92b5de"}
````

**Comment by heckj** [comment]
FYI @zyoung51

**Comment by zyoung51** [comment]
@heck @benbp Can this be added to the list of things to change in the 2.0 api? Can we drop post from 2.0 and treat put as an upsert instead?

**Comment by benbp** [comment]
@zyoung51 makes sense to me (CC @brianparry)

**Comment by brianparry** [comment]
@zyoung51 Fine with me too.

**Comment by amymullins** [comment]
This work will be tracked as part of the 2.0 API SKU Controller development : https://www.pivotaltracker.com/projects/1496834/stories/111716486

**Comment by zyoung51** [comment]
@ytjohn The PR above changed POST behavior and adds PUT.  Because POST has create semantics, re-POSTing the same sku will now result in a 409 error due to a duplicate 'name' conflict.  PUT has replace semantics and it can be used to update or insert a sku definition.
