### ISSUE TITLE
static/DSP8010_1.0.0/json-schema-oem/RackHD.BootImage.json has extra colon in "ipv4" and "ipv6" fields

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#116]
When trying to do a POST /Systems/{identifier}/Actions/RackHD.BootImage, we got a response of 

{
  "name": "Error",
  "message": "ValidationError: Additional properties not allowed",
  "stack": "Error: ValidationError: Additional properties not allowed\n    at validatePayload (/RackHD/on-http/lib/api/redfish-1.0/systems.js:471:19)\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/RackHD/on-core/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/RackHD/on-core/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/RackHD/on-core/node_modules/bluebird/js/main/promise.js:581:18)\n    at Promise._settlePromises (/RackHD/on-core/node_modules/bluebird/js/main/promise.js:697:14)\n    at Async._drainQueue (/RackHD/on-core/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/RackHD/on-core/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/RackHD/on-core/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)",
  "context": {}
}

Tracked this down to an extra colon in the "ipv4" and "ipv6" fields of NetworkAddress in the schema.  This requires the networkDevices section of the payload to have "ipv4:": rather than "ipv4":

This is the payload we were trying to use:
`{
      "domain": "hwimo.lab.emc.com",
       "users": [{
               "password": "onrack",
               "uid": 100,
               "name": "onrack"
       }],
       "hostname": "rhel70test",
       "osName": "RHEL",
       "version": "7",
       "repo": "http://172.31.128.1:8080/rhel/7.0/os/x86_64",
       "networkDevices": [{
               "device": "ens20f0",
               "ipv4": {
                       "netmask": "255.255.255.0",
                       "ipAddr": "192.168.199.154",
                       "gateway": "192.168.1.1",
                       "vlanId": "1824"
               }
       }],
       "rootPassword": "1234567",
       "dnsServers": [
               "192.168.199.153"
       ]
}`

**Comment by benbp** [comment]
@jlongever @zyoung51

**Comment by zyoung51** [comment]
Other errors I made in the json schema should also be addressed at the same time:
- required property definition is missing (defined in redfish.yaml)
- BootImage.osName is missing enum definition
@amymullins

**Comment by amymullins** [comment]
Story created in the Gripen backlog to track the errors noted above:
https://www.pivotaltracker.com/projects/1492890/stories/114712497

**Comment by jgolio** [comment]
After changing the payload to have "ipv4:": rather than "ipv4":, the error response went away, and I now get a 202 response, but, both the response body and header contain a reference to an undefined task. 

{
  "@odata.id": "/redfish/v1/TaskService/Tasks/undefined"
}

{
  "date": "Wed, 02 Mar 2016 13:32:34 GMT",
  "via": "1.1 web (squid/3.3.8)",
  "x-cache-lookup": "MISS from web:3128",
  "x-powered-by": "Express",
  "etag": "W/\"37-mjH/C6Q+Yqkcn4xy70KYGw\"",
  "location": "/redfish/v1/TaskService/Tasks/undefined",
  "x-cache": "MISS from web",
  "content-type": "application/json; charset=utf-8",
  "access-control-allow-origin": "*",
  "connection": "keep-alive",
  "content-length": "55"
}

**Comment by zyoung51** [comment]
I'll fix that at the same time, but that is a different issue.  The recent workflow refactor changed the object data structure such that the field that used to be there is now undefined. FYI @benbp

**Comment by jgolio** [comment]
Jeanne had me check a few things and it looks like some of the tasks in the workflow are failing due to lack of OBM settings. I'm going to pursue that next.... as well.

**Comment by zyoung51** [comment]
@jgolio FWIW, Gripen has a PR up to automatically setup OBM settings during node discovery.  You may not have to deal with that issue in the future...

**Comment by jgolio** [comment]
ok, that sounds good.

**Comment by zyoung51** [comment]
https://github.com/RackHD/on-http/pull/165

**Comment by jgolio** [comment]
Well, I've set the OBM settings, but still I can't seem to get the install to work. I backed off and tried ComputerSystem.Reset and that gave me back the same "undefined" task ID with a 202. Out of curiosity, will the PR above (165) fix the issue for all workflows? I'm assuming so, but just want to be sure I understand. Also, when I get that back, does it mean the task actually started?

**Comment by jgolio** [comment]
Keep in mind I'm not sure how many issues I'm running into are issues with the Redfish API and how many are issues with running in Docker containers. Could very well be both or a combination.

**Comment by zyoung51** [comment]
@jgolio The PR above will resolve the 'undefined' task id issue.  

A 202 indicates the task was accepted (note that this should probably be changed to a 201...), but does not indicate that the task has actually been started.  Querying the /TaskService with the odata.id will give you the status of the task.

**Comment by jgolio** [comment]
ok, thanks

**Comment by heckj** [comment]
resolved with https://github.com/RackHD/on-http/pull/165
