### ISSUE TITLE
question about random EOF in output of /workflow/tasks/library

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#13]
from Avery Yen:

> We're working with the EMC CMD team in Cambridge on the RackHD CPI. We've noticed recently that > when we issue a GET on /workflows/tasks/library against the Hopkinton lab, we get random EOF in the > middle of the response.
> 
> We get this behavior both in the browser and in our test code. We also attached a sample response. Is > it possible this is a bug in RackHD? Is there any other information you'd like?
> 
> Thanks!

[example_library_response.txt](https://github.com/RackHD/RackHD/files/38101/example_library_response.txt)

**Comment by heckj** [comment]
When I downloaded that file and looked at in an editor (Atom), what was attached was a solid block of JSON with no line feeds in it and truncated  - the JSON in that example wasn’t complete. Is that the EOF you’re talking about?

The file is exactly 108600 bytes long, which seems strangely specific. I’ll see what I can do to replicate this  - I noticed in includes a number of workflows you uploaded into the system, can you give me a sense of how many you added? Not sure if that will be a variable or not, but figured it was worth asking.

**Comment by heckj** [comment]
from evan:

> Yeah, our initial instinct was to create a Github issue, but we ended up emailing because we weren't sure if this was a solved/known problem and perhaps the Hopkinton Lab just wasn't running the most recent version of the code. Now that we know your preference we can open a Github issue for similar situations in the future.
> 
> As far as the data goes, yes, that is the EOF we're referring to. The JSON is truncated which causes an error in our test code. Unfortunately I don't have a great sense of the exact number of workflows  that have been uploaded (Megan just said it's "a boatload")
> 
> Best,
> 
> Evan

**Comment by heckj** [comment]
[dummy.json.txt](https://github.com/RackHD/RackHD/files/43363/dummy.json.txt)

And a test script for creating a ton (999, actually) of extra 'dummy'  tasks:

```
for i in {1..999}; do
cat dummy.json.txt | sed "s/exampleXXX/example$i/" > dummy.json.$i
curl -H "Content-Type: application/json" -X PUT --data @dummy.json.$i http://localhost:9090/api/1.1/workflows/tasks
rm dummy.json.$i
done
```

Then I ran `curl -s http://localhost:9090/api/1.1/workflows/tasks/library > output.json`, which resulted in a file 249594 bytes long - longer than what Evan was seeing at break.

`curl -s http://localhost:9090/api/1.1/workflows/tasks/library | wc` results in the output:

    0    2862  249594

And I went ahead and ran that in a tight loop as well to see if I could get an intermittent failure, but every result came back functionally the same - no variance in word count, every response a 200:

`for i in {1..999}; do curl -s http://localhost:9090/api/1.1/workflows/tasks/library | wc; done`

Just for the sheer lunacy of it, I also tried to use "ab" to flood the system to get a failure response:

    ab -n 500 -c 5 http://localhost:9090/api/1.1/workflows/tasks/library

with success (following results):

```
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests


Server Software:
Server Hostname:        localhost
Server Port:            9090

Document Path:          /api/1.1/workflows/tasks/library
Document Length:        249594 bytes

Concurrency Level:      5
Time taken for tests:   53.394 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      124917500 bytes
HTML transferred:       124797000 bytes
Requests per second:    9.36 [#/sec] (mean)
Time per request:       533.936 [ms] (mean)
Time per request:       106.787 [ms] (mean, across all concurrent requests)
Transfer rate:          2284.73 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    1   0.1      1       3
Processing:   113  531  82.8    530     902
Waiting:      110  525  82.3    525     895
Total:        116  532  82.8    530     903

Percentage of the requests served within a certain time (ms)
  50%    530
  66%    545
  75%    556
  80%    560
  90%    574
  95%    625
  98%    858
  99%    868
 100%    903 (longest request)
```

**Comment by benbp** [comment]
That ab test shows much higher latency, but I'm not reading it to say you actually got a failure response as you say @heckj 

```
Complete requests:      500
Failed requests:        0
```

**Comment by benbp** [comment]
@heckj can I tell from that ab test how many responses you got had the incomplete document length? Or what do you mean by failed in that case?

**Comment by heckj** [comment]
@benbp my bad - I meant to say that I never saw a failure response here - I'm unable to reproduce this issue at all

**Comment by benbp** [comment]
Would the ab test even fail though, since I would assume the EOF is still returned with an HTTP success and the only indication of failure happens during JSON parsing of the output?

**Comment by heckj** [comment]
I was more looking the length of the outputs in that set than failures per se.

**Comment by benbp** [comment]
Ah ok, `124797000 / 500 = 249594`. Cool. I'm going to close this ticket in that case then.
