### ISSUE TITLE
ohai catalog hits ruby error occasionally

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#132]
On one of our nodes in our smoke test, we occasionally hit a condition where we do not get an ohai catalog during discovery.  Because our SKU rules for this node is based on the ohai catalog, we don't get a sku and a bunch of our tests fail.  

on-taskgraph.log shows an error that it was not able to parse the ohai data that is passed back.  I was able to log on to the discovery microkernel and run the ohai command () several times and found that sometimes it hits a ruby error. (see attached file)

[ohai.error.txt](https://github.com/RackHD/RackHD/files/166150/ohai.error.txt)

**Comment by johren** [comment]
This is the error shown in on-taskgraph.log:

```
[debug] [2016-03-09T16:10:46.713Z] [on-taskgraph] [Job.Linux.Catalog] [fcef66] Received command request from node. Sending commands.
 -> /node_modules/on-tasks/lib/jobs/linux-catalog.js:50
commands:
  -
    cmd: sudo ohai --directory /etc/ohai/plugins
[debug] [2016-03-09T16:10:46.951Z] [on-taskgraph] [Job.Linux.Catalog] [fcef66] Received command payload from node.
 -> /node_modules/on-tasks/lib/jobs/linux-catalog.js:61
[error] [2016-03-09T16:10:46.951Z] [on-taskgraph] [Job.Linux.Catalog] [Server] Failed to parse data for ohai
 -> /node_modules/on-tasks/lib/jobs/linux-catalog.js:72
error:
  killed: false
  code:   134
  signal: null
result:
  source: ohai
  error:
    killed: false
    code:   134
    signal: null
```

**Comment by johren** [comment]
So far, this always seems to fail on the same node in our smoke tests.  However, I was just able to verify that I do get this error on other nodes when I log in and run "sudo ohai --directory /etc/ohai/plugins" multiple times.  So it does NOT seem to be isolated only to the one node.

**Comment by johren** [comment]
Update:  We have seen this failure in 19% of our test runs in the last week (since 3/11/2016).  We have also started seeing it happen across a few different T41 nodes.

**Comment by heckj** [comment]
@johren what's changed in this space, or has this always been happening and we didn't catch the failure rate previously? Did the microkernel you're using get rebuilt, which may have included a different version of OHAI and embedded ruby?

The code in the overlay is defined in:

https://github.com/RackHD/on-imagebuilder/blob/master/roles/overlay/provision_discovery_overlay/tasks/main.yml

and https://github.com/RackHD/on-imagebuilder/blob/master/vars/oem/raid_overlay.yml

- so this is bound to version `6.14.0-2`

The very earliest OHAI came from elsewhere (hand built into the microkernel) which does seem to be the latest: https://launchpad.net/ubuntu/+source/ohai

**Comment by DavidjohnBlodgett** [comment]
@johren @heckj so took a look in the areas you posted joe and the only change I can see, is version bumping the pciutils that I discovered while needing to refactor the on-imagebuilder to support ansible 2.0 here: https://github.com/RackHD/on-imagebuilder/commit/97491aa4642016190f3867e75673b44853a7ed13

not sure if this could be the root cause of the issue or just a red herring.

**Comment by johren** [comment]
I went digging deeper in the history and found the issue started showing up on 2/18/2016. 
The last build of on-static-common was on 2/15/2016.  Digging with Stuart now on what changes came in on that last build.  It looks like it does not have your change, DJ, because that went in on 2/16.

**Comment by DavidjohnBlodgett** [comment]
@johren ok understood, thank you for looking into that!

**Comment by johren** [comment]
These are the files that changed in the latest on-static-common build:

base.trusty.3.16.0-25-generic.squashfs.img
discovery.overlay.cpio.gz
initrd.img-3.16.0-25-generic

These were pulled in from bintray on 02/08/2016.  I will run a test with latest version of each of these which appear to have last been updated 4 days ago.

**Comment by heckj** [comment]
We're definitely not the only ones hitting this:
 - https://gist.github.com/pmorillon/be88451ca2000750b2ec

I found related style dumps from OHAI when using other plugins - mostly related to wmi-lite under WinOS though, so not exactly this. When we first made microkernels with OHAI, we installed it from Chef Omnibus (https://docs.chef.io/install_omnibus.html), which included ruby, ohai, and all relevant libraries in a pre-built static directory. This might be an alternative we can try out instead the Ansible installation of Ubuntu/OHAI if we can't sort out what's crashing in there.

The relevant files here would be in the `discovery.overlay.cpio.gz` I think - WAY back, we had them in the base, but that's been way slimmed down to preserve disk space these days.

**Comment by johren** [comment]
In the initial testing with the latest versions of these three files from bintray, the problem appears to have gone away.  I am putting up a PR to pull these latest files into the build and we'll see if it reproduces after that merges.

**Comment by DavidjohnBlodgett** [comment]
@johren Hi Jeanne, just wanted to follow up and see if your still seeing these issues in our smoke tests or if your PR will resolve this issue.

**Comment by johren** [comment]
Yeah, I wanted to give it a couple of days to run tests to make sure the problem no longer occurs.  That brings us to today with no occurrence.  Therefore, I will close as fixed.
