### ISSUE TITLE
 Ignoring DHCP requests from node because there is no active task assigned to it.

### ISSUE THREAD

**Issue by j-wheezy** [RackHD/RackHD#143]
Hello,

This is more a question then issue, but I cannot get a graph to execute against a node. I have a pending Install CentOS graph assigned to my node, and i can see the node trying to PXE, but the on-dhcp-proxy continually gives the error:

 Ignoring DHCP requests from node because there is no active task assigned to it.

Even though I can see a pending workflow assigned to the node in the API and the GUI....what am I missing?

Thanks,

James

**Comment by anhou** [comment]
A quick verification that this issue is brought between 20160223 and 20160314 (seen from internal ova image. 20160223 ova image works well, 20160314 ova image has this issue)

**Comment by j-wheezy** [comment]
Yes, that was exactly the problem...i had a null parameter.

Thanks!
