### ISSUE TITLE
coreOS demonstration install isn't installing to disk

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#146]
Ran through demonstration in https://github.com/RackHD/RackHD/blob/master/example/README.md, and the CoreOS OS automatically boots, but fails to install.

Digging it out, I tracked it down to a combination of the template that runs the install process to disk and the proxy settings.

The proxy settings are:

``` JSON
    "httpProxies": [{
        "localPath": "/coreos",
        "server": "http://stable.release.core-os.net",
        "remotePath": "/amd64-usr/current/"
    }],
```

and when the template `install-coreos.sh` is run in the kernel, it uses the `-b repo` portion to specify an alternative repo, which resulted in the following URL being requested:

http://172.31.128.1:9080/coreos/899.13.0/coreos_production_image.bin.bz2

which doesn't resolve. The error in the console (screenshot):

![screen shot 2016-03-23 at 12 14 39 pm](https://cloud.githubusercontent.com/assets/43388/13997760/d9b071e0-f0f0-11e5-888d-391ffa30d4c7.png)

It then follows in the script and reboots, having failed to install to disk. FYI the command to hunt through the logs on CoreOS is `journalctl`

To debug this, I commented out the reboot in the installation script (the line at https://github.com/RackHD/on-http/blob/master/data/templates/install-coreos.sh#L4), and re-ran the discovery/install process, and then hunted up the error with the command `journalctl | less` that worked with the `coreos-autologin` that's included in the profile to aid for this kind of debugging.

**Comment by heckj** [comment]
verified that with those changes in the PR's mentioned, the installation happens correctly:

![screen shot 2016-03-23 at 12 46 07 pm](https://cloud.githubusercontent.com/assets/43388/13998623/50e0fc2c-f0f5-11e5-864f-6768a5503b3b.png)

**Comment by yyscamper** [comment]
it seems like a redirection, otherwise how it knows the current CoreOS version is `899.13.0`

**Comment by heckj** [comment]
@yyscamper it is some redirection. The coreos-install script has an option on that code to specify a base URI repo, and it apparently expects that to be the level of the remote host to the versions - where the mirror of CoreOS resides. This makes the settings for the Install CoreOS profile and the install-coreos.sh template dependent on the proxy settings. 

The files from CoreOS come embedded for a specific version (like `899.13.0`) when you boot their installer disk (the file that comes from `/current/...` - so that version is being defined by the files at CoreOS, not any redirect we're doing explciitly.

**Comment by heckj** [comment]
(resolved with above merges)
