### ISSUE TITLE
2.0 API pollers tests occasionally fail

### ISSUE THREAD

**Issue by brianparry** [RackHD/RackHD#150]
There are a couple of problems with the 2.0 pollers API tests

1.  /api/2.0/pollers/.../data should return 204 rather than 404 if no data is available.
2. The pollers data test uses the lastFinished property to determine if data should be available in a poller's data stream.  This check does not always work.

To address this problem, item 1 should be corrected and the test should accept either a 200 or a 204 response.  If a 200 is received, the test should verify that some data is present in the response body.

A failure caused by this problem can be found here: https://github.com/RackHD/on-core/pull/105

**Comment by brianparry** [comment]
@srinia6 Looks like we're still seeing these errors (see https://github.com/RackHD/on-http/pull/204) .  Error caught in controller is: `[TypeError: undefined is not a function]`  Also, the functional test still needs to be modified to handle both 200 and 204.

**Comment by amymullins** [comment]
Closing out, resolved with : https://www.pivotaltracker.com/story/show/127723603
