### ISSUE TITLE
404 response on delete active workflow.

### ISSUE THREAD

**Issue by jlongever** [RackHD/RackHD#151]
Observed in both 1.1 and 2.0 API's;  following the workflow engine redesign the integration tests started reporting random 404 errors on a DELETE to /node/:id/workflows/active after starting a discovery graph workflow.  Checks to monitor the status following a POST to workflows indicate the workflow is either 'pending' or 'running';  when a DELETE is sent the following error is returned:

```
ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '62', 'X-Powered-By': 'Express', 'Connection': 'keep-alive', 'ETag': 'W/"3e-uVr3eF51jj1og38xQuRGng"', 'Date': 'Tue, 22 Mar 2016 07:28:50 GMT', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {"message":"NotFoundError: No active workflow found for node"}
```

This can be reproduced locally after multiple attempts.   

Looking at the workflow API service in on-http;  there isn't much to distinguish between the two error scenerios in the promise chain.  But after some digging the second .then() in the chain is what's being hit indicating the cancel request is randomly responding with an unfulfilled graph:
```
        .then(function(graphId) {
            if (!graphId) {
                throw new Errors.NotFoundError('No active workflow found for node');
            } else {
                return;
            }
        });
```

A [commit] (https://github.com/RackHD/RackHD/commit/4c7e4b2daf030b9b41128d70868e3adb05157730)  was made to help mitigate these random failures in the functional integration tests;  but some additional evaluation around this is probably in order to ensure everything is behaving as designed.

@RackHD/corecommitters FYI

**Comment by jlongever** [comment]
Put up this PR https://github.com/RackHD/on-http/pull/192/files to help provide some more detail when a cancel fails.

**Comment by benbp** [comment]
That route code was added to handle possible race conditions where the workflow was completed after the API call/node query but before the delete call. Perhaps there is a bug with that handling, OR the workflow in the test is actually completing?

Discussion originally at https://github.com/RackHD/on-http/pull/112#discussion_r52049893

**Comment by jlongever** [comment]
@benbp The functional test ensures the state is running or pending prior to requesting the cancel.  The time between status checking and cancellong is immediate. How long does the Graph.Discovery workflow take to complete?  Is it possible the findAndModify() isn't updating the document on subsequent workflow request?

**Comment by benbp** [comment]
Yeah it seems much more likely to be a real bug, was just raising the possibility. @jlongever do you see any log statements in the on-taskgraph log that start with "subscribeCancelGraph stream error" ??

**Comment by benbp** [comment]
Looking at the cancellation code, seems we have an issue that could occur where we will end up triggering a 404 response on a graph cancellation error (instead of a 500): https://github.com/RackHD/on-taskgraph/blob/master/lib/task-scheduler.js#L417-L428

**Comment by jlongever** [comment]
@benbp I'll have to go back to the on-taskgraph logs when I'm near a system and check. Stay tuned.
