### ISSUE TITLE
Taskgraph does not fail on task rendering error

### ISSUE THREAD

**Issue by benbp** [RackHD/RackHD#154]
This happened as part of a CentOS installer run, where the version field was not passed into the CentOS install task (the third task to run in the workflow), but the workflow and task remained in a pending state when the failure should have been reflected.

Relevant error:
```
2016-03-29T14:27:48.625941453Z  -> /lib/task-runner.js:311
2016-03-29T14:27:48.628014514Z taskRunnerId: 756fb06d-bb3a-4160-ba26-7d070efb51e0
2016-03-29T14:27:48.628037963Z error: 
2016-03-29T14:27:48.628047023Z   message: Value does not exist for options.version
2016-03-29T14:27:48.628054541Z   name:    TemplateRenderError
2016-03-29T14:27:48.628061844Z   context: 
```

Logs:
https://gist.github.com/benbp/546d8a94c472cfb859d92ca9d424eda3

Workflow data:
https://gist.github.com/benbp/6bbbb2f574ce58a8c22c390ee6792bbd

CC @jgolio @heckj @VulpesArtificem

**Comment by heckj** [comment]
Ah - this is what Joe Golio hit with his workflow error recently?

**Comment by yyscamper** [comment]
By examining the graph instance, the `version` is null, so the rendering error is expected. So I guess the problem was that the overriden options JSON payload was not successfully passed to the workflow engine, right? How is the JSON payload be defined?

**Comment by benbp** [comment]
@yyscamper yes those are issues although this bug is specifically about why the graph didn't actually reach a failed state despite these failures.

**Comment by pscharla** [comment]
@benbp Should this be closed due to the merged PR?
