### ISSUE TITLE
error: ipmitool isn't hosted on the local machine at /usr/bin/ipmitool

### ISSUE THREAD

**Issue by jgolio** [RackHD/RackHD#155]
The Docker implementation of RackHD uses Alpine Linux (on-core) which hosts ipmitool in /usr/sbin, ratner than /usr/bin. Once a node is discovered, the on-taskgraph container will begin to log the following error as the IPMI poller attempts to start. 

error: ipmitool isn't hosted on the local machine at /usr/bin/ipmitool

The code which is generating the error is located in "on-tasks/lib/utils/job-utils/ipmitool.js" inside the "ipmitoolFactory" function:

 fs.exists('/usr/bin/ipmitool', function(exists) {
                if (!exists) {
                    reject("ipmitool isn't hosted on the local machine" +
                                        " at /usr/bin/ipmitool");
                    return;
                }

**Comment by heckj** [comment]
@RackHD/corecommitters ^^ we'll have more variation as we go forward for shell-out tooling. Docker is just a piecemeal start of this. Do we want to have something that's set to in configuration that identifies where tools should be found to provide a path to both resolve this and enable other changes as we go forward?

**Comment by benbp** [comment]
@heckj I'm wondering whether the hard path is even necessary here at all? Just call `ipmitool` and let $PATH resolve where it is.

**Comment by codenrhoden** [comment]
I just hit this myself. FWIW, I do think that it should be left to `$PATH` resolution vs hardcoding a path to the executable.

**Comment by yyscamper** [comment]
I add some enhancement in this PR: https://github.com/RackHD/on-tasks/pull/315

My solution is to check the existence of some required tool at the early stage when service starts. This depends on user has correctly added the tool in the $PATH.

**Comment by yyscamper** [comment]
I have completely remove the checkToolExist in the latest change, when the ipmi command is executed the tool existence will  be checked then, so it's not necessary to add a special step to check tool existence.
