### ISSUE TITLE
Add ESXi 6 sample file

### ISSUE THREAD

**Issue by tschwaller** [RackHD/RackHD#159]
Add an ESXi 6 sample file to [https://github.com/RackHD/RackHD/tree/master/example/samples](https://github.com/RackHD/RackHD/tree/master/example/samples).

**Comment by heckj** [comment]
We can redistribute ESXi installables, so there's additional files you'll need to have there already. I assume you're looking for instructions on how to get that set up and invoke the ESXi flavored install OS workflow?

**Comment by tschwaller** [comment]
Let's assume that the ESXi ISO files are downloaded separately to avoid any legal issues, so the answer to

>I assume you're looking for instructions on how to get that set up and invoke the ESXi flavored install >OS workflow

would be a clear yes. :-)

**Comment by benbp** [comment]
@tschwaller a little late to the party on this, but we have added some more detailed documentation on supported options and API commands for running the OS installer workflows, including ESXi: http://rackhd.readthedocs.io/en/latest/rackhd/install_os.html. This is the kickstart we use for all ESXi installs (https://github.com/RackHD/on-http/blob/master/data/templates/esx-ks), though I haven't personally tested on v6.

**Comment by benbp** [comment]
Looks like https://github.com/RackHD/RackHD/pull/251 might be what you're looking for @tschwaller
