### ISSUE TITLE
Get HTTP 400 resposne when attemp to create a new tag 

### ISSUE THREAD

**Issue by nortonluo** [RackHD/RackHD#169]
I get http 400 response code when creating a new tag on RackHD.  I used the following command
`curl -H "Content-Type: application/json" -X POST -d '{ "name": "newtag_JYNrtABT_ccdsffa_ccds", "rules": [ { "equals": "my server", "path": "dmi.System Information.Product Name" }]}' http://{IP}:8080/api/1.1/tags`

And it get 400 http response. Error message is
` {"message":"required option nodeId for task Task.Catalog.GenerateTag in graph Graph.GenerateTags"}`

**Comment by yyscamper** [comment]
I also reproduced this issue in my system, add @zyoung51 for awareness.

**Comment by amymullins** [comment]
Known issue being tracked in : https://www.pivotaltracker.com/projects/1492890/stories/117246337

**Comment by amymullins** [comment]
FYI @uppalk1

**Comment by uppalk1** [comment]
Created PR https://github.com/RackHD/on-http/pull/224

**Comment by amymullins** [comment]
Code merged: https://github.com/RackHD/on-http/commit/23cf90b44ff3cda765334517e35dbe811a361f49

if you set the pull request message to read:
resolves RackHD/RackHD#169
then when this is merged, it will close the github bug

**Comment by amymullins** [comment]
Closing bug
