### ISSUE TITLE
Still get http 200 success response when query a not existed Tag

### ISSUE THREAD

**Issue by nortonluo** [RackHD/RackHD#180]
I tried to query tags with a non-exist tag name in the system.
`curl -x http://192.168.187.63:8080/api/1.1/tags/tagnotexistinthesystem`
But it still get http 200 response. I think in this situation, Http 404 is expected.

**Comment by nortonluo** [comment]
@yyscamper @zyoung51 @amymullins @uppalk1

**Comment by amymullins** [comment]
fYI @brianparry
