### ISSUE TITLE
on-http crash after an invalid sku pack command

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#186]
I tried following invalid command to register and skupack (I forgot the symbol `@` before the file name):
```
 curl -X POST --data-binary rinjin_test.tar.gz http://localhost:8080/api/1.1/skus/pack
```

I found the on-http service crashed with following error messsage:
```
/home/yuanf/src/on-http/lib/services/sku-pack-service.js:134
                    reject(new Errors.InternalServerError('Invalid gzip'));
                           ^
TypeError: undefined is not a function
    at Gunzip.start.pipe.on.pipe.tar.Extract.path (/home/yuanf/src/on-http/lib/services/sku-pack-service.js:134:28)
    at Gunzip.emit (events.js:117:20)
    at Zlib._binding.onerror (zlib.js:299:10)
```

If I sent a correct name (with a symbol `@` before the file name), the command executed successfully.

The expected behavior is that the on-http service should never be crashed even for an invalid command.

**Comment by amymullins** [comment]
@yyscamper  please update to the latest code on master.  This issue was fixed last week with PR : https://github.com/RackHD/on-http/pull/221

**Comment by yyscamper** [comment]
@amymullins : I have already used the latest code, and I double confirmed my code had included the fix of the PR your mentioned.

**Comment by zyoung51** [comment]
@brianparry InternalServerError is missing in the on-core definitions.  Can you take a look?

**Comment by amymullins** [comment]
Closed too soon!   Looks like went in with on-core PR #112 @brianparry and I'll assign this issue over to the stryker team.

**Comment by yyscamper** [comment]
I have found the root cause, the `InternalServerError` is not in the list of return list (see https://github.com/RackHD/on-core/blob/master/lib%2Fcommon%2Ferrors.js#L152), It could have been captured by unit-test, but the unit-test was forgot.

**Comment by yyscamper** [comment]
The unit-test for other errors were also forgot, such as `UnauthorizedError`, `ForbiddenError`, `NotFoundError`, and may be more.

**Comment by amymullins** [comment]
Story tracking resolution of this bug in the Stryker backlog: https://www.pivotaltracker.com/projects/1496834/stories/117907165

**Comment by amymullins** [comment]
Code has been merged: 
https://github.com/​RackHD/on-core/pull/​121
https://github.com/​RackHD/on-core/pull/​122
