### ISSUE TITLE
RackHD can't discovery T41 w/ 3.19 version microkernel

### ISSUE THREAD

**Issue by pengz1** [RackHD/RackHD#187]
Latest code (20160416) w/ 3.19 version mircro-kernel can't discovery T41. Everything goes moothly until T41 boots into micro-kernel and resets before booting into micro-kernel successfully. Below picture shows screen shot before T41 reboots. 

![image](https://cloud.githubusercontent.com/assets/13991453/14597748/589d7418-0581-11e6-81cb-957358264a95.png)

Even after system reboot, no error logs will be recorded by RackHD since it is a OS issue w/ micro-kernel. Switch back to 3.16 micro-kernel, T41 can be discovered successfully.

**Comment by yyscamper** [comment]
I also reproduced this issue in virtual node.

**Comment by johren** [comment]
We are currently seeing this on all nodes in our smoke test.  All of the compute nodes fail to discover.  Quanta T41, Quanta D51, and Platform-R.

**Comment by benbp** [comment]
FYI @DavidjohnBlodgett

**Comment by benbp** [comment]
@pengz1 I've got a fix up for real hardware at https://github.com/RackHD/on-imagebuilder/issues/35, but unfortunately it's breaking our vBMCs at the moment, so we're going to revert back to the 3.16 microkernel (see https://github.com/RackHD/on-imagebuilder/pull/36/).

**Comment by pengz1** [comment]
@benbp , thanks for the update. Looks current code also have version embedded for overlay, we should correct that in "bootstrap-ubuntu.js" or change the script in 3.16 on-imagebuilder:
overlayfs: 'common/discovery.{{ options.kernelVersion }}.overlay.cpio.gz'

**Comment by anhou** [comment]
I heard multiple guys facing the basic discovery issue yesterday, Jenkins didn't  block this PR in previous test?  or it's PR dependency related? @jlongever  @RackHD/corecommitters

**Comment by pengz1** [comment]
Looks PR: https://github.com/RackHD/on-tasks/pull/164 also includes overlay change-back already.

**Comment by jlongever** [comment]
Looks like the kernel bump change was merged while Jenkin's smoke tests were failing: https://github.com/RackHD/on-tasks/pull/148

**Comment by benbp** [comment]
@anhou yep, the reason we couldn't catch it in the PR smoke tests was because of the interdependency on https://github.com/RackHD/on-tasks/pull/148

**Comment by yyscamper** [comment]
@jlongever : If the on-imagebuilder change the microkernel version, then whether the jenkins will auto build the new microkernel and do the testing? If so, for https://github.com/RackHD/on-tasks/pull/148, I think we should first merge the on-imagebuilder PR, then on-tasks.

**Comment by jlongever** [comment]
@yyscamper There is no Jenkins job for on-imagebuilder.  Those images are built and deployed to bintray through travis-ci.  Jenkin's downloads the images from bintray.

**Comment by pscharla** [comment]
@pengz1 Sounds like the solution here was to revert to 3.16 and there is no driving reason at this point to go back to 3.19. Suggest we close this issue unless someone has a specific reason to keep it open.

**Comment by heckj** [comment]
I'm good with closing it

**Comment by pengz1** [comment]
Close this PR as we already revert to 3.16.
