### ISSUE TITLE
Improve the skupack API error reporting

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#190]
I forget a quotation mark (after the key `name`) when defined the config.json of a skupack:
```json
"skuConfig": {
     "postDiscoveryGraph": {
            "name": abcdef"
        }
}
```

Then I used following command to insert this SKU pack
```
curl -X POST --data-binary @rinjin_test.tar.gz http://127.0.0.1:8080/api/1.1/skus/pack
```

RackHD rejected this request (this is expected), and the API returned following message and with http status code `500` (Internal Server Error):
```
{"error":"Failed to serve file request:Failed to serve file request:Unexpected token a"}
```

I think two problems or enhancement opportunities here:
1.  The error message is not clear enough to tell user the `config.json` is invalid, I would expect the message to directly tell user the `config.json` violates the JSON format.
2.  The return code `500` is not correct, `400` should be the right one
    
    400 Bad Request
    The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)

**Comment by zyoung51** [comment]
Tracked at: https://www.pivotaltracker.com/projects/1492890/stories/118178159

**Comment by amymullins** [comment]
Closing out issue, resolved in this merge: https://github.com/​RackHD/on-http/commi​t/ae1ccc4235eb5f704b​97c8b1650ae775674f57​28
