### ISSUE TITLE
Tasks' amqp subscription still exist after delete active workflow

### ISSUE THREAD

**Issue by anhou** [RackHD/RackHD#191]
after deleting active workflow, the deleted workflow's tasks' amqp subscription still exist. and when new workflow is started, deleted workflow's task amqp subscription still take effect, and new workflow run has problem, It's found when install ESX OS firstly, before it finished, DELETE this active workflow then run install RHEL OS workflow like below.
```
curl -X POST -H "Content-Type:application/json" -d @esxi_6.json http://localhost:8080/api/common/nodes/57161bc69b97098207bc2135/workflows?name=Graph.InstallEsx
curl -X DELETE localhost:8080/api/common/nodes/57161bc69b97098207bc2135/workflows/active
curl -X POST -H "Content-Type:application/json" -d @rhel_7.json http://localhost:8080/api/common/nodes/57161bc69b97098207bc2135/workflows?name=Graph.InstallRHEL
```
then found that machine's ipxe bootup with esxi's install-esx.ipxe profile, not using install-centos.ipxe profile.

**Comment by anhou** [comment]
today, I did some debug, found that when deleting active workflow, code path only goes to https://github.com/RackHD/on-taskgraph/blob/master/lib/task-runner.js#L191 , not go to https://github.com/RackHD/on-taskgraph/blob/master/lib/task-runner.js#L195  which call 'task.cancel()' should clean the amqp subscriptions.   maybe cancel taskgraph sequence should have an adjustment

**Comment by anhou** [comment]
@benbp any insights on this?

**Comment by benbp** [comment]
FYI @VulpesArtificem

**Comment by benbp** [comment]
@anhou it appears this filter is to prevent trying to call `cancel()` on undefined values. The question is why it is undefined (not in the activeTasks object) in the first place. One possibility is that specific task was never started/run, and so doesn't need to be cancelled.

**Comment by benbp** [comment]
Any chance there are log statements relating to AMQP subscription cleanup failures?

**Comment by anhou** [comment]
@benbp there's no AMQP subscription cleanup failure. but the AMQP subscription cleanup is not called, then cause above problem

**Comment by anhou** [comment]
@benbp @VulpesArtificem I think https://github.com/RackHD/on-core/pull/119 could resolve this issue, and I have a test, it pass. please review the PR
