### ISSUE TITLE
schedulerOverrides in graph definitions are ignored

### ISSUE THREAD

**Issue by stuart-stanley** [RackHD/RackHD#197]
When defining a graph, it is possible to add a key under "options" to override scheduler options on tasks within the graph. For example:
```
{
    ...
    "options": {
    "install-os": {
    "schedulerOverrides":
    { 
        "timeout": 3600000
    }
   ...
}
```

This is no longer working (it is ignored). This impacts (at least):
- os install timeouts
- poller timeouts
- probably some other things that set a timeout of -1 (infinite) will probably timeout now? (like dhcp lease)
others????

**Comment by heckj** [comment]
This appears to be a regression (at least from what I read in Slack) that happened somewhere when we merged the Workflow HA branches

**Comment by benbp** [comment]
It's a feature regression, and a bug in the regression that causes the now broken feature not to break things...

**Comment by hohene** [comment]
Ben, not quite sure what you mean in your last comment - it is a bug - but regression doesn't catch it?  We do need a fix for this for testing the 1.2 release. This is blocking test cases that are looking for errors, ie. bootstrap install errors and alert generation. Thanks!!

**Comment by benbp** [comment]
@hohene back from EMC world, sorry for the delay. Looking closer, we do support timeouts, but removed backwards compatibility with the `schedulerOverrides` magic option value (now it reads `options.timeout` instead). I'll add back in support for the `schedulerOverrides` option today.

**Comment by hohene** [comment]
Thanks Ben! and yep - knew you were at EMC world - very cool!!

**Comment by benbp** [comment]
^^ PR up.
