### ISSUE TITLE
Get HTTP 500 error in deleting a tag

### ISSUE THREAD

**Issue by nortonluo** [RackHD/RackHD#200]
Get HTTP 500 error in deleting a tag
I tried to delete a tag with name "newtag_ p9Y]fTG%2016-04-25 10:21:39.294000 p9Y]fTG%", but I get http 500 error and error message is 
{"message":"URI malformed"} 
. The delete url is encode as "newtag_%20p9Y%5DfTG%252016-04-25%2010%3A21%3A39.294000%20p9Y%5DfTG%25" 
 And the whole command is
`curl -X DELETE http://localhost:8080/api/1.1/tags/newtag_%20p9Y%5DfTG%252016-04-25%2010%3A21%3A39.294000%20p9Y%5DfTG%25`

 
@yyscamper @zyoung51 @amymullins @uppalk1

**Comment by zyoung51** [comment]
@nortonluo Changed from decodeURI to decodeURIComponent.  decodeURI will not decode %3A into colon because encodeURI will not encode colons.
