### ISSUE TITLE
IPMI password printed to taskgraph logs if IPMI command fails

### ISSUE THREAD

**Issue by shanemsully** [RackHD/RackHD#216]
When an ipmi command fails the entire command line is printed to the logs including the password. 

[error] [2016-05-04T14:41:50.046Z] [on-taskgraph] [Job.Ipmi] [Server] Failed to capture IPMI driveHealth status data.
 -> /workspace/RackHD/on-tasks/lib/jobs/ipmi-job.js:140
data:
  user:       ipmi
  password:   [REDACTED]
  host:       X.X.X.X
  node:       572a08f3f996afab3893c88d
  workItemId: 572a094f33f085bd383bf56d
error:
  stack:
    - Error: Command failed: /bin/sh -c /usr/bin/ipmitool -I lanplus -U ipmi -H X.X.X.X -P ipmi -c sdr type 0xd
    -
    -     at ChildProcess.exithandler (child_process.js:213:12)
    -     at emitTwo (events.js:87:13)
    -     at ChildProcess.emit (events.js:172:7)
    -     at maybeClose (internal/child_process.js:821:16)
    -     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  message:
    """
      Command failed: /bin/sh -c /usr/bin/ipmitool -I lanplus -U ipmi -H X.X.X.X -P ipmi -c sdr type 0xd

    """
  killed:        true
  code:          null
  signal:        SIGTERM
  cmd:           /bin/sh -c /usr/bin/ipmitool -I lanplus -U ipmi -H X.X.X.X -P ipmi -c sdr type 0xd
  stderr:
  isOperational: true

**Comment by amymullins** [comment]
Tracking story to cover this bug fix: https://www.pivotaltracker.com/projects/1492890/stories/119021365

**Comment by amymullins** [comment]
Closing out issue, resolved in https://github.com/RackHD/on-tasks/pull/195
