### ISSUE TITLE
IPMI password is returned when getting poller data

### ISSUE THREAD

**Issue by zyoung51** [RackHD/RackHD#217]
A GET to /api/1.1/pollers/:id/data, /api/1.1/pollers/:id/data/current, /api/2.0/pollers/:id/data, and /api/2.0/pollers/:id/data/current return the OBM username/password information in the clear.

```
curl http://localhost:8080/api/1.1/pollers/5717bdaa2fde0d3558187ee4/data/current | python -mjson.tool
[
    ... data clipped ...
    {
        "host": "172.31.128.18",
        "node": "5717bd63e89936175898dafb",
        "password": "admin",
        "timestamp": "Thu May 05 2016 19:38:26 GMT+0000 (UTC)",
        "user": "admin"
    }
]
```

**Comment by amymullins** [comment]
Tracking story: https://www.pivotaltracker.com/projects/1492890/stories/119029575

**Comment by yyscamper** [comment]
The current design is to change the password to `[REDACT]` to hide those sensitive info, see obm (https://github.com/RackHD/on-http/blob/master/lib%2Fserializables%2Fv1%2Fobm.js) and ssh (https://github.com/RackHD/on-http/blob/master/lib%2Fserializables%2Fv1%2Fssh.js)

**Comment by amymullins** [comment]
Closing issue, resolved in https://github.com/RackHD/on-tasks/pull/195
