### ISSUE TITLE
Change workflow name from "Graph.InstallEsx" to "Graph.InstallESXi"

### ISSUE THREAD

**Issue by anhou** [RackHD/RackHD#218]
During writing documents for Install OS workflows 'http://rackhd.readthedocs.io/en/latest/rackhd/index.html#supported-os-installation-workflows' found that ESXi's workflow name 'Graph.InstallEsx' is not the same with other OS workflow in upper/lower case, 'Esx' is not the naming convention of 'ESX', and now our VMware OS installation are mainly focused on newer version 'ESXi' 5.5/6.0 (ESX is older versions before 5.0), so  I suggest change workflow name Graph.InstallEsx" to "Graph.InstallESXi", any thoughts?
@RackHD/corecommitters @RackHD/rackhd_dev

**Comment by heckj** [comment]
yeah, good by me - would be more consistent that way anyway

**Comment by yyscamper** [comment]
Agree on this change.

**Comment by PaynePei** [comment]
have encountered such issue in my test, i am a little confused at that moment, wait for this change :)

**Comment by leoyjchang** [comment]
Story has been created to solve this ticket at https://www.pivotaltracker.com/story/show/119417561
