### ISSUE TITLE
Switch, PDU or Managed Server created even with invalid parameters

### ISSUE THREAD

**Issue by tfuehrer** [RackHD/RackHD#220]
See internal ODR-594.

As part of negative testing, it was noticed that a Network Switch was added to the catalog even when using invalid IP Address format when initiating a switch discovery.

Command:

https:....redfish/v1/OEM/OnRack/Switch

{
  "ipaddress": "string",
  "community": "string"
}

A text string was used in place of the dot-notated IP Address. A Response Code of 202 was returned and a Node ID was assigned to a new switch entry in the catalog.

A check should be added to the code to verify the correct format of the IP Address (i.e. xx.xx.xx.xx). Possibly in the PDU and Managed Server add command also. The result of a wrong format should result in a "400"  response code.

This should be a low priority add to the code.

**Comment by zyoung51** [comment]
RackHD's IP address regex should also be adjusted (or deprecated).  The current regex: IpAddress: /^(\d+)\.(\d+)\.(\d+)\.(\d+)$/ (https://github.com/RackHD/on-core/blob/master/lib/common/constants.js#L197) allows invalid IP addresses.  

The validation added with schema's in 2.0 (https://github.com/RackHD/on-http/blob/59bba6a03f5c6a727d7f4e6f9b8a8fd8f08da53d/lib/services/schema-api-service.js#L34) which uses validator's isIP may be a better choice.

**Comment by benbp** [comment]
@tfuehrer @zyoung51 I'm not sure this is an issue with RackHD in regards to switch properties specifically. We don't actually support an IP Address field for switches or switch SNMP settings (you can certainly *add* it, but we'll do nothing *with* it). Instead, for switch SNMP settings, we use the schema required fields `"host"` and `"community"`, where host can be any valid hostname, so all we do is enforce a string requirement, nothing more (see the JSON schema used here: https://github.com/RackHD/on-http/blob/master/lib/serializables/v1/snmp.js#L23-L31).

**Comment by pscharla** [comment]
@tfuehrer: Is this still a valid issue based on the above comments? Sounds like ipAddress field is unused if set for switches.

**Comment by tfuehrer** [comment]
I agree the issue should not apply to switches since the IP address is optional. However the bug is written to cover Servers and PDU's also (it was originally found when adding compute nodes).

**Comment by pscharla** [comment]
@tfuehrer : Doing cleanup of older items. Given Ben's reasoning above, I see a similar format for the ssh settings for a server where we don't support an IP address field for servers. For ssh settings we use schema required fields `"host"`, `"user"`, and `"publicKey"`. As with the switch, host can be any valid hostname so we do string enforcement:
https://github.com/RackHD/on-http/blob/master/lib/serializables/v1/ssh.js#L20-L56

**Comment by pscharla** [comment]
Just tied off on this with @frostr3 and we agreed to close based on the reasoning above.
