### ISSUE TITLE
ESXi workflow indicates completion before the OS installation is complete

### ISSUE THREAD

**Issue by zyoung51** [RackHD/RackHD#221]
The ESXi installation workflow indicates the installation is complete when the esx-ks file is requested by the targetted node at the beginning of the installation. The installation should not be indicated as completed until the OS installation is completed.

**Comment by ebedros** [comment]
@amymullins  Internal ODR 682 associated

**Comment by amymullins** [comment]
3 Required PRs have been merged (1.2 branch)
