### ISSUE TITLE
TravisCI fetches code from Wrong Pull Request #

### ISSUE THREAD

**Issue by cgx027** [RackHD/RackHD#222]
I get an error from TravisCI when submitting a PR against RackHD/on-tasks repo: https://github.com/RackHD/on-tasks/pull/191. 

I had tried to file the same PR against my own repo and find everything should be fine. PR against my own repo: https://github.com/cgx027/on-tasks/pull/1

Further debug find that, on RackHD/on-tasks, TravisCI featched the wrong PR# for tests. The correct PR@ should be #191 , but TravisCI fetches #192 for test. Travis log file can be found at: https://travis-ci.org/RackHD/on-tasks/jobs/129387465 

```
1.80s$ git clone --depth=50 https://github.com/RackHD/on-tasks.git RackHD/on-tasks
Cloning into 'RackHD/on-tasks'...
remote: Counting objects: 2836, done.
remote: Compressing objects: 100% (1328/1328), done.
remote: Total 2836 (delta 1725), reused 2537 (delta 1506), pack-reused 0
Receiving objects: 100% (2836/2836), 701.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1725/1725), done.
Checking connectivity... done.
$ cd RackHD/on-tasks
0.43s$ git fetch origin +refs/pull/192/merge:
remote: Counting objects: 28, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 28 (delta 18), reused 18 (delta 10), pack-reused 0
Unpacking objects: 100% (28/28), done.
From https://github.com/RackHD/on-tasks
 * branch            refs/pull/192/merge -> FETCH_HEAD
```

**Comment by heckj** [comment]
@cgx027 I'm afraid there's nothing we can do for these issues here, so I'm going to close this bug here.
