### ISSUE TITLE
[Doc] Packer Build : Ubuntu 14.03 is out of date and unavailable

### ISSUE THREAD

**Issue by panpan0000** [RackHD/RackHD#229]
according to  https://github.com/RackHD/RackHD/tree/master/packer/README.md
when we do 
> packer build -only=virtualbox-iso template-packages.json

it will fail.

In the template-packages.json, the "http://releases.ubuntu.com/14.04/ubuntu-14.04.3-server-amd64.iso" is no longer existing .
should update to 14.04.4 as this commit(https://github.com/RackHD/RackHD/commit/d9fc6110a3dbe8fb471ca71b134aa08fb2b33207) did to template.json 

But I guess 14.04.4 may be replaced by some others later . How we prevent this kind of issue happen again ? using some "latest" alias (if any) ?

**Comment by heckj** [comment]
Hey Peter,

I'm afraid there isn't an alias - and in fact, it's explicit about wanting not only a URL but also a checksum (md5 or sha) to validate the image you're intending to use. There's an updated version in template.json, I just didn't catch template-packages at the same time. I'll get a PR up for that ASAP.
