### ISSUE TITLE
Need nodeid in lookup record of passive-discovered switches for POAP

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#236]
In order to be able to run the POAP workflows on passively discovered switches, we need to have the nodeid in the lookup record.  This needs to be created at the time the switch is discovered so it doesn't try to active-discover when it sends the DHCP request.

Discussed with @benbp last night.

**Comment by johren** [comment]
This is an urgent issue for a customer engagement.

**Comment by johren** [comment]
I tried this on the latest build of the 1.2 branch and found that it is adding the lookup records for the switch but it is setting the nodeID to "".

**Comment by johren** [comment]
Keep in mind this is doing **passive** (not active) discovery on the switches.

**Comment by benbp** [comment]
@VulpesArtificem FYI

**Comment by johren** [comment]
Tried again with a new build of on-http and it seems to be working now.  Add this one to the list of issues related to our bad build.  Closing.

**Comment by benbp** [comment]
😈
