### ISSUE TITLE
OS install workflows - State task.wait.completion.uri timing out on Some Nodes

### ISSUE THREAD

**Issue by hohene** [RackHD/RackHD#238]
Performing the OS Install workflows.

Per the internal ODR-728:
During ESXi 5.5 and 6.0 (still testing other OS's) there is an intermittent issue with task.wait.completion.uri timing out and causing the workflow to fail.
For the Dell C6320, this was originally witnessed going from ESXi 5.5 to ESXi 6.0, but then it was repeated with running 5.5 over again repeatedly.

Please see the internal ODR for full logs.

Comment 1 per Valerie:
A T41 prior to timing out; ESXi has been installed for over 5 minutes and there has been no AMQP alert generated and the task.completion.uri and task.ssh.validation are still pending. They eventually timeout and the message is sent as failed.
...
Ohren, Jeanne added a comment - 2 hours ago
One additional note. I watched with Valerie as this was happening. I was monitoring the on-http logs and
did not see the completionUri request come in to the ORA.

**Comment by amymullins** [comment]
@hohene , can this github issue be closed out as the original ODR-728 was closed as invalid?

**Comment by amymullins** [comment]
Closing out issue, ODR-728 is no longer open.
