### ISSUE TITLE
[Build Error]  on-imagebuilder TravisCI failure

### ISSUE THREAD

**Issue by panpan0000** [RackHD/RackHD#244]
Detail in 
https://travis-ci.org/RackHD/on-imagebuilder/builds/133310178

also , it will block customer to build microkernel by themselves

who can take a look ?

**Comment by panpan0000** [comment]
@anhou  @pengt2

**Comment by panpan0000** [comment]
I meant, Its failure does not relative to that PR, but from master

**Comment by anhou** [comment]
double check that latest ansible 2.1.0.0 version has this problem

**Comment by anhou** [comment]
Fix is included in PR https://github.com/RackHD/on-imagebuilder/pull/42

**Comment by panpan0000** [comment]
ok. Thx.
