### ISSUE TITLE
sharedKey isn't documented

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#256]
Per conversation in slack channel, the configuration `sharedKey` that we can an example of in our configuration, isn't documented as to what it is, how it's used, or how to create another one.

Add to our documentation. 

Verify it’s a shared encryption key for encrypting/decrypting data as it goes in and out of MongoDB (data encryption at rest kinda thing). It’s a pre-set shared secret key that can be provided via config - string format. It’s a `base64` key relevant for `aes-256-cbc`. So I think (@benbp can you verify when you’re kicking) that the a 256 byte randomly generated and base64 encoded would be a good “in production” replacement.

**Comment by heckj** [comment]
@pscharla can you have one of the monorail gang go through, review the relevant code, and update the docs at https://github.com/RackHD/docs/blob/master/docs/rackhd/configuration.rst to include `sharedKey` and what reasonable values are for it?

**Comment by pscharla** [comment]
@heckj OK. Will do.

**Comment by pscharla** [comment]
Pivotal tracker link here:
https://www.pivotaltracker.com/n/projects/1492888/stories/126555983

**Comment by pscharla** [comment]
PR is ready to be merged:
https://github.com/RackHD/docs/pull/318
