### ISSUE TITLE
Ubuntu Package Based Installation does not deploy monorail-undionly.kpxe

### ISSUE THREAD

**Issue by seyoung720** [RackHD/RackHD#261]
Following the instructions for the Ubuntu Package Based installation at https://rackhd.readthedocs.io/en/latest/packaging_and_deployment.html (section 7.7) results in the deployment of undionly.kpxe instead of monorail-undionly.kpxe. The instructions for manually downloading the binary files in the section titled "RackHD Binary Support Files", are as follows:
 
for file in $(echo "\
undionly.kpxe \
monorail.ipxe \
monorail-efi64-snponly.efi \
monorail-efi32-snponly.efi");do
wget "https://dl.bintray.com/rackhd/binary/ipxe/$file"
done

When the compute nodes under management subsequently try to boot they fail to find monorail-undionly.kpxe, and node discovery/cataloging fails. From /var/log/upstart/tftp.log:

![image](https://cloud.githubusercontent.com/assets/1584803/15875142/89cec7a6-2cd4-11e6-9f04-b548ef962023.png)

The correct file (monorail-undionly.pxe) exists in bintray so I believe this is just a documentation bug on the RackHD readthedocs site:

![image](https://cloud.githubusercontent.com/assets/1584803/15875325/5ba2d01a-2cd5-11e6-8557-ecc8a8cfc4f0.png)

The issue can be reproduced by following the instructions for the Ubuntu Package Based Installation from the RackHD site (as referenced above).

The Ansible-based installation detailed in "7.6. Ubuntu Source Based Installation" works fine and correctly downloads monorail-undionly.kpxe.

Both installations were tested with the latest version of RackHD.

**Comment by anhou** [comment]
@seyoung720 Good catch, Thanks for report this docs bug. It's a miss  when other places were updated.  https://github.com/RackHD/docs/pull/289  is submitted to fix this. if any other docs bugs you've found, feel free to submit a PR to https://github.com/RackHD/docs  . the docs repo is maintained there.
