### ISSUE TITLE
EventEmitter has hit MaxListeners 

### ISSUE THREAD

**Issue by BillyAbildgaard** [RackHD/RackHD#262]
Error seen in travis builds showing ```warning: possible EventEmitter memory leak detected```

Can be seen in travis build: https://travis-ci.org/RackHD/on-http/jobs/135950465

![image](https://cloud.githubusercontent.com/assets/14279042/15907107/c198ad40-2d89-11e6-9d12-4dd53b8fd94e.png)

tried increasing max amount of listeners, and that did not fix the issue.

**Comment by hohene** [comment]
I opened an ODR on this for the internal 1.2 branch, full logs are available there.  This occurred on an upgrade from the 1.0.6 to 1.2.0 latest build.  ODR-761

**Comment by rolandpoulter** [comment]
I have a patch that will silence the memory leak warnings for amqp connections. 

Patch:
https://github.com/RackHD/on-core/commit/cbf408f1f589f15295772a2480a8f132a747e5db

Unit Tests:
https://travis-ci.org/rolandpoulter/on-core/jobs/136286587

**Comment by johren** [comment]
Is the issue fixed in amqp 0.2.6?

**Comment by brianparry** [comment]
@rolandpoulter So it looks like we have 12 exchanges.  Did you choose 24 to allow additional headroom for exchanges to be added in the future or was that required to eliminate the warnings?

**Comment by BillyAbildgaard** [comment]
@rolandpoulter @johren is there changes in the later versions of amqp that you guys need?  

If not, should we just change amqp version to 2.0.3, which is before this issue presented itself?

**Comment by heckj** [comment]
recommend we pin it back explicitly to `2.0.3` per conversation on the slack channel. We didn't need any new features, just let the version float where we expected semantics would operate within expected bounds (i.e. semantic API spec), but the introduction of the leak in the dependency would warrant pinning this to a version we know is OK.

**Comment by BillyAbildgaard** [comment]
made a PR doing just that.  I tried to link it to this issue as well.  If it worked properly or not is another story

https://github.com/RackHD/on-core/pull/155

**Comment by rolandpoulter** [comment]
@BillyAbildgaard  @heckj @brianparry I believe it is usually better to try to stay current with dependency versions, than to pin it back. Unlike other platforms NodeJS and NPM packages evolve rapidly and if you get in the habbit of pinning versions back you'll have a much hard time updating in the future.
