### ISSUE TITLE
RackHD SKU pack for arista-dcs-7124S fails to load with error

### ISSUE THREAD

**Issue by gpaulos** [RackHD/RackHD#264]
The SKU pack for arista-dcs-7124S from 'https://github.com/RackHD/on-skupack' fails to load via curl and generates the error below:

curl -X POST -F file=@tarballs/arista-dcs-7124S_arista-dcs-7124S.tar.gz stack4-ora.admin:8080/api/common/skus/pack 

```
{"error":"Failed to serve file request:Failed to serve file request:[Error (E_VALIDATION) 1 attribute is invalid] Invalid attributes sent to skus:\n • rules\n   • \"skuRules\" validation rule failed for input: { path: 'version.Hardwaremodel', equals: 'AristaDCS-7124S-F' }\nSpecifically, it threw an error.  Details:\n { name: 'AssertionError',\n  actual: 'object',\n  expected: '[object]',\n  operator: '===',\n  message: 'rules ([object]) is required' }\n"}
```

SKU pack tarball was created using:
 ./build-package.bash arista-dcs-7124S arista-dcs-7124S

Server logs here:
https://web.hwimo.lab.emc.com/qa/log/bug_logs/ODR-756

ODR-756
https://hwjiraprd01.corp.emc.com/browse/ODR-756

**Comment by heckj** [comment]
fyi @pscharla

**Comment by pscharla** [comment]
OK. Thanks for the heads up. Will take a look.

**Comment by benbp** [comment]
@pscharla rules needs to be an array of objects rather than an object is what is looks like (see https://github.com/RackHD/on-skupack/blob/master/arista-dcs-7124S/config.json#L3).

**Comment by pscharla** [comment]
Gotcha. Thanks!

**Comment by pscharla** [comment]
The PR with the fix is now merged:

https://github.com/RackHD/on-skupack/pull/26#event-687751762
