### ISSUE TITLE
failed to get processor information with redfish api:/Systems/{identifier}/Processors/{socket} 

### ISSUE THREAD

**Issue by PengTian0** [RackHD/RackHD#269]
try to run proboscis with two physical nodes(both quanta d51),
one case failed: Testing GET /Systems/{identifier}/Processors/{socket} .

Then I run the api manually, I also got error.
here is the logs:
onrack@ORA:~$ curl localhost:8080/redfish/v1/Systems/575ed5a33131496a7ca56a2e/Processors |python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   456  100   456    0     0  10652      0 --:--:-- --:--:-- --:--:-- 10857
{
    "@odata.context": "/redfish/v1/$metadata#Systems/Links/Members/575ed5a33131496a7ca56a2e/Processors/#entity",
    "@odata.id": "/redfish/v1/Systems/575ed5a33131496a7ca56a2e/Processors",
    "@odata.type": "#Procssors.1.0.0.ProcessorsCollection",
    "Members": [
        {
            "@odata.id": "/redfish/v1/Systems/575ed5a33131496a7ca56a2e/Processors/0"
        },
        {
            "@odata.id": "/redfish/v1/Systems/575ed5a33131496a7ca56a2e/Processors/1"
        }
    ],
    "Members@odata.count": **2**,
    "Name": "Processors Collection",
    "Oem": {}
}
onrack@ORA:~$ curl localhost:8080/redfish/v1/Systems/575ed5a33131496a7ca56a2e/Processors/0 |python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   696  100   696    0     0  12437      0 --:--:-- --:--:-- --:--:-- 12654
{
    "@odata.context": "/redfish/v1/$metadata#Systems/Links/Members/575ed5a33131496a7ca56a2e/Processors/Members/$entity",
    "@odata.id": "/redfish/v1/Systems/575ed5a33131496a7ca56a2e/Processors/0",
    "@odata.type": "#Processor.1.0.0.Processor",
    "Id": "0",
    "InstructionSet": "x86-64",
    "Manufacturer": "Intel",
    "MaxSpeedMHz": 2300,
    "Model": "Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz",
    "Oem": {},
    "ProcessorArchitecture": "x86",
    "ProcessorId": {
        "EffectiveFamily": "Xeon",
        "EffectiveModel": "Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz",
        "IdentificationRegisters": "F2 06 03 00 FF FB EB BF",
        "MicrocodeInfo": "",
        "Step": "",
        "VendorId": "GenuineIntel"
    },
    "ProcessorType": "CPU",
    "Socket": "SOCKET 0",
    "Status": {},
    "TotalCores": 10,
    "TotalThreads": 20
}
onrack@ORA:~$ curl localhost:8080/redfish/v1/Systems/575ed5a33131496a7ca56a2e/Processors/1 |python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   716  100   716    0     0   9002      0 --:--:-- --:--:-- --:--:--  9063
{
    **"error": {
        "@Message.ExtendedInfo": [
            {
                "@odata.type": "#Message.1.0.0.Message",
                "Description": "Indicates that the request failed for an unknown internal error but that the service is still operational.",
                "Message": "The request failed due to an internal service error.  The service is still operational.",
                "MessageId": "Base.1.0.Messages.InternalError",
                "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service.",
                "Severity": "Critical"
            },
            {
                "Description": "Contains the detailed error message contents",
                "Message": "Unexpected token U",
                "MessageId": "RackHD.1.0.DetailedErrorMessage"
            }
        ],
        "code": "Base.1.0.GeneralError",
        "message": "A general error has occurred. See ExtendedInfo for more information."
    }**
}

**Comment by PengTian0** [comment]
and ipmi sdr show:
![sdr](https://cloud.githubusercontent.com/assets/19203416/16004452/4bc1c8e0-3194-11e6-88de-1b1040c83822.PNG)

bios information:
![image](https://cloud.githubusercontent.com/assets/19203416/16004488/80229998-3194-11e6-9af0-a16bb571b160.png)

**Comment by heckj** [comment]
@PengTian0 this is referencing a PR that you've merged, was this issue resolved with that PR?

**Comment by PengTian0** [comment]
@heckj  yes, the PR fixed the issue

**Comment by PengTian0** [comment]
@heckj here is the commit link:
https://github.com/RackHD/on-http/commit/55727e8686a3077a58b37e79ab623200dcfbdb92
