### ISSUE TITLE
X-Forwarded-For missing in API Proxy support

### ISSUE THREAD

**Issue by jlmcknight** [RackHD/RackHD#278]
Building on the recent API proxy support added in the following pull requests:

https://github.com/RackHD/on-http/pull/274
https://github.com/RackHD/on-core/pull/131
https://github.com/RackHD/on-tasks/pull/185

The API proxy support, in addition to looking at the `X-REAL-IP` HTTP header, should also look for the `X-Forwarded-For` HTTP header.  Some proxy software (squid3 for example) does not allow setting arbitrary HTTP headers in the chain, but does support adding `X-Forwarded-For` to pass on the real ip address of the originating client.

**Comment by amymullins** [comment]
New story created, will plan to review with the team later this week in refinement: https://www.pivotaltracker.com/projects/1496834/stories/122668211

**Comment by jlmcknight** [comment]
Had a conversation with @keedya on slack this morning, so here is a deeper explanation of our use case:

Our production sites all need to talk to a set of proxies to get to things like OS distribution repositories, etc.  Because RackHD doesn't give the functionality in `monorail.json` to add upstream proxy information for `httpProxies`, you can only give it 'localPath', 'server', 'remotepath', this caused us issues in getting to upstream repositories.  

In the case of Ubuntu, we solved this by installing `apt-cacher-ng` local on the RackHD servers, and creating an entry in `monorail.json` `httpProxies` for `/ubuntu` to redirect to the RackHD server on the port `apt-cacher-ng` listens on.  Then `apt-cacher-ng` is configured to talk out through the right proxies.

However, when dealing with non-ubuntu distributions there is no `apt-cacher-ng` type tool that we can leverage to hand off the upstream communication.  In these cases (sles/rhel/centos etc) we need to stand up a squid3 proxy on the RackHD host and pass in the proxy information during the OS install (autoyast.xml/kickstart etc).  In our testing of this setup things go well until the OS install needs to pull anything from RackHD, since the communication is coming through a proxy, RackHD doesn't know how to resolve the fetching of templates.

For instance, a SLES11 install looks like this:

1.  Node pxeboots normally (no proxy involved)
2.  Repo information passed down hits the `/sles11` (configured in `monorail.json`) proxy path on the RackHD server, which redirects it to the local squid instance on the RackHD server.
3.  The initial download of the OS bits happen without any issues.
4.  SLES11 gets far enough to request the autoyast.xml, and this is where it blows up.  The request for the template hits `/sles11`, then to the local squid3 instance, then to the rackhd server.  Because the request looks to be coming from the local RackHD server, RackHD can't associate the template request with a host that has an active workflow it returns a 503.  If RackHD honored `X-Forwarded-For` in this case, it would see the right IP and the lookup process would work accordingly.

I hope that makes sense, please let me know if you need more info.
