### ISSUE TITLE
Bintray debian packages not getting updated.

### ISSUE THREAD

**Issue by jlongever** [RackHD/RackHD#283]
Debian packages not getting updated,  looks like package version expired. 

```
travis_fold:end:dpl.1
[Bintray Upload] Reading descriptor file: .bintray.json
[Bintray Upload] Uploading file 'deb/on-http_1.1-1master1_amd64.deb' to dists/trusty/main/binary-amd64/on-http_1.1-1master1_amd64.deb
[Bintray Upload] Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be deployed to.
[Bintray Upload] Uploading file 'deb/python-on-http-api1.1_1.1-1master1_amd64.deb' to dists/trusty/main/binary-amd64/python-on-http-api1.1_1.1-1master1_amd64.deb
[Bintray Upload] Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be deployed to.
[Bintray Upload] Uploading file 'deb/python-on-http-api2.0_1.1-1master1_amd64.deb' to dists/trusty/main/binary-amd64/python-on-http-api2.0_1.1-1master1_amd64.deb
[Bintray Upload] Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be deployed to.
[Bintray Upload] Uploading file 'deb/python-on-http-redfish-1.0_1.1-1master1_amd64.deb' to dists/trusty/main/binary-amd64/python-on-http-redfish-1.0_1.1-1master1_amd64.deb
[Bintray Upload] Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be deployed to.
[Bintray Upload] Publishing version 'master' of package 'packages'...
[Bintray Upload] Bintray response: 200 OK.
```

**Comment by jlongever** [comment]
@RackHD/corecommitters fyi

**Comment by anhou** [comment]
@jlongever yes, the version is expired, I didn't get any method to workaound it, I'm trying to remove related deb packages manually to workaround
https://bintray.com/docs/api/#_content_uploading_publishing
https://github.com/softprops/bintray-sbt/issues/35

**Comment by anhou** [comment]
on-syslog,on-http,on-syslog, on-taskgraph,on-dhcp-proxy are updated

**Comment by chrisdembia** [comment]
I have this same issue now for my own project (https://github.com/opensim-org/opensim-core). We were hoping to maintain a "latest" binary release on bintray. We use travis-ci to update that binary release with every push to the master branch. Could you explain how you solved this issue? Looking through your codebase, it's not obvious to me how you solved it.

Thank you!

**Comment by heckj** [comment]
Hey @chrisdembia 

The "solution" was really sort of a hack - we appended a date string (monotonically increasing) onto a base version, most of that hackery being in setting up an ENV variable called `DEBBRANCH` which we then pass into the cli `dch` that updates the change log in debian/ directory just prior to building the latest debian package.

Code bits:
 - https://github.com/RackHD/on-tftp/blob/master/extra/make-deb.sh#L19-L20
 - https://github.com/RackHD/on-tftp/blob/master/extra/make-deb.sh#L31
 - https://github.com/RackHD/on-tftp/blob/master/extra/make-deb.sh#L39
 - https://github.com/RackHD/on-tftp/blob/master/extra/make-deb.sh#L59

Bintray *really* didn't like pushing the same "version" (which is what was happening previously) of the debian to their repository and it sometimes updated and sometimes didn't. 

Not saying this is perfect in any way - but it's functional to what we need. The resulting debian files look like:

    `on-tftp_1.1-1master-20160718063750Z1_amd64.deb`

**Comment by chrisdembia** [comment]
Thank you for the detailed explanation! I greatly appreciate that you took the time to help out a fellow developer!
