### ISSUE TITLE
Modify template file will cause template meta error

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#286]
I modified the template file "centos-ks", then I restart  the on-http service. When I tried to run the workflow to install CentOS, it reported an error about "template meta error" while the installer trying to download the centos-ks.

In such situation, I need to clear the database for all template meta documents, then I can successfully run the workflow.

I expect the on-http can auto load the new version of template file.

Below is the error log:
```
http-1 [error] [2016-06-28T06:46:47.942Z] [on-http] [common-api-presenter] [Server] template meta error
http-1  -> /lib/services/common-api-presenter.js:108
http-1 error:
http-1   message: template meta error
http-1   name:    InternalServerError
http-1   context:
http-1   status:  500
http-1 path:  /templates/centos-ks
http-1 [debug] [2016-06-28T06:46:47.944Z] [on-http] [Http.Server] [16344b] http: GET 500 38.121 - /api/current/templates/centos-ks
http-1  -> /lib/services/http-service.js:321
```

**Comment by yyscamper** [comment]
@brianparry any insight?

**Comment by benbp** [comment]
@lacarb reported a similar error to me when just hitting the nodes API. Doesn't make any sense why we'd be hitting this at all from that route:

```
lacarb@linux-ws:~$ curl http://localhost:9090/api/2.0/nodes | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     100  1187  100  1187    0     0  11246      0 --:--:-- --:--:-- --:--:-- 11304
{
  "stack": "Error: template meta error    at _processError (/home/vagrant/src/on-http/lib/services/swagger-api-service.js:43:19)    at /home/vagrant/src/on-http/lib/services/swagger-api-service.js:216:22    at b (domain.js:183:18)    at tryCatcher (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)    at Promise._settlePromiseFromHandler (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)    at Promise._settlePromiseAt (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)    at Promise._settlePromises (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)    at Async._drainQueue (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)    at Async._drainQueues (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)    at Async.drainQueues (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)    at process._tickDomainCallback (node.js:459:13)",
  "status": "500",
  "message": "template meta error"
}
```

**Comment by brianparry** [comment]
@yyscamper @benbp Not sure how this error is showing up for the nodes API.  I wonder if it has something to do with the nodes view which is a renderable object like templates and profiles  The behavior @yyscamper describes is as-designed.  I made some changes a while ago to make the file system the "source of truth" for templates and profiles.  Previously, renderable objects deleted or modified via the API would be overwritten on service restart.  Now, we maintain a database record to track metadata mainly to allow scoping.  Part of the metadata in the database is an MD5 hash which is validated any time a template or profile is retrieved.  When you change a profile, template, or view without using the API or restarting on-http, you'll get this error.

**Comment by yyscamper** [comment]
Thanks @brianparry , as talked in Slack, please update the error message to be more clear.

**Comment by brianparry** [comment]
The change @yyscamper requested has been merged so I'm closing this issue
