### ISSUE TITLE
ESXi SSH validation task fails if no users are defined

### ISSUE THREAD

**Issue by benbp** [RackHD/RackHD#287]
Hat tip to @keedya 

The intended behavior of the SSH validation task is to skip doing validation and succeed if no users are defined in the workflow options. Apparently we are not doing a skip and are timing out on SSH validation for no defined users.

**Comment by keedya** [comment]
Another Issue here is  that SSH Validation gets stuck in a loop if lookups returns an empty array

**Comment by leoyjchang** [comment]
This issue should go away as ssh validation step in all OS installation has been removed. Close this ticket.
