### ISSUE TITLE
Documentation : example

### ISSUE THREAD

**Issue by mmumshad** [RackHD/RackHD#29]
In the documentation for example application, under Set Up instructions, shouldn't it be `pushd example/bin/` instead of `pushd bin/`

**Comment by heckj** [comment]
When I wrote it, I was assuming you were already in the example directory since the README is there - did that not track for you?

**Comment by mmumshad** [comment]
But before that you said
```
$ pushd example/config/
$ cp ./monorail_rack.cfg.example ./monorail_rack.cfg
$ popd
```

so if you follow these step by step, it doesn't work.. not a big deal.. it's minor issue..thought of letting you know.

**Comment by heckj** [comment]
yep, I see what you mean - will cover it in a PR that I'm doing right now
