### ISSUE TITLE
Lookup find by term Fails to query entry by node ID

### ISSUE THREAD

**Issue by keedya** [RackHD/RackHD#291]
Found that lookup find by term in ssh validation fails every time to query entries by node id.
The failure seems related to type mismatch between nodeId string and node stored in lookup table as objectId

**Comment by yyscamper** [comment]
This should be the same reason with https://github.com/RackHD/RackHD/issues/288, need database migration.

**Comment by heckj** [comment]
@keedya could you verify this was resolved with the patch merged above?

**Comment by keedya** [comment]
@heckj I verified this fix with ssh Validation task and lookup api (querying by nodeid)
Is there any other tasks you want me to run related to this issue?

**Comment by heckj** [comment]
If you're happy, then I'm happy. Close this bug up?

**Comment by amymullins** [comment]
@heckj and @keedya Can we hold off closing ~30 more minutes until we get confirmation this resolves CI build issues?

**Comment by heckj** [comment]
yes, please!

**Comment by amymullins** [comment]
Confirmed CI build issues resolved and CI is back green status.  Closing out this issue.
