### ISSUE TITLE
WSS Image missing in Docker HUB

### ISSUE THREAD

**Issue by victorock** [RackHD/RackHD#294]
Hello,
The image for WSS Service is not automagically available on Docker Hub.
It breaks the non build activities of https://github.com/RackHD/RackHD/blob/master/docker/docker-compose.yml

Sincerely,
Victor da Costa

**Comment by lanchongyizu** [comment]
Hello @victorock , you could change it as a workaround
FROM
    image: rackhd/on-wss:latest
TO
    image: roland/on-wss:latest

And wait @rolandpoulter for a fix.

**Comment by pscharla** [comment]
Checking with @rolandpoulter on this one

**Comment by rolandpoulter** [comment]
@pscharla https://hub.docker.com/r/rackhd/on-wss is up
