### ISSUE TITLE
reboot rackhd 

### ISSUE THREAD

**Issue by James-Dao** [RackHD/RackHD#297]
hi,
I try to use rackhd to automatically manage bare metal. When i reboot the machine which installed rackhd, i do not know how to check whether it is running. Is there any method to do it?

From DaoCloud

**Comment by anhou** [comment]
Just use 'ps aux | grep on-' to see if  5 'on-xxxx' processes are running. they are on-taskgraph/on-http/on-syslog/on-tftp/on-dhcp-proxy

**Comment by James-Dao** [comment]
Thanks

**Comment by leoyjchang** [comment]
Close this ticket as question has been answered.
