### ISSUE TITLE
how to set ip on multi network card

### ISSUE THREAD

**Issue by James-Dao** [RackHD/RackHD#299]
Hi,

When there are multi network cards, such as eth0 , eth1 and so on,  if eth1 is used as business, how to set static ip in data center?

From DaoCloud

**Comment by yyscamper** [comment]
@James-Dao : which network card? the ones in RackHD hosting OS or the computer node's OS after installing?

**Comment by James-Dao** [comment]
I mean that if i want to install ubuntu and this machine has two network cards ,  eth0 is often to be used to connect RackHD dhcp server, is it right?  so , i can use eth1 as business network card. I need to set the static ip for eth1.

**Comment by James-Dao** [comment]
computer node

**Comment by anhou** [comment]
@James-Dao usually,  eth0 is the network interface you could access rackhd,  eth1 is the dhcp service interface, the defaul IP is 172.31.128.1 . more network configuration, you could refer to http://rackhd.readthedocs.io/, one section describe all kinds of network configurations.  it seems it's 'Service Unavailable" at present, maybe it will be back after a while

**Comment by James-Dao** [comment]
"eth0 is the network interface you could access rackhd, eth1 is the dhcp service interface, the defaul IP is 172.31.128.1" 

It sounds like RackHD Controller ,not compute node.

**Comment by anhou** [comment]
@James-Dao for how to set static ip for installed os in computed node. more payload information could be found at  http://rackhd.readthedocs.io/en/latest/rackhd/index.html#non-windows-os-installation-workflow-payload .  a example is at https://github.com/RackHD/RackHD/blob/master/example/samples/install_ubuntu_payload_full.json

**Comment by James-Dao** [comment]
Thanks

**Comment by James-Dao** [comment]
As for RackHD controller, is there need to set eth1 nic to 172.31.128.1?  I run into some errors with docker to run Rackhd controller.  on-http , on-tftp, isc-dhcp-server and on-core start failed.

on-http error:

vents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 172.31.128.1:9080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickDomainCallback (node.js:400:17)

on-tftp error:

[info] [2016-07-07T03:31:14.608Z] [on-tftp] [Services.Configuration] [Server] Configuration value is undefined, using default (taskgraph-store => mongo).
 -> /RackHD/on-core/lib/services/configuration.js:73
[info] [2016-07-07T03:31:15.450Z] [on-tftp] [Services.Configuration] [Server] Configuration value is undefined, using default (color => undefined).
 -> /RackHD/on-core/lib/services/configuration.js:73
[info] [2016-07-07T03:31:15.456Z] [on-tftp] [Services.Configuration] [Server] Configuration value is undefined, using default (logColorEnable => undefined).
 -> /RackHD/on-core/lib/services/configuration.js:73
[critical] [2016-07-07T03:31:15.531Z] [on-tftp] [Tftp.Server] [Server] TFTP main socket error:
 -> /lib/server.js:62
code:    EADDRNOTAVAIL
errno:   EADDRNOTAVAIL
syscall: bind
address: 172.31.128.1
port:    69

isc-dhcp-server error:

No subnet declaration for eth0 (10.1.9.130).
** Ignoring requests on eth0.  If this is not what
   you want, please write a subnet declaration
   in your dhcpd.conf file for the network segment
   to which interface eth0 is attached. **


No subnet declaration for docker_gwbridge (172.20.0.1).
** Ignoring requests on docker_gwbridge.  If this is not what
   you want, please write a subnet declaration
   in your dhcpd.conf file for the network segment
   to which interface docker_gwbridge is attached. **


No subnet declaration for docker0 (172.17.0.1).
** Ignoring requests on docker0.  If this is not what
   you want, please write a subnet declaration
   in your dhcpd.conf file for the network segment
   to which interface docker0 is attached. **


No subnet declaration for br-3ec9266d9510 (172.19.0.1).
** Ignoring requests on br-3ec9266d9510.  If this is not what
   you want, please write a subnet declaration
   in your dhcpd.conf file for the network segment
   to which interface br-3ec9266d9510 is attached. **


No subnet declaration for br-9c76c39d150c (172.18.0.1).
** Ignoring requests on br-9c76c39d150c.  If this is not what
   you want, please write a subnet declaration
   in your dhcpd.conf file for the network segment
   to which interface br-9c76c39d150c is attached. **


Not configured to listen on any interfaces!

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.

**Comment by James-Dao** [comment]
root@ubuntu119:/home/ubuntu/RackHD/docker/monorail# ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:cf:88 brd ff:ff:ff:ff:ff:ff
    inet 10.1.9.130/24 brd 10.1.9.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:feb5:cf88/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:3d:7f brd ff:ff:ff:ff:ff:ff
    inet6 fe80::250:56ff:feb5:3d7f/64 scope link
       valid_lft forever preferred_lft forever
4: br-3ec9266d9510: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:80:b0:a3:ec brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 scope global br-3ec9266d9510
       valid_lft forever preferred_lft forever
5: docker_gwbridge: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:fc:09:39:fb brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/16 scope global docker_gwbridge
       valid_lft forever preferred_lft forever
6: br-9c76c39d150c: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:ce:e6:e2:96 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global br-9c76c39d150c
       valid_lft forever preferred_lft forever
    inet6 fe80::42:ceff:fee6:e296/64 scope link
       valid_lft forever preferred_lft forever
7: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:13:3f:c3:c0 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever

**Comment by yyscamper** [comment]
@James-Dao : Whether your problem has been resolved now?

**Comment by leoyjchang** [comment]
Close this ticket as we questions has been answered and didn't hear concern from submitted for a long time.
