### ISSUE TITLE
how to identify node id, when installing multipul machines

### ISSUE THREAD

**Issue by James-Dao** [RackHD/RackHD#300]
Hi,

When i use RackHD to install one machine , i need to identify the node id , then use it call another api to do something, if there is only one machine , i can read the ouput json to find it , but if there are some machines to install at the same time , how to identify every machine's node id and use node id to do something such as installing operation system or rebooting machine and so on. 

From DaoCloud

**Comment by yyscamper** [comment]
Hi @James-Dao :
1. The node information records the node's MacAddress in `identifiers` list, you can use the MacAddress to identify the node:
```
    {
        "autoDiscover": false,
        "createdAt": "2016-07-05T02:28:51.038Z",
        "id": "577b1b6393ea853d2ebbd1b9",
        "identifiers": [
            "52:54:be:ef:40:45"
        ],
        "name": "52:54:be:ef:40:45",
        "obmSettings": [],
        "relations": [
            {
                "relationType": "enclosedBy",
                "targets": [
                    "577b1ba76f9c69242e23fce2"
                ]
            }
        ],
        "sku": "577b1ba76f9c68742e12d1de",
        "tags": [],
        "type": "compute",
        "updatedAt": "2016-07-05T02:29:59.962Z"
    }
```

2. You can also turn to use lookup to find the node, search `lookups` by either macAddress or ipAddress.
```
[
    {
        "createdAt": "2016-07-05T02:28:50.181Z",
        "id": "577b1b62421845ae10f83054",
        "ipAddress": "172.31.128.8",
        "macAddress": "52:54:be:ef:40:45",
        "node": "577b1b6393ea853d2ebbd1b9",
        "updatedAt": "2016-07-05T02:30:17.411Z"
    }
]
```

3. You can manually post some tags to a node, then you can use the tag to identify the node you want, detail is here: http://rackhd.readthedocs.io/en/latest/rackhd/index.html?highlight=tags#node-tags

**Comment by James-Dao** [comment]
I need to iterate the nodes array, then use node id to find mac address or ip address, right?

**Comment by anhou** [comment]
@James-Dao Right

**Comment by James-Dao** [comment]
Thanks

**Comment by yyscamper** [comment]
@James-Dao: if you use lookups, you don't need to iterate the nodes array, below HTTP request will return the node you want:
```
curl http://<RackHD-IP>:8080/api/common/lookups?q=<MAC-ADDRESS>
```

**Comment by James-Dao** [comment]
Thanks

**Comment by leoyjchang** [comment]
Close this ticket as question has been answered.
