### ISSUE TITLE
skip ubuntu dhcp setting step 

### ISSUE THREAD

**Issue by James-Dao** [RackHD/RackHD#301]
Hi,

When installing ubuntu operation system, it always shows the dhcp setting screen, if so , the automatic installation process will be interrupted.  how to skip it?

From DaoCloud

**Comment by yyscamper** [comment]
@WangWinson: you may have the answer.

**Comment by WangWinson** [comment]
Hi @James-Dao,  

The ubuntu installing we support currently is only net installer mode. So the install process will always ensure the net work setting works at first. 
So if my guess correct. You may try manually update the dhcp config on the rackhd server, just add the last line to **/etc/dhcp/dhcp.conf** as below:
>
...
subnet 172.31.128.0 netmask 255.255.252.0 {
range 172.31.128.2 172.31.131.254;
 Use this option to signal to the PXE client that we are doing proxy DHCP
option vendor-class-identifier "PXEClient";
**option routers 172.31.128.1**;


Then reboot dhcp service or the rackhd server , then restart the install os workflow to see if this solve the issue.
Note: above example suppose your rackhd control network NIC is set to 172.31.128.1

Thanks

**Comment by James-Dao** [comment]
got it. thanks. I will try it.

**Comment by anhou** [comment]
@WangWinson @yyscamper @leoyjchang  a story for this https://www.pivotaltracker.com/story/show/120504923 was created previously

**Comment by leoyjchang** [comment]
Close this ticket as question has been answer.
