### ISSUE TITLE
how to build local mirror

### ISSUE THREAD

**Issue by James-Dao** [RackHD/RackHD#302]
Hi,

Is there any document to describe how to build own local operation system mirror ? If i want to install some types of OS, i hope that OS can be installed quickly. It can download some packages from local mirror. 

From DaoCloud

**Comment by anhou** [comment]
@James-Dao we docuemnt how to make the mirror at http://rackhd.readthedocs.io/en/latest/packaging_and_deployment.html#making-the-mirrors. but it's out-of-date updated.  and some other OSes are  not included. we'll create a story to track this. make a local OS mirror is not the functionally of RackHD. you could find all kinds of OS mirror setup on the internet. although we also could document them in RackHD docs.
just pay attention that Ubuntu mirror will consume much disk spaces compared with other OSes (either apt-mirror or rsync)  if you're located in Shanghai/China, you could try to use http://cn.archive.ubuntu.com which is at aliyun, In my previous test, the performance is also fine to save your time.

**Comment by heckj** [comment]
@James-Dao If you are asking about how to mirror OS files for Os installation/provisioning on RackHD, the details tend to be specific to the operating system that you're mirroring - SUSE, RedHat, CentOS, and Ubuntu all have slightly different mirroring mechanisms they have optimized for. The link that @anhou provided above has some examples. These will need to matched to profiles in RackHD or options provided when running the OS.Install to match to the locations that you host those mirrors - either on the same instance hosting RackHD's processes, or it's own endpoint. Its typically in the form of a URL (i.e. `http://...`). You can see some of those details in the documentation at http://rackhd.readthedocs.io/en/latest/rackhd/install_os.html

**Comment by James-Dao** [comment]
The location in config file is "httpProxies", right?

**Comment by anhou** [comment]
@James-Dao  Yes. you could refer to  http://rackhd.readthedocs.io/en/latest/rackhd/index.html#configuration-parameters for 'httpProxies' fields

**Comment by James-Dao** [comment]
Thanks

**Comment by leoyjchang** [comment]
Close this ticket as James got the answer.
