### ISSUE TITLE
deploy RackHD with Docker on multiple host

### ISSUE THREAD

**Issue by James-Dao** [RackHD/RackHD#303]
Hi,

Now, RackHD has support to install with Docker. I found the compose file that only supports local deployment, it can not be deploy on multi-host.  I think that ELK often use most of resources, such as memory , cpu and disk. In order to improve the stability, ELK runs on single host or single cluster.  Is there plan to provide compose file to deploy RackHD on multi-host?

From DaoCloud

**Comment by anhou** [comment]
@James-Dao As I know, no plan for this yet. RackHD roadmap plans are at https://github.com/RackHD/RackHD/wiki/roadmap, So welcome post proposal to rackhd@googlegroups.com. and more, welcome contribution on this :).

**Comment by rolandpoulter** [comment]
@James-Dao you can still separate ELK from RackHD, the current example does run everything on a single machine. It is meant to provide an example of RackHD working within Docker.

However like I said you could configure it differently.  See: https://github.com/RackHD/RackHD/blob/master/docker/logstash/config/logstash.conf

The only piece of RackHD that uses Elasticsearch is the UI which doesn't require ELK to be running unless you want it to remember old logs.

You could also move MongoDB and RabbitMQ to their own machines:
https://github.com/RackHD/RackHD/blob/master/docker/monorail/config.json

But all the main RackHD containers need to run on the same machine.

**Comment by leoyjchang** [comment]
Close this ticket as we questions has been answered and didn't hear concern from submitted for a long time.
