### ISSUE TITLE
run Rackhd with docker failed

### ISSUE THREAD

**Issue by James-Dao** [RackHD/RackHD#306]
Hi,

When installing ubuntu, it will shows the error on on-taskgraph. Maybe its version is not right ? 

error info:

"state":"failed","terminalOnStates":["timeout","cancelled","failed"],"error":"AssertionError: No OBM service assigned to this node.\n    at AssertService.(anonymous function) [as ok](/RackHD/on-core/lib/common/assert.js:30:28)\n    at /RackHD/on-taskgraph/node_modules/on-tasks/lib/jobs/obm-control.js:78:24\n    at tryCatcher (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)\n    at Promise._settlePromiseAt (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)\n    at Async._drainQueue (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate](/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback](timers.js:383:17)"},"ecdc33d4-a72d-4017-8112-1b3bf76565ac":{"friendlyName":"Set Node Pxeboot","injectableName":"Task.Obm.Node.PxeBoot","implementsTask":"Task.Base.Obm.Node","schemaRef":"rackhd/schemas/v1/tasks/obm-control","options":{"action":"setBootPxe"},"properties":{"power":{}},"instanceId":"ecdc33d4-a72d-4017-8112-1b3bf76565ac","runJob":"Job.Obm.Node","label":"set-boot-pxe","name":"Task.Obm.Node.PxeBoot","waitingOn":{},"ignoreFailure":true,"state":"failed","terminalOnStates":[],"error":"AssertionError: No OBM service assigned to this node.\n    at AssertService.(anonymous function) [as ok](/RackHD/on-core/lib/common/assert.js:30:28)\n    at /RackHD/on-taskgraph/node_modules/on-tasks/lib/jobs/obm-control.js:78:24\n    at tryCatcher (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)\n    at Promise._settlePromiseAt (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)\n    at Async._drainQueue (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate](/RackHD/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback](timers.js:383:17)"},"5fc6d709-cff9-48d1-b80d-027fc072f59d":{"friendlyName":"Install Ubuntu","injectableName":"Task.Os.Install.Ubuntu","implementsTask":"Task.Base.Os.Install","schemaRef":"rackhd/schemas/v1/tasks/install-os-general","options":{"osType":"linux","profile":"install-ubuntu.ipxe","installScript":"ubuntu-preseed","installScriptUri":"http://172.31.128.1:9080/api/current/templates/ubuntu-preseed","hostname":"rackhd-node","comport":"ttyS0","domain":"abc.com","completionUri":"renasar-ansible.pub","version":"trusty","repo":"http://172.31.128.1:9080/ubuntu","rootPassword":"RackHDRocks!","rootSshKey":null,"users":[],"networkDevices":[],"dnsServers":[],"installDisk":"/dev/sda","kvm":false},

From DaoCloud

**Comment by anhou** [comment]
It looks like it's a error 'AssertionError: No OBM service assigned to this node'  Do you have use the latest master codes? if yes, please check the 'obms' in this node, and GET /api/2.0/obms to see if the obms exist.

**Comment by James-Dao** [comment]
Just do it as the document said using docker-compose up.

**Comment by James-Dao** [comment]
anyone can test it ?

**Comment by James-Dao** [comment]
it says "Cannot GET /api/2.0/obms"

**Comment by pscharla** [comment]
Will see if I can enlist the help of @rolandpoulter here

**Comment by rolandpoulter** [comment]
@James-Dao Not sure if you figured this out yet, but certain graphs require a `obmSettings` field on the node. Otherwise the graph will fail with the error you pasted above.

Assuming you were testing this out with a VirtualBox node. You should be able to add an OBM to your node:
```
PUT /api/2.0/obms 
body:
{
    nodeId: <nodeId>,
    config: {},
    service: "vbox-obm-service" OR "noop-obm-service"
}
```

I don't believe there is anything wrong with running RackHD on Docker.

**Comment by pscharla** [comment]
@James-Dao Let us know the result here after @rolandpoulter suggestions and if you still need any help. Thanks!!

**Comment by pscharla** [comment]
No response. Closing this one out.
