### ISSUE TITLE
Bootstrap Ubuntu taking longer than expected time

### ISSUE THREAD

**Issue by kaleo211** [RackHD/RackHD#31]
Normally, it only takes like no more than 2 minutes.
But these day, it takes more than 10 minutes, with the same rackhd server and rackhd nodes.

Is there any debug methods we could try?

**Comment by heckj** [comment]
Hey @kaleo211,

When you say it normally takes no more than 2 minutes, was that using an earlier version of RackHD, or a separate system?

We found the Ubuntu installs to be fairly time consuming I'm afraid, they're also the most intense with file transfer, which is where (at a complete guess with no data) most of the time is being consumed.

If you watch the logs from the on-http process, you'll see all the requests back and forth during the install process, and that should give some sense of if that's the bottleneck or not. Right now, we're serving all files through on-http (serves static files as well as the REST API), so as a single process it could be the bottleneck. I'd need more information from you to help verify that though.

If that does turn out to be the issue, you can host the static files yourself using an alternate (faster, leaner) method. I would personally tend to suggest nginx for something like that. If you go this route, you'll need to tweak the template used for the installation (lines like https://github.com/RackHD/on-http/blob/master/data/templates/ubuntu-trusty-preseed#L4 and https://github.com/RackHD/on-http/blob/master/data/templates/ubuntu-trusty-preseed#L183) to reference the correct location for however you set up nginx.

You may also find that tweaking the debseed for an Ubuntu installation itself can render some speed benefits - the templates we have in there are examples, and you may want to tweak them for your own uses regardless.
