### ISSUE TITLE
bintray packages aren't updating ... again

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#310]
@anhou reset the bintray repos a week or two ago, but we're back to seeing that the packages built there aren't reflecting the latest code, as reported by @jlmcknight @ytjohn and John Inama in our slack channel.

We're pushing a "version" tag that is based on the branch, which for the latest builds on master is always "master" and never changing, so it's also impossible to tell what version the bintray deb packages are from.

IMO - we need to reset the package building to put some additional number on the tail end that's driven from Travis - even something as simple as a YYYYMMDD-HHMM - to extend the version detail with debian packaging so that we can validate the packages are getting updated, and have some better sense of metadata flowing into them to know if they're recent or older for people deploying the packages.

**Comment by anhou** [comment]
I go through on-http/on-taskgraph/.. travisci history ,  found  all packages are updated.  https://bintray.com/rackhd/debian/packages/master#files/dists/trusty/main/binary-amd64  not sure what's the problem. but I think add the version will help a lot for identify the problem
