### ISSUE TITLE
on-imagebuilder README should describe where do the OEM tool come from 

### ISSUE THREAD

**Issue by panpan0000** [RackHD/RackHD#314]
in https://github.com/RackHD/on-imagebuilder/blob/master/README.md
only  1.17.08_StorCLI.zip was described how user can retrieve them.
but for other vendor tool, nowhere describe how to obtain them.

only if those tools downloaded and put into on-imagebuilder/common folder, then "make_oem.sh" can pass and create all the OEM overlays .

**Comment by panpan0000** [comment]
without below files live in on-imagebuilder/common folder, make_oem.sh will fail :-)

1. Intel Tool :  flashupdt/syscfg
2. Quanta Tool: perccli_1.11.03-2_all.deb

@pengz1  ?

**Comment by panpan0000** [comment]
@PengTian0  is looking at this with @pengz1 's help....

**Comment by panpan0000** [comment]
**anyhow , if the source are all identified , the document should be updated.**

**Comment by leoyjchang** [comment]
Create a cookie story *https://www.pivotaltracker.com/story/show/126757413) to update the document

**Comment by ytjohn** [comment]
I ran into this myself today.  Here is what I came up with for perccli


```
cd /var/tmp
wget -q https://downloads.dell.com/FOLDER02444760M/1/perccli-1.11.03-1_Linux_A00.tar.gz -O perccli-1.11.03-1_Linux_A00.tar.gz
tar -xzf perccli-1.11.03-1_Linux_A00.tar.gz
alien perccli-1.11.03-1.noarch.rpm
cp perccli_1.11.03-2_all.deb /root/on-imagebuilder/common/files/perccli_1.11.03-2_all.deb
```

**Comment by ytjohn** [comment]
For storcli, the readme link is broken (curse you broadcom).

```
cd /var/tmp
wget -q https://downloadmirror.intel.com/25499/eng/StorCli_v1.17.08.zip
alien Linux/storcli-1.17.08-1.noarch.rpm
cp storcli_1.17.08-2_all.deb /root/on-imagebuilder/common/files/storcli_1.17.08_all.deb
```

**Comment by leoyjchang** [comment]
Good catch, @ytjohn. We didn't get chance to prioritize this issue. We'll screen these tools in Sprint after Chinese Festival Holiday. You could also post your findings here, so we can consolidate efforts on this. Thank you~~

**Comment by ytjohn** [comment]
Any updates on this?

**Comment by leoyjchang** [comment]
@ytjohn There was a RAC ticket opened for this github issue (https://rackhd.atlassian.net/browse/RAC-601), which we completed two weeks ago. We mainly updated download link for perccli and storcli.  Please tell us if this is enough for you.

Related PRs:
https://github.com/RackHD/on-imagebuilder/pull/78
https://github.com/RackHD/on-imagebuilder/pull/77

**Comment by ytjohn** [comment]
That should do it.  This issue can be closed.

**Comment by leoyjchang** [comment]
Close this issue as work was done.
