### ISSUE TITLE
on-http docker image build fail

### ISSUE THREAD

**Issue by cgx027** [RackHD/RackHD#316]
Checking dockhub and I find on-http image build had been failed since around 20 days ago: https://hub.docker.com/r/rackhd/on-http/builds/

The reason is that ```/RackHD/on-http/install-swagger-ui.sh``` use ```curl``` to download zip files but ```curl``` is not installed in the image. Adding ```curl``` at the end of apt line will fix the issue.

``` apk add --update ipmitool@testing unzip curl ```

With that, I also find the newly added ```install-task-doc.sh``` also prevent docker image from successfully built.  There are three reasons:

* ```install-task-doc.sh``` fail to run as it is decaired as a bash script but bash does not exist in docker image. Ref: 
 - https://github.com/RackHD/on-http/blob/master/install-task-doc.sh#L1
* ```install-task-doc.sh``` make use of ```on-core/spec/helper.js``` which in turn make use of ```supertest``` package will fail with missing package ```supertest```. The ```supertest``` is not installed because it's in the ```devDependances``` list which is not installed when using ```npm install --production`` inside Docerfile.  Ref:
 - https://github.com/RackHD/on-http/blob/master/Dockerfile#L11
 - https://github.com/RackHD/on-http/blob/master/package.json#L81
 - https://github.com/RackHD/on-tasks/blob/master/task-annotation-generator.js#L221
 - https://github.com/RackHD/on-core/blob/master/spec/helper.js#L21
* ```install-task-doc.sh``` make use of python for ```json.tool``` but python is not installed. Ref: https://github.com/RackHD/on-http/blob/master/install-task-doc.sh#L15

**Comment by cgx027** [comment]
@WangWinson

**Comment by WangWinson** [comment]
Good catch. I didn't test this in docker build yet. Will update.

**Comment by cgx027** [comment]
@WangWinson I just quickly created a PR against this issue: https://github.com/RackHD/on-http/pull/369

**Comment by WangWinson** [comment]
thans @cgx027, 
Alos, I submitted https://github.com/RackHD/on-tasks/pull/281 to replace the `python -m json.tool` solution
