### ISSUE TITLE
packer build using ubuntu 16.04 template fails to complete

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#325]
I ran through a packer build this weekend with 16.04 ubuntu as a base to see how it stands. Looks like there's some work before that'll be happy:

invoked:
  `packer build -only=virtualbox-iso template-ubuntu-16.04.json`

Errors:

```
    virtualbox-iso: Failed to start on-http.service: Unit on-http.service not found.
    virtualbox-iso: Failed to start on-taskgraph.service: Unit on-taskgraph.service not found.
    virtualbox-iso: Failed to start on-dhcp-proxy.service: Unit on-dhcp-proxy.service not found.
    virtualbox-iso: Failed to start on-syslog.service: Unit on-syslog.service not found.
    virtualbox-iso: Failed to start on-tftp.service: Unit on-tftp.service not found.
    virtualbox-iso: starting rackhd ./src services...
    virtualbox-iso: waiting for rackhd services..
    virtualbox-iso: failed: Connection refused.
    virtualbox-iso: failed: Connection refused.
    virtualbox-iso: failed: Connection refused.
    virtualbox-iso: No data received.
```

looks like `scripts/firstuser.sh` wasn't vetted and the service startup fails differently in Ubuntu 16.04 for setting initial user values

The `template-ubuntu-14.04.json` continues to work fine.

**Comment by panpan0000** [comment]
Now template-ubuntu-16.04.json   works fine on latest tip.

**Comment by leoyjchang** [comment]
Great, thanks for the information @panpan0000 . So I close this ticket since this issue got resolved.
