### ISSUE TITLE
reset on-tools

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#33]
Most of what's in the https://github.com/RackHD/on-tools repo is legacy that has pretty minimal value. At the same time, we've got scripts for deployment and simple management of an instance of RackHD buried in on-http, where they don't entirely make sense - but was easy to drop into place.

## reset and update on on-tools

- remove the dead scripts
- make sniff.js, logs.js, and events.js into NPM modules in their own directory in there
- move https://github.com/RackHD/on-http/blob/master/data/templates/setup_iso.py, https://github.com/RackHD/on-http/blob/master/data/templates/monorail-restore.sh, and https://github.com/RackHD/on-http/blob/master/data/templates/monorail-backup.sh into on-tools under a scripts directory
- add on-tools as a submodule to https://github.com/RackHD/RackHD
- update the README in on-tools to describe what's there
- move the bridgenetwork script snippets to docs about how to run RackHD on a mac laptop
- update the README instructions at https://github.com/RackHD/RackHD/blob/master/example/README.md with the new script locations

**Comment by tldavies** [comment]
Is this still open?

**Comment by heckj** [comment]
I never finished this out with updates to the documentation and making sure it all worked together...

**Comment by DavidjohnBlodgett** [comment]
@heckj hey Joe, just wanted to circle back on this and see if you'd like to delegate any pieces onto me, so we can close this. Just let me know!

**Comment by heckj** [comment]
@DavidjohnBlodgett you got it! The piece outstanding that I slacked off on doing was going through the documentation and specifically updating it with having moved the scripts that we wrote for unpacking the ISO, and then walk through the whole CentOS boot process that dumps the ISO and make sure everything is technically correct for the new locations of that code.

**Comment by DavidjohnBlodgett** [comment]
@heckj understood, I'll review whats there and try to push this forward.

**Comment by DavidjohnBlodgett** [comment]
WIP PR: https://github.com/RackHD/on-tools/pull/21
