### ISSUE TITLE
Reduce the number of logging levels

### ISSUE THREAD

**Issue by brianparry** [RackHD/RackHD#34]
Currently there are nine log levels available without clear a definition of their use.
https://github.com/RackHD/on-core/blob/master/lib/common/constants.js#L36-L44

To simplify logging and filtering, the number of log levels should be reduced to: 
- _debug_ 
- _info_
- _warning_
- _error_
- _critical_

In addiiton, notes describing conventions for using these levels should be published.

**Comment by benbp** [comment]
:

**Comment by heckj** [comment]
:+1:

**Comment by heckj** [comment]
PR's up for:
 - on-tasks
 - on-syslog
 - on-tftp
 - on-core
 - docs

Work TBD
 - on-http
 - on-taskgraph
 - on-dhcp-proxy

 - And then finally another PR to remove the no-longer-used levels in on-core
