### ISSUE TITLE
OBM defaults need to be asserted for workflows for no-op, even though no-op OBM defined

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#35]
I'm working through the installation effort of CentOS with the Vagrant/PXE demonstration setup. I'm leveraging the existing `Graph.InstallCentOS` graph, and my node has a no-op OBM service defined on it (the result of the demonstration flow from example/README)

The node:

```json
{
  "identifiers": [
    "08:00:27:f4:ca:1f"
  ],
  "name": "08:00:27:f4:ca:1f",
  "obmSettings": [
    {
      "service": "noop-obm-service",
      "config": {}
    }
  ],
  "relations": [
    {
      "relationType": "enclosedBy",
      "targets": [
        "566af70a6826416b15fc6075"
      ]
    }
  ],
  "sku": "566af6477c5de76d1530d1f2",
  "type": "compute",
  "updatedAt": "2015-12-11T19:20:17.647Z",
  "id": "566af6c77c5de76d1530d1f3"
}
```

I posted to this node to invoke the Install CentOS workflow with the command: 

```bash
curl -H "Content-Type: application/json" \
-X POST --data @samples/centos_iso_boot.json \ http://localhost:9090/api/1.1/nodes/566af6c77c5de76d1530d1f3/workflows
```

and the options for the workflow being:
```json
{
    "name": "Graph.InstallCentOS",
    "options": {
        "install-os": {
            "repo": "{{api.server}}/Centos/7.0"
        }
    }
}
```

This resulted in a positive response from the server, but on manual reboot of the node, the workflow failed. Digging out the error stanza from the workflow list for the nodes, I found:

```json
"error": {
                    "actual": null,
                    "expected": true,
                    "message": "Node should have OBM settings for service: ipmi-obm-service",
                    "name": "AssertionError",
                    "operator": "=="
                }
```

After talking with @benbp, he recalled there was a default setting inside the system to accommodate having more than one OBM service defined on a node, and that by default we attempt to use IPMI for our reboot tasks that are embedded within the Install.* workflows.

The error isn't clear on what you need to do, nor does it seem sensible that with only a single OBM service that you should get this error - that the noop-obm-service that's defined on the node should take precedence and work.

The workaround is to add a "defaults" stanza to the options when invoking the workflow:

```json
{
    "name": "Graph.InstallCentOS",
    "options": {
        "defaults": {
            "obmServiceName": "noop-obm-service"
        },
        "install-os": {
            "repo": "{{api.server}}/Centos/7.0"
        }
    }
}
```

Which apparently tells the workflow engine to default to the noop-obm-service for all workflow tasks, and overrides our internal code default.

I'd like to recommend that we change this internal functionality so that:

- if there's a single OBM service defined, the workflow will be default use that
- if there's more than one OBM service defined, and the workflow doesn't specify which to use, that the workflow should then fail with an error describing something like `more than one OBM service assigned to this node, no default set for which to use`
- a little scribbly documentation in the tasks and workflows docs about the fact that you *can* have more than one OBM service defined, and for tasks that utilize those (reboot, pxeboot, etc) you need to define either in the workflow, or in the task, which & what to  use.

**Comment by benbp** [comment]
:+1: I think this would only require a minimal change to the obm control job: https://github.com/RackHD/on-tasks/blob/047572018b67525fad61679bc18364ac6d317836/lib/jobs/obm-control.js.

**Comment by yyscamper** [comment]
Whether it means we should also not hard-code the "obmServiceName" from those obm-control task, like power-on: https://github.com/RackHD/on-tasks/blob/master/lib/task-data/tasks/power-on.js

**Comment by DavidjohnBlodgett** [comment]
@heckj @benbp @yyscamper hi guys, just looking into this issue, I think I hit this with my CentOS install and resolved it with a manual creation of OBM settings... just wanted to double check that this issue is still relevant, and if so... any additional info about suggestions for a solution. I've been looking at the code linked and though I see assertions being made against OBM properties, I'm not sure I follow how we would reference any defaults. Thanks!

**Comment by heckj** [comment]
It's still relevant - and yeah, we'll hit it in the "demo spaces" where we're working with raw PXE booting VMs that end up with a no-op OBM service associated with them
