### ISSUE TITLE
intermittent issue when discovering nodes

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#350]
from an internal jenkins build: http://rackhdci.lss.emc.com/job/Continuous-Test/job/Continuous-Functional/7309/artifact/build/vagrant.log

```
13:58:13 graph.1  |  taskRunnerId: 29a351da-4416-4949-b37d-61ca41a5e8a3
13:58:13 graph.1  |  error:
13:58:13 graph.1  |  stack:
13:58:13 graph.1  |    """
13:58:13 graph.1  |      TypeError: Cannot read property 'instanceId' of undefined
13:58:13 graph.1  |          at /home/vagrant/src/on-taskgraph/node_modules/on-core/lib/workflow/stores/mongo.js:374:31
13:58:13 graph.1  |          at tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
13:58:13 graph.1  |          at Promise._settlePromiseFromHandler (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
13:58:13 graph.1  |          at Promise._settlePromiseAt (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
13:58:13 graph.1  |          at Promise._settlePromises (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
13:58:13 graph.1  |          at Async._drainQueue (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
13:58:13 graph.1  |          at Async._drainQueues (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
13:58:13 graph.1  |          at Async.drainQueues (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
13:58:13 graph.1  |          at process._tickDomainCallback (node.js:459:13)
13:58:13 graph.1  |    """
13:58:16 http.1   |  Using monkey-patched Error.prototype.toJSON method, which will be deprecated soon.
13:58:16 http.1   |  [error] [2016-07-29T13:58:16.914Z] [on-http] [common-api-presenter] [Server] Request Timed Out (on.task:methods.requestProperties.579b60f52bd323d8072eea88:Object).
13:58:16 http.1   |   -> /lib/services/common-api-presenter.js:108
13:58:16 http.1   |  error:
13:58:16 http.1   |    message: Request Timed Out (on.task:methods.requestProperties.579b60f52bd323d8072eea88:Object).
13:58:16 http.1   |    name:    RequestTimedOutError
13:58:16 http.1   |    context:
13:58:16 http.1   |  path:  /profiles
13:58:16 http.1   |  [debug] [2016-07-29T13:58:16.918Z] [on-http] [Http.Server] [Server] http: GET 500 3204.524 - /api/current/profiles?macs=52%3A54%3Abe%3Aef%3Acb%3A02
13:58:16 http.1   |   -> /lib/services/http-service.js:328
13:58:16 http.1   |  ipAddress: 172.31.128.7
13:58:16 syslog.1 |  [info] [2016-07-29T13:58:16.923Z] [on-syslog] [Syslog] [Server] ipxe: http://172.31.128.1:9080/api/current/profiles?macs=52%3A54%3Abe%3Aef%3Acb%3A02...... Input/output error (http://ipxe.org/1d0c65
13:58:16 syslog.1 |   -> /lib/app.js:65
13:58:16 syslog.1 |  facility: 0
13:58:16 syslog.1 |  priority: 6
13:58:16 syslog.1 |  [info] [2016-07-29T13:58:16.930Z] [on-syslog] [Syslog] [Server] ipxe: 39)
13:58:16 syslog.1 |   -> /lib/app.js:65
13:58:16 syslog.1 |  facility: 0
13:58:16 syslog.1 |  priority: 6
13:58:16 syslog.1 |  [info] [2016-07-29T13:58:16.933Z] [on-syslog] [Syslog] [Server] ipxe: Could not boot image: Input/output error (http://ipxe.org/1d0c6539)
13:58:16 syslog.1 |   -> /lib/app.js:65
13:58:16 syslog.1 |  facility: 0
13:58:16 syslog.1 |  priority: 6
```

500 Error response from a /profiles request that caused iPXE to crap out (and fortunately to send the error to syslog)

Looks the under the covers, a graph being returned was undefined as a result of a waterline.graphobjects.fineOne() query based on the error message - was under the ‘getTaskById’ method in the mongo store. (https://github.com/RackHD/on-core/blob/master/lib/workflow/stores/mongo.js#L374)

**Comment by heckj** [comment]
@VulpesArtificem the results of the findOne() query can include a null response (from https://github.com/RackHD/on-core/blob/master/lib/workflow/stores/mongo.js#L371), which is what's causing this - the promise chain attempts to return when it's good, but I'm not sure what the appropriate response is when it's failing. Definitely appears that we're not catching and dealing with that error condition, but should we be doing something more at the mongo/interface layer with persistence to throw an error there?

The logic I found that uses this is within the reactive block, which is where I don't know how to apply any reasoning for "the way it *should* fail is..." (https://github.com/RackHD/on-taskgraph/blob/master/lib/task-runner.js#L148-L161)

**Comment by heckj** [comment]
@benbp ^^ if you have any insights here, would love them as well

**Comment by benbp** [comment]
@heckj I've always seen these errors in the past when there is a synchronization issue between the taskdependencies collection and the graphobjects collection, and only when I've manually deleted a document/documents in one but not the other. Unlikely that's the case here though.

**Comment by benbp** [comment]
@heckj to answer your question about how it _should_ fail, the call is wrapped within an error handler:

https://github.com/RackHD/on-taskgraph/blob/master/lib/task-runner.js#L105
https://github.com/RackHD/on-taskgraph/blob/master/lib/task-runner.js#L160

The inner DB call doesn't do any null check there because there _shouldn't_ be a code pathway that would cause that issue. That said, obviously we should add a null check there :)

**Comment by pscharla** [comment]
Will pick this up for the Monorail team

**Comment by pscharla** [comment]
We have ticket to track this one

**Comment by pscharla** [comment]
@VulpesArtificem made fixes for the logic hole described above with these PRs:
https://github.com/RackHD/on-taskgraph/pull/226
https://github.com/RackHD/on-core/pull/269
Closing this ticket now as the intemittent discovery issue itself has not been seen as of late.
