### ISSUE TITLE
ERROR: Error: image rackhd/on-wss:latest not found

### ISSUE THREAD

**Issue by ajeetraina** [RackHD/RackHD#354]
I tried running docker-compose pull but it ended up with the error message:

# docker-compose pull
Pulling files (rackhd/files:latest)...
latest: Pulling from rackhd/files
d0ca440e8637: Pull complete
05b5f203a3d0: Pull complete
38f188b76fb4: Pull complete
c89ecb5cbafd: Pull complete
630dda3e0b3d: Pull complete
5aee5b5075bb: Pull complete
77d2003c0808: Pull complete
38ef4c23ca28: Pull complete
b0ee505b565d: Pull complete
22a390b348bd: Pull complete
ea945067bff6: Pull complete
2c6b72d0c6c4: Pull complete
cf3714a04e5f: Pull complete
Digest: sha256:41143830f0a7da8861ef673bf30d3975984e71039796e842a917263b35ecab91
Status: Downloaded newer image for rackhd/files:latest
Pulling core (rackhd/on-core:latest)...
latest: Pulling from rackhd/on-core
e110a4a17941: Pull complete
3b8af7884faf: Pull complete
5c00a931db9d: Pull complete
f6e6c0d75b3e: Pull complete
Digest: sha256:13ceb0190a191219a93f1cd4d70f7ad821000d1fd3a5e14f382249fb69e20ca7
Status: Downloaded newer image for rackhd/on-core:latest
Pulling mongo (mongo:latest)...
latest: Pulling from library/mongo
5c68a10e9f3f: Pull complete
0110f95fa9c8: Pull complete
0cba4a42bc41: Pull complete
a6eafd7fba3f: Pull complete
703d9d7e0e21: Pull complete
7a4b36461321: Pull complete
5b3580f1488d: Pull complete
913554e7fcc9: Pull complete
2f9b4a452eb8: Pull complete
Digest: sha256:e599c71179c2bbe0eab56a7809d4a8d42ddcb625b32a7a665dc35bf5d3b0f7c4
Status: Downloaded newer image for mongo:latest
Pulling rabbitmq (rabbitmq:management)...
management: Pulling from library/rabbitmq
5c90d4a2d1a8: Pull complete
6089c6f096b9: Pull complete
23b5bfce8ad4: Pull complete
13946ed57420: Pull complete
f87077e96db6: Pull complete
91b271af1b6f: Pull complete
ae50560319c7: Pull complete
031a1dcbb47d: Pull complete
6ca65936d19d: Pull complete
44da2c895b8f: Pull complete
b33963637358: Pull complete
03658b60e6d0: Pull complete
cb39c06c1a97: Pull complete
147d1eaf83d5: Pull complete
d603280e7bb8: Pull complete
6da386aad6a3: Pull complete
Digest: sha256:34e2d37bbf141042840ce9efdbd0d7dfcc2101b4db135c55358b82dd84120694
Status: Downloaded newer image for rabbitmq:management
Pulling elasticsearch (elasticsearch:latest)...
latest: Pulling from library/elasticsearch
5c90d4a2d1a8: Already exists
ab30c63719b1: Pull complete
be275827e8b7: Pull complete
4cbd0b70645a: Pull complete
7d811bfac6eb: Pull complete
d35e5f0a148b: Pull complete
a17d585d8b66: Pull complete
79f385f1115e: Pull complete
ef4e10d7f225: Pull complete
7718adde794f: Pull complete
659b7b49db7d: Pull complete
c7debea69350: Pull complete
b3db15ab8afa: Pull complete
38c25943c55b: Pull complete
Digest: sha256:d866f6945a401e9486dc54c5242665692855ae58d4f0c42439925e9e5d9370ed
Status: Downloaded newer image for elasticsearch:latest
Pulling kibana (kibana:latest)...
latest: Pulling from library/kibana
357ea8c3d80b: Pull complete
9d99c1434c75: Pull complete
aa9e96f4d5f4: Pull complete
393684003c1e: Pull complete
e2578dae99ba: Pull complete
e93da2cb19e9: Pull complete
0fad8fa782fd: Pull complete
de9374ae6d43: Pull complete
3bab9bf1c98f: Pull complete
Digest: sha256:53aef5e425b1e2c719d3dc65d1f7bbf41930dfc8193d70283ce1ad3ca9050d88
Status: Downloaded newer image for kibana:latest
Pulling dhcp (rackhd/isc-dhcp-server:latest)...
latest: Pulling from rackhd/isc-dhcp-server
d0ca440e8637: Already exists
aa7a7f72c84c: Pull complete
e00c52c8c9ad: Pull complete
b00aac708b48: Pull complete
Digest: sha256:3b6849b4e12424c64d7194aef0781224c293965f75cb64fcb46d4dad62463548
Status: Downloaded newer image for rackhd/isc-dhcp-server:latest
Pulling logstash (logstash:latest)...
latest: Pulling from library/logstash
357ea8c3d80b: Already exists
52befadefd24: Pull complete
42f3df327392: Pull complete
3decae4e9763: Pull complete
0a60a7e0c31d: Pull complete
783d0812b9b6: Pull complete
2c49287cad2e: Pull complete
a7de2cf3c5b8: Pull complete
9f935a937c4d: Pull complete
92d2fb236d66: Pull complete
2e9ef30e353e: Pull complete
9b3ba42ab7a4: Pull complete
c73ae08f215d: Pull complete
b34c95fd5d23: Pull complete
Digest: sha256:52ee09b92448ead5563f3b37fc2fbebe56e270ff69e073dfb478a17a6243d041
Status: Downloaded newer image for logstash:latest
Pulling statsd (rackhd/on-statsd:latest)...
latest: Pulling from rackhd/on-statsd
e110a4a17941: Already exists
3b8af7884faf: Already exists
5c00a931db9d: Already exists
f6e6c0d75b3e: Already exists
d367dc7e528c: Pull complete
3db993aa70dd: Pull complete
36d8b69f480b: Pull complete
Digest: sha256:5b53440247a84697366a539f66f3b76e5e5061fb6ffe5f34d69aa6e20bc8059a
Status: Downloaded newer image for rackhd/on-statsd:latest
Pulling syslog (rackhd/on-syslog:latest)...
latest: Pulling from rackhd/on-syslog
e110a4a17941: Already exists
3b8af7884faf: Already exists
5c00a931db9d: Already exists
f6e6c0d75b3e: Already exists
394eee0f4ab7: Pull complete
e34b3a4347ed: Pull complete
Digest: sha256:7f1ed265011986af3139f1ac5b2554f67c5329b485a1f10715938c1d35e89280
Status: Downloaded newer image for rackhd/on-syslog:latest
Pulling tftp (rackhd/on-tftp:latest)...
latest: Pulling from rackhd/on-tftp
e110a4a17941: Already exists
3b8af7884faf: Already exists
5c00a931db9d: Already exists
f6e6c0d75b3e: Already exists
c55016117525: Pull complete
9fade46cc0a0: Pull complete
Digest: sha256:05d834f50eb35891588621b0d502908863ff89ebc9277bdc85c9b0e1f910ef1d
Status: Downloaded newer image for rackhd/on-tftp:latest
Pulling taskgraph (rackhd/on-taskgraph:latest)...
latest: Pulling from rackhd/on-taskgraph
e110a4a17941: Already exists
3b8af7884faf: Already exists
5c00a931db9d: Already exists
f6e6c0d75b3e: Already exists
5f89188426cb: Pull complete
a11a3f4c7589: Pull complete
Digest: sha256:b6a9afaa15e198cf1b141c4f005763f503965b37f6f1fb2817e6e3aafa382d55
Status: Downloaded newer image for rackhd/on-taskgraph:latest
Pulling dhcp-proxy (rackhd/on-dhcp-proxy:latest)...
latest: Pulling from rackhd/on-dhcp-proxy
e110a4a17941: Already exists
3b8af7884faf: Already exists
5c00a931db9d: Already exists
f6e6c0d75b3e: Already exists
150742b7db23: Pull complete
ca181b131dd6: Pull complete
Digest: sha256:5d8bc7d438af7ad4179171f66541d2bcac682e87f36b65e0c719e1a370d38b56
Status: Downloaded newer image for rackhd/on-dhcp-proxy:latest
Pulling http (rackhd/on-http:latest)...
latest: Pulling from rackhd/on-http
e110a4a17941: Already exists
3b8af7884faf: Already exists
5c00a931db9d: Already exists
f6e6c0d75b3e: Already exists
288cdb24be5d: Pull complete
a374f00c1598: Pull complete
Digest: sha256:8048bb99c6df69fd379c4829b0b2a6b2d09bfacf691d6678160f3996844adad7
Status: Downloaded newer image for rackhd/on-http:latest
Pulling wss (rackhd/on-wss:latest)...
Pulling repository docker.io/rackhd/on-wss
ERROR: Error: image rackhd/on-wss:latest not found

**Comment by heckj** [comment]
@rolandpoulter where are the docker builds set up? Did we miss adding in one for on-wss when we created that repo to add in the websocket layering?

**Comment by rolandpoulter** [comment]
I must have only created it for my github account. I can setup a new automated build for `rackhd/on-wss` for now you can use https://hub.docker.com/r/roland/on-wss/

**Comment by rolandpoulter** [comment]
Just created a automated build for `rackhd/on-wss` should be ready in about 15 minutes. https://hub.docker.com/r/rackhd/on-wss/

**Comment by heckj** [comment]
Thanks!

**Comment by johren** [comment]
I'm not seeing a rackhd/on-wss image on Docker Hub this morning.  Is there an issue with the automated build?  Or does it need to be triggered by a change to on-wss?

**Comment by heckj** [comment]
I was just wondering the same. I'll make a no-op merge to try and trigger something

**Comment by heckj** [comment]
@johren I think that's done it: https://hub.docker.com/r/rackhd/on-wss/builds/

**Comment by ajeetraina** [comment]
Thanks Team. I will be testing it soon.

On 2 Aug 2016 8:38 p.m., "Joseph Heck" <notifications@github.com> wrote:
>
> @johren I think that's done it:
https://hub.docker.com/r/rackhd/on-wss/builds/
