### ISSUE TITLE
OS installation files scattered in docs

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#355]
Some of the setup mirror stuff is under packaging and installation, other pieces in the OS install documentation. 

 - http://rackhd.readthedocs.io/en/latest/rackhd/install_os.html#setting-up-a-windows-os-repo
 - http://rackhd.readthedocs.io/en/latest/rackhd/ubuntu_package_installation.html?highlight=mirror#making-the-mirrors

We should converge these into a single location (likely the OS installation workflow documentation in the user's guide) and consolidate the missing pieces

**Comment by amymullins** [comment]
Tracking story: https://www.pivotaltracker.com/story/show/127638567

**Comment by amymullins** [comment]
PR has been merged, closing out this issue.
