### ISSUE TITLE
Centos-ks template render errors with `rootEncryptedPassword is not defined` with default options

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#36]
I'm working through the installation effort of CentOS with the Vagrant/PXE demonstration setup. I'm leveraging the existing `Graph.InstallCentOS` graph, and my node has a no-op OBM service defined on it (the result of the demonstration flow from example/README)

The node:

```json
{
  "identifiers": [
    "08:00:27:f4:ca:1f"
  ],
  "name": "08:00:27:f4:ca:1f",
  "obmSettings": [
    {
      "service": "noop-obm-service",
      "config": {}
    }
  ],
  "relations": [
    {
      "relationType": "enclosedBy",
      "targets": [
        "566af70a6826416b15fc6075"
      ]
    }
  ],
  "sku": "566af6477c5de76d1530d1f2",
  "type": "compute",
  "updatedAt": "2015-12-11T19:20:17.647Z",
  "id": "566af6c77c5de76d1530d1f3"
}
```

I posted to this node to invoke the Install CentOS workflow with the command: 

```bash
curl -H "Content-Type: application/json" \
-X POST --data @samples/centos_iso_boot.json \ http://localhost:9090/api/1.1/nodes/566af6c77c5de76d1530d1f3/workflows
```

and the options for the workflow being:
```json
{
    "name": "Graph.InstallCentOS",
    "options": {
        "defaults": {
            "obmServiceName": "noop-obm-service"
        },
        "install-os": {
            "repo": "{{api.server}}/Centos/7.0"
        }
    }
}
```

I unpacked the a CentOS installation ISO using: `vagrant ssh`

```bash
    cd /tmp
    # 636MB
    wget http://buildlogs.centos.org/rolling/7/isos/x86_64/CentOS-7-x86_64-Minimal.iso
    sudo python ~/src/on-http/data/templates/setup_iso.py /tmp/CentOS-7-x86_64-Minimal.iso /var/mirrors --link=/home/vagrant/src
````

which places the ISO repository into a location matching the "repo" stanza in the workflow options above (`~/src/on-http/static/http/Centos/7.0`).

# the problem

The workflow processes through to installation, and the kickstart template rendering fails. The exception in the logs (`on-http`):

```
19:47:28 http.1   |  E 2015-12-11T19:47:28.154Z [on-http] [common-api-presenter] [Server] ejs:26
19:47:28 http.1   |      24|
19:47:28 http.1   |      25| #Set the root account
19:47:28 http.1   |   >> 26| rootpw --iscrypted <%=rootEncryptedPassword%>
19:47:28 http.1   |      27|
19:47:28 http.1   |      28| #create all users
19:47:28 http.1   |      29| <% users.forEach(function(user) { %>
19:47:28 http.1   |  rootEncryptedPassword is not defined
19:47:28 http.1   |   -> /lib/services/common-api-presenter.js:197
19:47:28 http.1   |  error:
19:47:28 http.1   |    stack:
19:47:28 http.1   |      - ReferenceError: ejs:26
19:47:28 http.1   |      -     24|
19:47:28 http.1   |      -     25| #Set the root account
19:47:28 http.1   |      -  >> 26| rootpw --iscrypted <%=rootEncryptedPassword%>
19:47:28 http.1   |      -     27|
19:47:28 http.1   |      -     28| #create all users
19:47:28 http.1   |      -     29| <% users.forEach(function(user) { %>
19:47:28 http.1   |      -
19:47:28 http.1   |      - rootEncryptedPassword is not defined
19:47:28 http.1   |      -     at eval (eval at <anonymous> (/home/vagrant/src/on-http/node_modules/ejs/lib/ejs.js:464:12), <anonymous>:36:23)
19:47:28 http.1   |      -     at returnedFn (/home/vagrant/src/on-http/node_modules/ejs/lib/ejs.js:493:17)
19:47:28 http.1   |      -     at Object.exports.render (/home/vagrant/src/on-http/node_modules/ejs/lib/ejs.js:315:37)
19:47:28 http.1   |      -     at /home/vagrant/src/on-http/lib/services/common-api-presenter.js:242:34
19:47:28 http.1   |      -     at tryCatcher (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
19:47:28 http.1   |      -     at Promise._settlePromiseFromHandler (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:505:31)
19:47:28 http.1   |      -     at Promise._settlePromiseAt (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
19:47:28 http.1   |      -     at Promise._settlePromises (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
19:47:28 http.1   |      -     at Async._drainQueue (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
19:47:28 http.1   |      -     at Async._drainQueues (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
19:47:28 http.1   |      -     at Async.drainQueues (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
19:47:28 http.1   |      -     at process._tickDomainCallback (node.js:459:13)
19:47:28 http.1   |    arguments:
19:47:28 http.1   |      - rootEncryptedPassword
19:47:28 http.1   |    type:      not_defined
19:47:28 http.1   |    message:
19:47:28 http.1   |      """
19:47:28 http.1   |        ejs:26
19:47:28 http.1   |            24|
19:47:28 http.1   |            25| #Set the root account
19:47:28 http.1   |         >> 26| rootpw --iscrypted <%=rootEncryptedPassword%>
19:47:28 http.1   |            27|
19:47:28 http.1   |            28| #create all users
19:47:28 http.1   |            29| <% users.forEach(function(user) { %>
19:47:28 http.1   |        rootEncryptedPassword is not defined
19:47:28 http.1   |      """
19:47:28 http.1   |  path:  /templates/centos-ks
19:47:36 http.1   |  E 2015-12-11T19:47:36.855Z [on-http] [Services.ErrorPublisher] [Server] Event Loop Blocked
19:47:36 http.1   |   -> /node_modules/on-core/lib/services/error-publisher.js:93
19:47:36 http.1   |  host:     rackhd-demo
19:47:36 http.1   |  name:     on-http
19:47:36 http.1   |  severity: error
19:47:36 http.1   |  ms:       107
```

**Comment by yyscamper** [comment]
Hi @heckj:

The rootPassword is a required option for install-os, if not specified, the render error is expected for our current design. The option "version" is same as well.

About why I haven't added the assertion for rootPassword, I have described in the code (https://github.com/RackHD/on-tasks/blob/master/lib/jobs/install-os.js#L71-L80) 

Even so, we still can have some improvement:
 - Add the required options to the workflow definition, so you will not forget to specify this value.
- Add a default rootPassword if no password is specified.

**Comment by heckj** [comment]
Thanks @yyscamper 

I totally understand making the root password a required value for the task, the problem that I ran into was that it wasn't documented and there was no way to tell other than a template rendering failing in the logs - nothing in any of the REST API responses indicated a required value wasn't available.

I like both of your ideas for a "belt and suspends" solution to quick usage of our system, and was what I was thinking would be good solutions up front. We have also identified needing documentation for tasks to help offset this. As I was reading through this I thought of one more - probably more generally for workflows (@benbp):

The solutions above solve issues for the workflows we've created and are using, but our system is predicated around folks making their own workflows, where they may not realize these same kinds of issues. I think it would be a significant improvement if we could validate the options sent in for graphs (workflows) so that it was obvious at creation time. For example, use the required options for each of the tasks and defaults from the workflow files, and determine if any of the constraints are missed - like the required "root password" option in this case.

The second is deeper and more subtle, but under the idea that a user may not have access to the logs, when we have a template rendering failure, can we improve the information/error message that's included in the resulting workflow to identify what the template value was and that it was missing. That way there's sufficient information in the API response for the failed workflow for a user to know what's gone wrong.

**Comment by benbp** [comment]
One thing that will help with the refactor is that we are now doing the validation up front, so you will get failures immediately. Part of the challenge here is we are 
 using a task that is essentially polymorphic, but without being able to properly provide more than one schema. @jlongever and I have talked a little bit about the idea of having multiple optional schemas defined against a job when we do the work to move base task definitions into the jobs.

**Comment by yyscamper** [comment]
@heckj: 
We have documented in Confluence for which options are required for install-os, but that's not available  for open source user. I agree we have to improve the error message to tell user the exact cause when a failure happens. But there is a challenge that I described in the code (https://github.com/RackHD/on-tasks/blob/master/lib/jobs/install-os.js#L71-L80), as not all OS installation has supported these options, I have to add some code especially for ESXi/RHEL/CentOS. Personally these kinds of particular code is something I want to avoid but seems I still need to do this before other OS install job ready.

@benbp:
For the idea about  multi schema for task, that's good idea, I totally agree we need this.

For the up front validation, I just wanted to proposal this last week, but forgot :(. Currently the install-os workflow begins to validate the option when a task is scheduled, but the system has been pxe rebooted and around 5 min has passed, even for a very simple validation failure! Move the validation work up-front will give user a very quick error message for such simple error. However if only check the requiredOptions or the type in task schema (such as it should be a String, Number or Array...),  though this is basically required, it is still not enough, I think we need consider following cases:

1) How about if option is passed from context? Context value is get during workflow runtime, we need to separately validate the immediate value and context value.

2) How about some relative complex logic?
Following kind of validation is very common, but it is task specified and can be done up-front. Have we ever considered to support this in up-front validation?

For example: 
````javascript
if (options.vlanId < 0 || options.vlanId >= 4096) {
    throw new ValidationError('vlanId is not in required range');
}
````

````javascript
if (options.raidType == 'raid1') {
     if (options.physicalDriveNumer <= 1) {
           throw new ValidationError('physical drive number must be at latest 2 for RAID1');
    }
} else if (options.raidType == 'raid5') {
    if (options.physicalDriveNumber <= 2) {
         throw new ValidationError('physical drive number must be at least 3 for RAID5');
   }
}
````

**Comment by cgx027** [comment]
Guys, I had just filed and PR with regarding the short term solution, which is to set a default root password. Please let me know if this is not expected.

**Comment by cgx027** [comment]
@heckj where is the most suitable document for me to specify the default password please?

**Comment by heckj** [comment]
We don't yet have annotated documentation for our tasks or graphs (pending spec to enable that), so in the meantime my opinion is the best place would be with our user's guide until we have that in place. Likely the document specific to workflows: https://github.com/RackHD/docs/blob/master/docs/rackhd/graphs.rst

**Comment by cgx027** [comment]
Thanks Joe. Seems we have to wait till the spec reaches the install OS section.

**Comment by Gary15** [comment]
Hi,guys.I am sorry to disturb you.
I am just doing the steps like the @heckj  doing.But client can not get the centos.ks file.The [picture](https://goo.gl/photos/V8tSrVbG1G6kDSjt9) can show you.
And the client [start Dracut Emergency shell ](https://goo.gl/photos/3GgsRY9UPnEm4xAg8).

**Comment by heckj** [comment]
Hey @Gary15, not a problem. Probably better for this to be a separate issue, since I don't think it's related to the specifics of the kickstart since you don't appear to be getting that far from your image. I'll open another issue and do some digging to see if I can help point in how to troubleshoot this.
