### ISSUE TITLE
Unable to query workflows library in 1.1 API as documented

### ISSUE THREAD

**Issue by codenrhoden** [RackHD/RackHD#363]
The docs (http://rackhd.readthedocs.io/en/latest/rackhd/graphs.html#api-commands-for-graphs) say to do the following to get a list of Graphs:

`GET /api/1.1/workflows/library`

However, this is the response I get when doing so:

```
$ curl localhost:9090/api/1.1/workflows/library | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    84  100    84    0     0   3995      0 --:--:-- --:--:-- --:--:--  4200
{
    "message": "Could not find graphobject with criteria {\"instanceId\":\"library\"}."
}
```

The server side logs show the following:

```
5:21:01 PM http.1 |  [info] [2016-08-03T17:21:01.189Z] [on-http] [Services.Configuration] [Server] Configuration value is undefined, u…
5:21:01 PM http.1 |   -> /node_modules/on-core/lib/services/configuration.js:73
5:21:01 PM http.1 |  [error] [2016-08-03T17:21:01.202Z] [on-http] [Http.Services.RestApi] [Server] Could not find graphobject with cri…
5:21:01 PM http.1 |   -> /lib/services/rest-api-service.js:323
5:21:01 PM http.1 |  error:
5:21:01 PM http.1 |    message: Could not find graphobject with criteria {"instanceId":"library"}.
5:21:01 PM http.1 |    name:    NotFoundError
5:21:01 PM http.1 |    context:
5:21:01 PM http.1 |      criteria:
5:21:01 PM http.1 |        instanceId: library
5:21:01 PM http.1 |      collection: graphobjects
5:21:01 PM http.1 |    status:  404
5:21:01 PM http.1 |  path:  /workflows/library
5:21:01 PM http.1 |  NotFoundError: Could not find graphobject with criteria {"instanceId":"library"}.
5:21:01 PM http.1 |      at /home/vagrant/src/on-http/node_modules/on-core/lib/common/model.js:407:27
5:21:01 PM http.1 |      at tryCatcher (/home/vagrant/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js…
5:21:01 PM http.1 |      at Promise._settlePromiseFromHandler (/home/vagrant/src/on-http/node_modules/on-core/node_modules/waterline/n…
5:21:01 PM http.1 |      at Promise._settlePromiseAt (/home/vagrant/src/on-http/node_modules/on-core/node_modules/waterline/node_modul…
5:21:01 PM http.1 |      at Promise._settlePromises (/home/vagrant/src/on-http/node_modules/on-core/node_modules/waterline/node_module…
5:21:01 PM http.1 |      at Async._drainQueue (/home/vagrant/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/blue…
5:21:01 PM http.1 |      at Async._drainQueues (/home/vagrant/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/blu…
5:21:01 PM http.1 |      at Immediate.Async.drainQueues [as _onImmediate] (/home/vagrant/src/on-http/node_modules/on-core/node_modules…
5:21:01 PM http.1 |      at processImmediate [as _immediateCallback] (timers.js:383:17)
```

It's clearly trying to interpret `library` as a graph ID instead of an endpoint, as `/api/1.1/workflows/<instanceID>` is a valid endpoint to retrieve a specific graph.

`/api/1.1/workflows/tasks` has the exact same issue (on-http thinks "tasks" is an instanceID".

`/api/1.1/workflows/library/<injectable name>` works fine

The 1.1 API swagger spec is expecting this endpoint to work as well: https://github.com/RackHD/on-http/blob/master/static/monorail.yml#L653

Is there another way to query the list of graphs available?

**Comment by codenrhoden** [comment]
Ah - by seeing the logging output when running the Web GUI, I see that `GET /api/1.1/workflows/library/*` is what I really want here.

So there is a doc and API spec issue. Also, `/api/1.1/workflows/tasks/*` does not work, so it's unclear to me what the difference betwee `workflows/tasks` and `workflows/tasks/library` is intended to be. I think the former may not be necessary at all?

**Comment by heckj** [comment]
@codenrhoden sorry, yeah - it's sort of a crappy evolution of our original thinking (or lack thereof) around the URI structure here. The 1.1 setup never really worked the way we envisioned it, and we're replacing the structure significantly with the 2.0 API to be `/api/2.0/workflow/graphs` to get the list of workflows, and `/api/2.0/workflows/tasks` to get the list of individual tasks that can be composed into workflows. 

While it's not a full solution for this, https://github.com/RackHD/docs/pull/309 should help with at least some of the 2.0 API pieces with it's examples, and we need to deprecate the 1.1 API and update it's documentation appropriately. In the hosted docs there was supposed to be an update, but it doesn't look like it's rendering properly:

![screen shot 2016-08-03 at 11 27 33 am](https://cloud.githubusercontent.com/assets/43388/17377113/4a9aa5b2-596d-11e6-95c8-a0c00abc1b55.png)

**Comment by yyscamper** [comment]
I would rather think this is a bug for code rather than a doc issue.
I think the biggest problems is that there is a lot mismatching for API 1.1:
- `/api/1.1/workflows/library/*` is to get all graph definition, but `/api/1.1/workflows/task/library/*` will not get all task definition.
- `/api/1.1/workflows/library/:injectableName` is to get a graph definition, but no API `/api/1.1/workflows/tasks/library/:injectableName` to get a task definition.

I guess the reason why use `/api/1.1/workflows/library/*` to get all graph definitions is to distinguish the `/api/1.1/workflows/:instanceId` and `/api/1.1/workflows/tasks`. But if we carefully design the sequence of router, we can let these APIs work at expected because the instanceId will never be a string like `tasks`.

This is my PR to fix this issue as my preference: https://github.com/RackHD/on-http/pull/402
