### ISSUE TITLE
Service graphs are creating duplicates on taskgraph start

### ISSUE THREAD

**Issue by benbp** [RackHD/RackHD#371]
We should refrain from creating duplicate instances of a service graph if one already exists and is running. Instead, we're creating new ones on every reboot (this is very bad). Hat tip to Danielle Skinner who has 391 instances of the IPMI pollers running right now on her test system :)

If people have been seeing slowness issues on test environments, this would be a likely culprit. You can do a quick check from the RackHD server via:

```
mongo pxe
db.graphobjects.find({injectableName: 'Graph.Service.Poller'}).count()
```

FYI @heckj @pscharla

**Comment by benbp** [comment]
I'm betting it has to do with the removal of the `toJSON` method in the graph-object model:

https://github.com/RackHD/on-core/commit/7bebf9b1e8f5ba230882ed236ef9b840851a460a#diff-4cd9720a7ce15e21af87edcabd5d70f7L49
https://github.com/RackHD/on-core/blob/master/lib/workflow/stores/mongo.js#L395

**Comment by benbp** [comment]
Deleted my last comment, the issue here is we changed the default graph state value to `running`, but we still do a running check by looking for a `pending` status (FYI @rolandpoulter).

**Comment by heckj** [comment]
@ytjohn @jlmcknight when we get the related PR merged in for this, you'll definitely want it!
