### ISSUE TITLE
update simple decommission to use sgdisk instead of dd

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#373]
Per thread related to wiping up some left-overs on a satadom, the process we started with for quick filesystem eradication uses `dd if=/dev/zero of=/dev/$disk bs=512 count=1`

ref: https://github.com/RackHD/on-taskgraph/blob/master/lib/graphs/bootstrap-decommission-node-graph.js#L14

That wasn't apparently sufficient to clear off some extra tidbits that were left on a satadom, and the manufacturing team found/resorted to `sgdisk -z` instead of clear the drive.

We should probably go ahead and leverage `sgdisk -z` or `sgdisk --zap-all` as a better default for decommissioning in that workflow. I'm not entirely sure that our microkernel includes `sgdisk`, so it may be worth adding it if it doesn't already exist there.

**Comment by leoyjchang** [comment]
We chose hdparm utility to handle satadom in security erase development.  Add @pengz1 for awareness.

**Comment by pengz1** [comment]
Our micro-kernel doesn't include this sgdisk tool. Looks this tool deals with partition tables, we can add it to secure erase micro kernel if we have plan to use it.

**Comment by pscharla** [comment]
Just heard that the reason the original dd command, which was wiping out LBA 0 only I believe, did not work was because the drives in question were being partitioned with GPT.

**Comment by pscharla** [comment]
@pengz1 I couldn't find that story in your backlog. Is it completed or actively being worked?  Maybe you can provide the link? Thanks.

**Comment by leoyjchang** [comment]
@pscharla here is the story link (https://www.pivotaltracker.com/story/show/128393885) but we didn't prioritize it yet. Do you want Monorail to take a look at it?

**Comment by pscharla** [comment]
@leoyjchang We have it at the top of our backlog now so it should be addressed in the near term. I'll let you know if we end up being blocked on this one in any way. Thanks!
