### ISSUE TITLE
HEAD method needs to be added to 2.0 templates route

### ISSUE THREAD

**Issue by brianparry** [RackHD/RackHD#381]
@codenrhoden discovered this issue.

Centos install fails because `wget —spider`uses the HEAD method on the templates route which is not currently supported in the 2.0 API.
```
http: HEAD 405 19.695 - /api/current/templates/renasar-ansible.pub
```
```
Error: Path [/templates/{name}] defined in Swagger, but HEAD operation is not
```

**Comment by codenrhoden** [comment]
Thanks @brianparry 

And just for clarification, I found this when using `Graph.InstallCoreOS`, so CoreOS, not CentOS. I just brought up CentOS since it uses the same `wget` command, and so I think it would fail as well.

**Comment by amymullins** [comment]
Closing as PR (https://github.com/RackHD/on-http/pull/437) has been merged.
