### ISSUE TITLE
API 2.0: POST node workflow reports "Validation errors"

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#388]
## Description
When I tried to run the workflow `Graph.Reset.Node` against a node via API 2.0, it reported "Validation errors", but if I sent same command via API 1.1, the request succeeded.

I also tried other workflows, they have the same error pattern. When I tried to narrow down this problem, I found if I explicitly set the "content-type" the error will not happen again.

Below is the error using API 2.0:
```
$ http POST :8080/api/2.0/nodes/57ad3694edc56b041c69a6e5/workflows?name=Graph.Reset.Node
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 92
Content-Type: application/json; charset=utf-8
Date: Mon, 22 Aug 2016 06:42:13 GMT
ETag: W/"5c-GmsoeLFFE30tymddnoVyzA"
X-Powered-By: Express

{
    "UUID": "8e36c5c5-8b50-4408-a756-474b1e5099e7",
    "message": "Validation errors",
    "status": "400"
}
```

The error will be fixed after I explicitly set the content-type:
```
http POST :8080/api/2.0/nodes/57ad3694edc56b041c69a6e5/workflows?name=Graph.Reset.Node Content-Type:application/json
```

## Expected
1 - Actually, no payload for Graph.Reset.Node, so I expect to ignore the content-type check in this case.
2 - For other cases that payload is required, I would expect to improve the error message to make it be more clear for user.

**Comment by yyscamper** [comment]
@brianparry @srinia6 @keedya

**Comment by brianparry** [comment]
@yyscamper Strictly speaking, this is the advertised behavior (https://github.com/RackHD/on-http/blob/master/static/monorail-2.0.yaml#L15) and the validator is correctly rejecting this request..  

That said, the behavior is definitely a bit counter-intuitive.  I'm not sure there's much we can do about it though.  We can override the `consumes` property on a per-path basis, but I don't think there is a way to tell the validator to expect `application/json` if there is a body and ignore `Content-Type` otherwise.

**Comment by tldavies** [comment]
@yyscamper @brianparry - Is there anything that needs to be done here or are we leaving it at is since it is documented?

**Comment by heckj** [comment]
Is the take-away here that all our API's should expect a Content-Type: application/json header? Even if the 1.1 API's didn't - it's a bit stricter (for the positive and negative of that) and explicit - even if, as is the case with this, there's no payload required?

**Comment by zyoung51** [comment]
The swagger file is explicit about what it consumes so assumptions do not have to be made about what the API expects.  For what its worth, not all of the APIs consume application/json:
https://github.com/RackHD/on-http/blob/master/static/monorail-2.0.yaml#L457 (templates)
https://github.com/RackHD/on-http/blob/master/static/monorail-2.0.yaml#L695 (skupack)
https://github.com/RackHD/on-http/blob/master/static/monorail-2.0.yaml#L1263 (profiles)

**Comment by heckj** [comment]
@zyoung51 DOH, of course. Not thinking at all this morning apparently.

So it look like this is working exactly as specified in the YAML, and doing so correctly, but the error message when you don't do it per swagger spec is rather crappy. @brianparry is there anything within the swagger validation mechanisms that could be used to insert a more useful message - like "hey dude, use a content-type header here..." or the moral equiv?

**Comment by yyscamper** [comment]
@tldavies @brianparry @zyoung51 @heckj : 

As @brianparry said, this is counter-intuitive to report Content-Type error even the payload is empty. I know there may be some restriction in swagger config file, but that's not the excuse to not fix this issue. I think we can bypass the swagger config file and do some customized validation logic.

The error message is still better to be improved.

I also think we can report the issue or even provide some fix for swagger.

**Comment by brianparry** [comment]
@yyscamper Maybe we should just reject requests with an empty body.  If we do our own custom validation we're not really abiding by the constraints in  the OpenAPI spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md specification).  If we say a route consumes json, then it always consume json whether or not a body is present.

@heckj Agree that the swagger validator error message isn't very useful.  There was a PR opened up for this https://github.com/theganyo/swagger-node-runner/pull/36 but the maintainer opted not to merge it.  We could submit an alternate proposal or create our own variant of the validator fitting that provides useful information.

**Comment by brianparry** [comment]
@tldavies @brianparry @zyoung51 @heckj How about this:
```
{
  "message": "Validation errors",
  "status": "400",
  "UUID": "4424fd0e-5d70-468c-9270-6d8d5a8ccfde",
  "errors": [
    "Invalid Content-Type (text/plain).  These are supported: application/json"
  ]
}
```

**Comment by heckj** [comment]
That would work! Clearly states that isn't there and what's expected

**Comment by brianparry** [comment]
@BillyAbildgaard created a story in Pivotal Tracker: https://www.pivotaltracker.com/story/show/129534907

**Comment by pscharla** [comment]
@brianparry: @tldavies was actively working this in our current sprint here:
https://www.pivotaltracker.com/n/projects/1492888/stories/129374503
so we have a duplicate. Tracy has time now to work on the fix.

**Comment by brianparry** [comment]
@pscharla Okay - deleted the story from our backlog.

**Comment by yyscamper** [comment]
@brianparry : The error message is very clear. :+1:
