### ISSUE TITLE
an isc-dhcp-server v4.3.3 installation appeared to change the leases file path

### ISSUE THREAD

**Issue by benbp** [RackHD/RackHD#39]
We recently ran into an issue with an install of isc-dhcp-server v4.3.3 on Ubuntu that put the leases file into /var/db/dhcpd.leases, rather than the typical /var/lib/dhcp/dhcpd.leases. We hardcode to look in the former location on OSX platforms, and the latter on Linux platforms, but it's possible that with newer versions of isc we may be running into trouble.

**Comment by heckj** [comment]
I kind of think making the lease file lookup a configuration option with what we have hardcoded as a default is probably a good immediate solution.

**Comment by rolandpoulter** [comment]
Still need to document the new `monorail/config.json` property.

**Comment by rolandpoulter** [comment]
https://github.com/RackHD/docs/pull/290

**Comment by rolandpoulter** [comment]
@heckj I believe this issue is fixed now.
