### ISSUE TITLE
The houndci is down

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#391]
The houndci has been down for a long time. I tested in my own forked branch, the houndci still passed even I made some obvious syntax error. see https://github.com/yyscamper/on-tasks/pull/13

The checked the houndci official document (https://houndci.com/configuration#javascript), seems there is something change for houndci configuration.

**Comment by heckj** [comment]
Andrew - I just put up https://github.com/RackHD/on-core/pull/198 to fix this- headed in the right direction with what you’re seeing?

-joe

**Comment by heckj** [comment]
@yyscamper are you sure? Because I'm seeing it comment:

https://github.com/RackHD/on-http/pull/445/files/d5fd51bd0858f26b03a7e824528eed7f5d6dc3be#r76683978

**Comment by leoyjchang** [comment]
Story created in Maglev backlog to track this issue at https://www.pivotaltracker.com/story/show/129339463

**Comment by cgx027** [comment]
I had tried the same change as in https://github.com/RackHD/on-core/pull/198/files and it worked. 

Refer here for my experiment: https://github.com/RackHD/on-http/pull/447

I will submit PR for all the related repos.

**Comment by yyscamper** [comment]
Thanks for @cgx027 and @heckj 's effort on this issue. Now houndci resumes.
