### ISSUE TITLE
on-taskgraph Docker builds failing - ipmitool package missing

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#394]
The Alpine Linux package `ipmitool` has apparently gone missing for x86_64 packages, which in turn is causing a build failure for the on-taskgraph Dockerfile.

We first found the issue when researching the failed builds and related issue #393 

I reproduced the build locally with these results:

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
v3.4.3-8-g4e1813d [http://dl-cdn.alpinelinux.org/alpine/v3.4/main]
v3.4.2-11-g9b41a63 [http://dl-cdn.alpinelinux.org/alpine/v3.4/community]
v3.4.0-2846-gd96fd62 [http://nl.alpinelinux.org/alpine/edge/testing]
OK: 7400 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  ipmitool (missing):
    required by: world[ipmitool]
The command '/bin/sh -c mkdir -p ./node_modules   && ln -s /RackHD/on-core ./node_modules/on-core   && ln -s /RackHD/on-core/node_modules/di ./node_modules/di   && npm install --ignore-scripts --production   && echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories   && apk update   && apk add --update ipmitool net-snmp net-snmp-libs net-snmp-tools' returned a non-zero code: 1
```

Searching the AlpineLinux packages, the package still exists for `armhf`, but not for `x86_64`. It's findable in Google's search archives, but not in the active lists for Alpine packages at https://pkgs.alpinelinux.org/packages.

I opened a forum question at http://forum.alpinelinux.org/forum/general-discussion/ipmitool-package-disappeared-testing and will open a bug with Alpine linux about the disappearance.

**Comment by heckj** [comment]
FYI @rolandpoulter

**Comment by heckj** [comment]
issue http://bugs.alpinelinux.org/issues/6109 opened with Alpine linux (in addition to the forum post) to at least help identify the error

**Comment by heckj** [comment]
Some possible workarounds include building ipmitool ourselves and including it within a base image - maybe on-core - for our Docker series. That's been done at https://github.com/urzds/ipmitool-docker, which are docker files incorporating relevant fixes needed from upstream ipmitool, also captured in the bug there: https://sourceforge.net/p/ipmitool/bugs/426/

**Comment by zyoung51** [comment]
@heckj Problem also exists here: https://github.com/RackHD/on-imagebuilder/blob/master/micro-docker/Dockerfile

ERROR: unsatisfiable constraints:
  ipmitool (missing):
    required by: world[ipmitool]
  lshw (missing):
    required by: world[lshw]

**Comment by heckj** [comment]
@zyoung51 thanks - did lshw also previously exist and "disappear"?

**Comment by zyoung51** [comment]
@heckj Yes, @jlongever ran into that issue a while ago.

**Comment by heckj** [comment]
Any strong opinions on what we should, or shouldn’t, do here? Absent a reason otherwise, I think we should take the least effort path at the moment, which probably means doing the Alpine based workarounds rather than reconfiguring all the docker base images to anything else (OpenSuse, Debain, etc). Dissenting voices?

**Comment by jgolio** [comment]
At this point, I’m thinking that we should take the path of least resistance and continue with Alpine using the workarounds that we have identified. At least until we have better requirements driving us to use a different OS inside the Docker containers.  If right now, our main driver for wanting to use Alpine is it’s shear “tiny-ness” ☺ then I don’t think any of the other choices, like the ones below, will get close to the size of Alpine. That said, we do need to keep in mind Docker’s use of union filesystems, which helps reduce the resources required on the host to a minimum.

REPOSITORY            TAG                    IMAGE ID            CREATED             SIZE
centos                latest                 980e0e4c79ec        7 days ago          196.8 MB
debian                wheezy                 92e3b9f59655        2 weeks ago         84.93 MB
debian                latest                 031143c1c662        2 weeks ago         125.1 MB
ubuntu                latest                 bd3d4369aebc        2 weeks ago         126.6 MB
opensuse              latest                 642bc8a45961        8 weeks ago         97.78 MB


Joe

**Comment by pscharla** [comment]
@rolandpoulter Just created a pivotal tracker ticket for this work:
https://www.pivotaltracker.com/n/projects/1492888/stories/130452039

Let's put this as top priority of your work to get our docker builds back on track short term.

**Comment by rolandpoulter** [comment]
PR up to fix this problem. Decided to switch away from Alpine and over to a Debian base image.
https://github.com/RackHD/on-core/pull/210
https://github.com/RackHD/on-tasks/pull/336
https://github.com/RackHD/on-taskgraph/pull/171
https://github.com/RackHD/on-http/pull/466

**Comment by pscharla** [comment]
Thanks @rolandpoulter!!

As @jgolio said, not sure if there are any requirements around size (which is where alpine would help). Switching to debian base image seems to get us out of the model of having to be a package maintainer which is where we be for alpine.

**Comment by zyoung51** [comment]
Does this repo get the fix too? https://github.com/RackHD/on-imagebuilder/tree/master/micro-docker

**Comment by rolandpoulter** [comment]
@zyoung51 we should fix that one as well. I wasn't aware of it so I didn't fix it. However I think the `micro-docker` should absolutely continue to use Alpine linux and we should build `ipmitool` from source. Otherwise the it wouldn't really be a "micro" kernel.

**Comment by pscharla** [comment]
@rolandpoulter : Will close out this ticket since the bug was referencing on-taskgraph. Will create a new one for the repo above @zyoung51 is referencing.
