### ISSUE TITLE
setup_iso.py: add support for Ubuntu/SUSE/PhotonOS/Windows

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#401]
Some users prefer to use the setup_iso.py (https://github.com/RackHD/on-tools/blob/master/scripts/setup_iso.py) to create the OS repository, but it is out-of-date for a long time and it doesn't cover some new OS, such as Ubuntu, SUSE, PhotonOS, Windows.

**Comment by yyscamper** [comment]
Add @zyoung51 for awareness.

**Comment by leoyjchang** [comment]
Story created to track this ticket at https://www.pivotaltracker.com/story/show/115748605

**Comment by leoyjchang** [comment]
The story has been finished(see https://github.com/RackHD/on-tools/pull/33). Close this ticket.
