### ISSUE TITLE
where are the kernelFile and initrdFile in run-emc-diag.js?

### ISSUE THREAD

**Issue by lanchongyizu** [RackHD/RackHD#404]
```
kernelFile: vmlinuz-4.1.15-diag
initrdFile: ramfs.lzma
```
Where could we find these two files or how to generate them?
Thanks.

**Comment by heckj** [comment]
@jlongever I think you might be able to provide some guidance?

**Comment by jlongever** [comment]
@heckj @lanchongyizu Those are EMC internal diagnostic images.

**Comment by lanchongyizu** [comment]
@jlongever How could I get them for testing? Thanks.

**Comment by leoyjchang** [comment]
@lanchongyizu , you could reach out to @jlongever directly if want to use it for some business reason. I would suggest to close this ticket as question was answered - "Those are EMC internal diagnostic images". Are you Okay?

**Comment by lanchongyizu** [comment]
@leoyjchang OK, @jlongever has helped me through Email.
