### ISSUE TITLE
autounattend_windows_2012

### ISSUE THREAD

**Issue by lanchongyizu** [RackHD/RackHD#413]
What are the following files used for, and how to use them?
https://github.com/RackHD/on-http/blob/master/data/templates/autounattend_windows_2012_r2_SMC_6028U-TR4%2B.xml
https://github.com/RackHD/on-http/blob/master/data/templates/autounattend_windows_2012_r2_unknown.xml
https://github.com/RackHD/on-http/blob/master/data/templates/autounattend_windows_2012_r2_vmware.xml

Thanks.

**Comment by amymullins** [comment]
The autounattended files are legacy and no longer used.  This story is tracking their cleanup: 
https://www.pivotaltracker.com/story/show/130526881
