### ISSUE TITLE
The daily jenkins OS installer jobs are currently failing 

### ISSUE THREAD

**Issue by keedya** [RackHD/RackHD#414]

**Comment by keedya** [comment]
this jobs run every 24 hrs and run the tests in https://github.com/RackHD/RackHD/blob/master/test/tests/api/v1_1/os_install_tests.py

**Comment by keedya** [comment]
There was some modification to the payloads of certain OSes due to the introduction of tasks schema(required properties etc..) and other factors. these changes were updated in rackHD documentation at https://github.com/RackHD/RackHD/tree/master/example/samples

**Comment by heckj** [comment]
@keedya can you put in a link to the internal jenkins that hosts running these tests? Right now I can't personally reproduce them locally, so I couldn't even begin to vet them myself - but I recognize we want to keep them operational - just need a way to make sure they're good.

FYI @yyscamper I suspect there's some fallout from the updates you were making related to task schema that didn't get propagated to integration tests

**Comment by keedya** [comment]
here is the internal link to jenkins OS install jobs:
http://rackhdci.lss.emc.com/job/Continuous-Test/job/Continuous-OS-Install/

**Comment by yyscamper** [comment]
@keedya @heckj : I'll look at it.

**Comment by leoyjchang** [comment]
PT story has been created to track this issue at https://www.pivotaltracker.com/story/show/130614329

**Comment by leoyjchang** [comment]
I took a look at test result and console log provided by Andre (http://rackhdci.lss.emc.com/job/Continuous-Test/job/Continuous-OS-Install/).  All the OS installation test (ESXi, Windows 2K2, CentOS, OpenSUES, ...) were failed from 9/4 till now with same failure as below -- can't connect to vagrant VM. So we should get this issue fixed at first. @jlongever @panpan0000 @changev 
>> 
23:02:05 --2016-09-04 23:02:05--  http://localhost:9090/api/1.1/nodes
23:02:05 Resolving localhost (localhost)... ::1, 127.0.0.1
23:02:05 Connecting to localhost (localhost)|::1|:9090... failed: Connection refused.
23:02:05 Connecting to localhost (localhost)|127.0.0.1|:9090... connected.
23:02:05 HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
23:02:20 Giving up.

**Comment by amymullins** [comment]
FYI @leoyjchang , the vagrant issue should be resolved with this PR: https://github.com/RackHD/RackHD/pull/415

**Comment by keedya** [comment]
Continuous OS install job in Jenkins is now passing  and tests are stable now:
http://rackhdci.lss.emc.com/job/Continuous-Test/job/Continuous-OS-Install/
