### ISSUE TITLE
set bmc credential workflow fails to set BMC user

### ISSUE THREAD

**Issue by keedya** [RackHD/RackHD#417]
I think the failure is related to commit :
https://github.com/RackHD/on-core/commit/06638621b02727db77c57ad2493640b6b41806ab

below is part of the rendered script that shows the password rendered is encrypted:
script: https://github.com/RackHD/on-http/blob/master/data/templates/set_bmc_credentials.sh

`for x in $cmdReturn; do
   if [ roger == $x ]; then
   userNumber=${myarray[$(($i-1))]}
   echo "Username already present, overwriting existing user"
   ipmitool user set name $userNumber roger
   ipmitool user set password $userNumber P1Od9pfP5hHhLrJMhXiZVQ==.VbeQVU6svg/bX1X235xAzQ==
   ipmitool channel setaccess $channel $userNumber callin=on ipmi=on link=on privilege=4
   ipmitool user enable $userNumber
   check=$((check + 1))
  exit
  fi
  i=$((i+1))
done`

**Comment by DavidjohnBlodgett** [comment]
@keedya thanks for the extra info Andre! I'm looking into this now.

**Comment by DavidjohnBlodgett** [comment]
@keedya did you provide this workflow with a password in options? or invoke the auto creation of a unique password from here~ https://github.com/RackHD/on-tasks/blob/master/lib/jobs/generate-bmc-password.js#L41

**Comment by keedya** [comment]
I provided the password in the graph options
`{
    "name": "Graph.Bootstrap.With.BMC.Credentials.Setup",
    "options": {
         "defaults": {
             "graphOptions": {
                 "target": "57d81f417c03f648399cc1c8",
             "generate-pass": {
                 "user": "kizeb",
                 "password": "habilihabilihabili"
                }
                 
             },
             "nodeId": "57d81f417c03f648399cc1c8"
         }
     }
}`

**Comment by keedya** [comment]
Still failing with a different error:
 response:
3:12:52 PM graph.1  |    cmd:         sudo ./set_bmc_credentials.sh
3:12:52 PM graph.1  |    downloadUrl: http://172.31.128.1:9080/api/current/templates/set_bmc_credentials.sh?nodeId=583d98c0a47caa4e0852f7c9
3:12:52 PM graph.1  |    stdout:
3:12:52 PM graph.1  |    stderr:
3:12:52 PM graph.1  |      """
3:12:52 PM graph.1  |        sudo: ./set_bmc_credentials.sh: command not found
3:12:52 PM graph.1  |      """
3:12:52 PM graph.1  |    error:
3:12:52 PM graph.1  |      killed: false
3:12:52 PM graph.1  |      code:   1
3:12:52 PM graph.1  |      signal: null
3:12:52 PM graph.1  |      cmd:    /bin/sh -c sudo ./set_bmc_credentials.sh

**Comment by keedya** [comment]
I re-tested the bmc credentials workflow and it is passing now. Thanks everyone!!
