### ISSUE TITLE
annotation for dynamic task documentation not rendering any data

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#418]
found at Danielle Skinner (@dmskinner) per RackHD slack channel:

Pulled down the latest code in an OVA based distribution, and the task docs are empty:

![screen shot 2016-09-15 at 9 44 00 am](https://cloud.githubusercontent.com/assets/43388/18558887/bc066500-7b29-11e6-8d81-79e5af12f544.png)

The process I used to reproduce this:

`cd ~/src/rackhd/example`
`vagrant up && vagrant ssh`:

within the virtual machine:
```
cd ~src
./scripts/clean_all.bash && ./scripts/reset_submodules.bash && ./scripts/link_install_locally.bash
cd ~/src/on-http
./install-task-doc.sh
```

which reported success:
```
vagrant@rackhd-demo:~/src/on-http$ ./install-task-doc.sh
========= task_doc_data.json generated =======
vagrant@rackhd-demo:~/src/on-http$ echo $?
0
```

Digging in a bit further, it appears the underlying task data isn't getting collected and annotated:

```
vagrant@rackhd-demo:~/src/on-http$ cd ~/src/on-tasks/
vagrant@rackhd-demo:~/src/on-tasks$ node task-annotation-generator.js
========= task_doc_data.json generated =======
vagrant@rackhd-demo:~/src/on-tasks$ cat task_doc_data.json
[]
```

Digging into the code a bit, the logic is filtering on the existence of task.schemaRef (per https://github.com/RackHD/on-tasks/blob/master/task-annotation-generator.js#L28), which doesn't exist on these tasks any longer.

Just removing the filtering cascaded to an error, so it looks like the logic of this system needs to be updated to match the evolution of the task schema. The error when I removed the filtering from the promise chain: `TypeError: Parameter 'url' must be a string, not undefined`

**Comment by heckj** [comment]
FYI @yyscamper, @leoyjchang

**Comment by heckj** [comment]
I also put up a PR to fix the broken HTML link the in the header/footer there - found while I was hunting down this issue: https://github.com/RackHD/on-http/pull/465/files

**Comment by yyscamper** [comment]
@heckj : This is the PR to fix the problem: https://github.com/RackHD/on-tasks/pull/340
