### ISSUE TITLE
ESXI static IP setup on all ports fails now

### ISSUE THREAD

**Issue by keedya** [RackHD/RackHD#420]
ESXI static IP setup on all ports fails now after this commit:
https://github.com/RackHD/on-http/commit/bbfb7fd52fce29fcc5d2b0690997d56da6b60172

I suggest to revert the changesat : https://github.com/RackHD/on-http/commit/bbfb7fd52fce29fcc5d2b0690997d56da6b60172#diff-18c4b1cfd6087ff2dd6ec5b5d5fc57a0L35
 for ESXI by adding the postlookup back to the KS script.

**Comment by lanchongyizu** [comment]
@keedya We can move setting static IP to %post, and make `curl callback file`  work before the part of setting static IP. And we will create a story to solve the problem for all other OSes except Windows, which I think @uppalk1 will take it.
Thanks.

**Comment by panpan0000** [comment]
@keedya , @lanchongyizu's PR only on master, but NOT in the EMC internal release branch.
aka, in EMC internal release branch, ESXi static IP setup should be all set .
please confirm.

@lanchongyizu will work on the improvement later ( not urgent impact to EMC internal release.)
