### ISSUE TITLE
Get /templates/library with 'null' value in return value

### ISSUE THREAD

**Issue by cgx027** [RackHD/RackHD#430]
It's reported that one of the FIT test fail due to a 'null' value returned by rackHD when calling '''curl localhost:8080/api/1.1/templates/library'''. 

The log file:

```
curl localhost:8080/api/1.1/templates/library | python -m json.tool
[
...
...
    {
        "contents": "hostname rackhd-arista\n\nenable\nconfig\nusername rackhd secret 0 rackhd\n\nmanagement api http-commands\nno shut\n\nsnmp-server community rackhd\nsnmp-server group network-admin v2c\n\nend\n",
        "createdAt": "2016-09-28T15:00:21.190Z",
        "hash": "KzVhrsZJJ4XLDEArQbdtyg==",
        "id": "02aa7f98-b3ad-4073-aeed-984c522a8491",
        "name": "arista-startup-config",
        "path": "/home/vagrant/src/on-http/data/templates/arista-startup-config",
        "scope": "global",
        "updatedAt": "2016-09-28T15:00:21.190Z"
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
]
```

### The mongo db records looks fine
Initial checking confirms that's no null value in mongo templates collection. 

### The templates posted by skupack are returned as 'null' 
No template posted by skupack is show in the result, they are all turned into 'null' 

## The root cause
A code defect found on https://github.com/RackHD/on-http/blob/master/lib/api/1.1/northbound/templates.js#L38 that the scope should be passed along with 

Origin code look like:
```return templates.get(t.name);```

The fix:
```return templates.get(t.name, [t.scope]);```

**Comment by heckj** [comment]
@gpaulos FYI

**Comment by heckj** [comment]
@cgx027 will you be putting up a pull request with your suggested fix?

**Comment by cgx027** [comment]
Hi @heckj , @iceiilin and discussed on the solution and @iceiilin will help post a PR shortly.

**Comment by leoyjchang** [comment]
PT story was created to track efforts on this ticket. https://www.pivotaltracker.com/story/show/131343685
