### ISSUE TITLE
Add metadata to nodes and be able to retrive

### ISSUE THREAD

**Issue by kaleo211** [RackHD/RackHD#439]
Hi team,
We are using RackHD 2.0 now. We hit an issue that with endpoint `GET`:`/api/2.0/nodes/{id}`, we are not able to retrieve the metadata we patched through `PATCH`:`/api/2.0/nodes/{id}`. We talked to Joseph about this. He said we could create an issue here and here we are :). We wonder if you guys could do a patch to add following 3 attributes to the response of getting node?

Thank you so much!

The Id of VM provision on this node
```
vmId: string
```

The status of this node, like provisioned, reserved, available....
```
status: string
```

Information about disk
```
persistentDisk: {
    diskId: string,
    path: string,
    attached: bool
}
```

So that the response would look like:
```
  {
    "vmId": "j1l328jfdppfdfd883232l",
    "status": "reserved",
    "persistentDisk": {
      "diskId": "5665a65a0561790005b77b85-requestid",
      "path": "/dev/sdb",
      "attached": false
    },
    "workflows": "/api/2.0/nodes/55e79ea54e66816f6152fff9/workflows",
    "catalogs": "/api/2.0/nodes/55e79ea54e66816f6152fff9/catalogs",
    "autoDiscover": "false",
    "identifiers": [
      "00:1e:67:c2:67:06",
      "00:1e:67:c2:67:07"
    ],
    "name": "00:1e:67:c2:67:06,00:1e:67:c2:67:07",
    "obms": [
      {
        "service": "amt-obm-service",
        "ref": "/api/2.0/obms/55e79ea54e66816f6152fff9"
      }
    ],
    "sku": "55e79e0e4e66816f6152ffe6",
    "type": "compute",
    "id": "55e79ea54e66816f6152fff9"
  },
```

**Comment by zyoung51** [comment]
@RackHD/corecommitters For what its worth, the environment model is used by skupacks to store free-form data mapped to ids for all sku based information: https://github.com/RackHD/on-core/blob/master/lib/models/environment.js#L17.

**Comment by kaleo211** [comment]
@zyoung51 Thank you! But we're not very sure about how to use the environment model to store free-form data. We looked into SKU a little bit. It seems like it's trying to group the nodes using the rules defined in SKU base on the catalog information of nodes. We didn't find any endpoint to update the catalog or environment of an node. Will the SKU also group nodes base on the nodes' detail from `/api/2.0/nodes/{id}`?

**Comment by brianparry** [comment]
@kaleo211 Were you able to PATCH the `status` and `persistentDisk` properties?  That patch request should have failed with a schema validation error.

**Comment by kaleo211** [comment]
@brianparry we tried, and succeeded. lol

**Comment by kaleo211** [comment]
@zyoung51 that's very helpful to us. We thought we need to create a tag first in order to use it. But the way you showed to us is way more easier. It seem like it only support for simple metadata. If we want to put a little complicate one like persistentDisk, it might not be easy as others. If you guys plan to add `/api/2.0/environment/{id}`, that would be awesome! we'll definitely wait for that.
