### ISSUE TITLE
Improve API validation error message

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#445]
## Problem
For both API 2.0 & Redfish API, the error message doesn't provide clear clue to help user to identify the problem, especially when the payload is huge.

For example: 
1 - I set a wrong password (it should be string, but I set it as number) while putting an obm setting:

```
http PUT :8080/api/2.0/obms < ~/data/obm.json

The content for obm.json:
{
    "service": "ipmi-obm-service",
    "config": {
        "user": "admin",
        "password": 1,
        "host": "172.31.128.99"
    }
}
```

The error message is as below, it doesn't tell user it is `password` can cause the problem:
```
{
    "UUID": "2f29e70c-8d8c-47bc-8b3e-78721a33ed5b",
    "message": "Validation errors",
    "status": "400"
}
```

2 - The Redfish Boot Image API
You could get some detail from [ODR-905](https://hwjiraprd01.corp.emc.com/browse/ODR-905), I copied some error message below:

 * Set version to invalid (it should be string, but I set it as number):
```
{
  "message": "Validation errors",
  "status": "400",
  "UUID": "92425948-0651-459b-bfdf-3d51cac3aac8"
}
```

* Add some additional properties
```
{
    "MessageId": "RackHD.1.0.DetailedErrorMessage",
    "Message": "ValidationError: Additional properties not allowed",
    "Description": "Contains the detailed error message contents"
}
```

Since the BootImage payload is very large, if the error message doesn't tell user which option is not correct, then user will feel trouble.

## Expectation：
In contrast, when I designed the task-schema, it can output much more clear error message, below is some example:
```
"message": "Task.Os.Install.CentOS: JSON schema validation failed - data should have required property 'version'"
```

```
"message": "Task.Os.Install.CentOS: JSON schema validation failed - data.users[0].uid should be >= 500"
```

```
"message": "Task.Os.Install.CentOS: JSON schema validation failed - data.rootPassword should be string"
```

So if the API validation can provide similar error message, it will make API be more user-friendly and help user's self-debugging.

**Comment by pscharla** [comment]
@yyscamper : Curious if this is different from issue 388 you filed:
https://github.com/RackHD/RackHD/issues/388

**Comment by benbp** [comment]
Should be resolved with https://github.com/RackHD/on-http/pull/511
