### ISSUE TITLE
Compute nodes not running microkernel and not getting discovered after bootup

### ISSUE THREAD

**Issue by gpaulos** [RackHD/RackHD#453]
Starting on Oct 14, we started getting node discovery errors on our daily RackHD FIT test here in MN test lab. 

It looks like the microkernel is not getting executed when the compute node first boot up. This is happening on all of our compute nodes. Subsequent reboots do not correct the problem. No indication in logs about the problem. Very little in the logs at all.

Using same installation, configuration, and initialization routines as before. 

Here is the configuration file:
{
    "$0": "/usr/bin/nodejs index.js",
    "CIDRNet": "172.31.128.0/22",
    "LANG": "en_US.UTF-8",
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "PWD": "/var/renasar/on-http",
    "SHLVL": "0",
    "_": [],
    "amqp": "amqp://localhost",
    "apiServerAddress": "172.31.128.1",
    "apiServerPort": 9080,
    "arpCacheEnabled": true,
    "authPasswordHash": "KcBN9YobNV0wdux8h0fKNqi4uoKCgGl/j8c6YGlG7iA0PB3P9ojbmANGhDlcSBE0iOTIsYsGbtSsbqP4wvsVcw==",
    "authPasswordSalt": "zlxkgxjvcFwm0M8sWaGojh25qNYO8tuNWUMN4xKPH93PidwkCAvaX2JItLA3p7BSCWIzkw4GwWuezoMvKf3UXg==",
    "authTokenExpireIn": 86400,
    "authTokenSecret": "RackHDRocks!",
    "authUsername": "admin",
    "baseDirectory": "/var/renasar/on-http/node_modules/on-core",
    "broadcastaddr": "172.31.131.255",
    "dhcpGateway": "172.31.128.1",
    "dhcpProxyBindAddress": "172.31.128.1",
    "dhcpProxyBindPort": 4011,
    "dhcpSubnetMask": "255.255.252.0",
    "gatewayaddr": "172.31.128.1",
    "httpDocsRoot": "./build/apidoc",
    "httpEndpoints": [
        {
            "address": "0.0.0.0",
            "authEnabled": false,
            "httpsEnabled": false,
            "port": 8080,
            "proxiesEnabled": true,
            "routers": "northbound-api-router"
        },
        {
            "address": "0.0.0.0",
            "authEnabled": true,
            "httpsEnabled": true,
            "port": 443,
            "proxiesEnabled": true,
            "routers": "northbound-api-router"
        },
        {
            "address": "172.31.128.1",
            "authEnabled": false,
            "httpsEnabled": false,
            "port": 9080,
            "proxiesEnabled": true,
            "routers": "southbound-api-router"
        }
    ],
    "httpFileServiceRoot": "./static/files",
    "httpFileServiceType": "FileSystem",
    "httpProxies": [
        {
            "localPath": "/mirror",
            "remotePath": "/",
            "server": "http://mirrors.hwimo.lab.emc.com/mirrors"
        }
    ],
    "httpStaticRoot": "/opt/monorail/static/http",
    "minLogLevel": 3,
    "mongo": "mongodb://localhost/pxe",
    "sharedKey": "qxfO2D3tIJsZACu7UA6Fbw0avowo8r79ALzn+WeuC8M=",
    "statsd": "127.0.0.1:8125",
    "subnetmask": "255.255.252.0",
    "syslogBindAddress": "172.31.128.1",
    "syslogBindPort": 514,
    "tftpBindAddress": "172.31.128.1",
    "tftpBindPort": 69,
    "tftpRoot": "./static/tftp"
}

This is a blocker for us.

Possibly related to Issue #448 ??

**Comment by johren** [comment]
What I am seeing is that the microkernel is running but it just sits there waiting.  I do not see any of the Task.Catalog.* tasks start running in the on-taskgraph.log.  Still digging.

**Comment by gpaulos** [comment]
Fixed when the build process was repaired.
