### ISSUE TITLE
No new bintray packages since October 4th

### ISSUE THREAD

**Issue by ytjohn** [RackHD/RackHD#457]
No new packages have made it into bintray since October 4th. 

This was discovered (and impacts) https://github.com/RackHD/on-imagebuilder/issues/63

**Comment by panpan0000** [comment]
Hi, @ytjohn .  it's an accident renaming of the bintray repo "packages" into "package",
so TravisCI will complain "Bintray response: 404 Not Found. Package 'packages' was not found"
I just fixed it "https://bintray.com/rackhd/debian/packages" and rebuild last ones in each repo.

**Comment by panpan0000** [comment]
TravisCI doesn't complain Bintray upload failure. I find it might in a Bintray & TravisCI problem (no stop after failure). but I can't find TravisCI github issue id now....

**Comment by panpan0000** [comment]
https://bintray.com/rackhd/debian/packages#files/dists/trusty/main/binary-amd64
```
|----   on-dhcp-proxy_1.1-1master-20161011120548Z1_amd64.deb
|----   on-http_1.1-1master-20161020003223Z1_amd64.deb
|----   python-on-http-api1.1_1.1-1master-20161020003223Z1_amd64.deb
|----   python-on-http-api2.0_1.1-1master-20161020003223Z1_amd64.deb	
|----   python-on-http-redfish-1.0_1.1-1master-20161020003223Z1_amd64.deb	
|----   on-taskgraph_1.1-1master-20161014110629Z1_amd64.deb

```
