### ISSUE TITLE
GET on lookups doesn't return all records

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#47]
I just noticed if I do a query for a specific lookup record by mac (/api/current/lookups?q=<mac>), I get the record, but when I do a query for all lookups (/api/current/lookups), the same record doesn’t show up in that list.

```
$ curl localhost:8080/api/common/lookups?q=00:1c:73:66:ad:2a | python -mjson.tool 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0  27525      0 --:--:-- --:--:-- --:--:-- 30833
[
    {
        "createdAt": "2015-12-15T20:32:18.989Z",
        "id": "567078d29cccb24615688a7f",
        "ipAddress": "172.31.131.200",
        "macAddress": "00:1c:73:66:ad:2a",
        "node": "",
        "updatedAt": "2015-12-17T14:32:09.909Z"
    }
]

$ curl localhost:8080/api/common/lookups | python -mjson.tool | grep 567078d29cccb24615688a7f
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3735  100  3735    0     0   164k      0 --:--:-- --:--:-- --:--:--  158k
```

**Comment by heckj** [comment]
Thanks @johren 

Relevant code is at https://github.com/RackHD/on-http/blob/master/lib/api/lookups.js#L30 - looks like `waterline.lookups.findByTerm(req.query.q)` when the query is empty doesn't return a complete list.

**Comment by yyscamper** [comment]
Should get the cause.
From the implementation of findByTerm (https://github.com/RackHD/on-core/blob/master/lib/models/lookup.js#L36-L44): 
```javascript
findByTerm: function (term) {
            return this.find({
                or: [
                    { node: term },
                    { macAddress: term },
                    { ipAddress: term }
                ]
            });
        }
```
if *term* is empty, findByTerm only returns entries that either "node", "macAddress" or "ipAddress" is empty.

For @johren 's case, The fields node/macAddress/ipAddress are all exist, so it is excluded from the list. 

The solution should be adding a special query in findByTerm if *term* is empty.

**Comment by yyscamper** [comment]
PR for this issue: https://github.com/RackHD/on-core/pull/52
