### ISSUE TITLE
Unable to Catalog Cisco Nexus switch with POAP

### ISSUE THREAD

**Issue by arajapa** [RackHD/RackHD#488]
Hi,

I am trying to catalog a Cisco N9K-C9396PX in POAP mode however when RACKHD tries to run the  cisco-catalog-version.py script it fails with the following error.  I was working with the RackHD team and they had requested we open a bug.  Here is the errors i see.

Thanks in advance,
Alan
[RackHD Cisco POAP errors.txt](https://github.com/RackHD/RackHD/files/583791/RackHD.Cisco.POAP.errors.txt)

**Comment by leoyjchang** [comment]
Add @RackHD/corecommitters @amymullins @pscharla for attention

**Comment by brianparry** [comment]
@arajapa This looks like it could be a problem with either the templates metadata stored in Mongo or mismatched data models between on-core and on-http.  What version of on-http are you running?  Also, could you provide a dump of your templates collection using these commands:
```
rackhd@RackHdDev:~$ mongo
MongoDB shell version: 2.4.9
connecting to: test
> use pxe
switched to db pxe
> db.templates.findOne()
```

**Comment by king-jam** [comment]
👍 
Hitting a similar issue. May or may not be related.
We are getting to the download of the cisco-catalog-version.py and then the switch is hanging. We are getting intermittent success. The first time a switch is seen...it works successfully, anytime afterwards we will typically fail. Appears to be a race condition/timing issue of some kind.

We have been debugging for multiple days without success.

**Comment by arajapa** [comment]
Hey James, I believe Jean Pierre figured out what the issue was.  Let me check with him.

**Comment by king-jam** [comment]
I talked to JP and he thinks this is a different but similar issue. @brianparry @leoyjchang @keedya Should I open a separate issue?

**Comment by nucklehead** [comment]
@brianparry @keedya. This was mainly related to upgrade issues b ut this is no longer a problem

However we encountered an issue with the md5 of [cisco-poap.py](https://github.com/RackHD/on-tftp/blob/master/data/templates/cisco-poap.py) wich may require minor updates.

Since it is a template, the md5 hash will change every-time it renders. We had to hard code the RackHD ip in it. This might need a different issue for tracking.

``` 
cd ~/src/on-tftp/data/templates/
echo "Updating md5sum cisco-poap.py file..."
sed -i -- "s/\(# f=cisco-poap.py.*\)/\1\n#md5sum=/g" cisco-poap.py
sed -i -- "s/API_SERVER_ADDRESS =.*/API_SERVER_ADDRESS = '172.31.128.1'/g" cisco-poap.py
sed -i -- "s/API_SERVER_PORT =.*/API_SERVER_PORT = '9080'/g" cisco-poap.py
```

**Comment by amymullins** [comment]
@nucklehead , I'd like to close this out since you helped confirm this is no longer an issue.  I'll open up a new issue for the md5 of cisco-poap.py.
