### ISSUE TITLE
downloadUrl in Task.Base.Linux.Commands entries requires a relative URL

### ISSUE THREAD

**Issue by jeamland** [RackHD/RackHD#489]
This requirement is not spelled out anywhere and means that any use of things like `{{ api.templates }}` in one of these causes it to fail in a way that's highly non-obvious, being that the file you end up with contains:

```
Cannot GET <the absolute URL you specified>
```

On top of that, the on-http logs contain 404 errors with correct-looking URLs.

As a kicker, the entry is named `downloadUrl` where it probably should be `downloadUri` for consistency with everything else.

**Comment by leoyjchang** [comment]
Take an example below, are you suggesting to rename "downloadUrl" to "downloadUri" ? Add @RackHD/corecommitters for attention.
 
module.exports = {
    "friendlyName": "Arista Switch ZTP Discovery",
    "injectableName": "Graph.Switch.Discovery.Arista.Ztp",
    "tasks": [
        {
            "label": "catalog-switch",
            "taskDefinition": {
                "friendlyName": "Catalog Arista Switch",
                "injectableName": "Task.Inline.Catalog.Switch.Arista",
                "implementsTask": "Task.Base.Linux.Commands",
                "options": {
		    "commands": [
                        {
                            "downloadUrl": "/api/1.1/templates/arista-catalog-version.py",
                            "catalog": { "format": "json", "source": "version" }
                        }
                    ]
                },
                "properties": {}
            }
        }
    ]
};

**Comment by brianparry** [comment]
@jeamland It looks like this is documented in the schema for the linux command task here: https://github.com/RackHD/on-tasks/blob/4cfd6a6efe141a83c27095a5eb6cadd7e5602c47/lib/task-data/schemas/linux-command.json#L44.  @leoyjchang Are we publishing task documentation anywhere yet.  The property name is definitely incorrect and misleading.  It should definitely be changed to downloadUri.  Do you have on-http logs available with the 404 errors you mentioned?

**Comment by leoyjchang** [comment]
@brianparry No, current task document will only be generated by user in local environment. But we do have plan to provide an online/live version which is integrated with readthedoc and keep synced with RackHD latest repos. If the renaming does make sense, I will create a story in Maglev backlog. For 404 errors, @jeamland , do you happen to have on-http logs available?

**Comment by yyscamper** [comment]
@lanchongyizu is working on two PRs, that need to change the downloadUrl to fullpath (not relative path), so we can keep the name.
- https://github.com/RackHD/on-skupack/pull/57
- https://github.com/RackHD/on-taskgraph/pull/187
