### ISSUE TITLE
Disabling default pollers should be far easier than it is

### ISSUE THREAD

**Issue by jeamland** [RackHD/RackHD#490]
We have some older BMCs that tend to get a bit freaked out if they're hit too often. I've seen them resetting themselves under the load from the default IPMI pollers that get created.

The advice I received was either don't create an OBM entry, which doesn't work since I actually want to use IPMI to manage these hosts, or to delete the create-default-pollers section from the Discovery SKU graph.

So I tried writing a script that'd fetch the Discovery SKU graph, remove the create-default-pollers task and then PUT it back. This didn't work because graphs are reformatted to give task names as URLs and are thus rejected. I tried rewriting them back but then it failed due to nodeId being null.

So I tried getting the Discovery SKU graph out of the Javascript (not JSON) file that it's in, converting it to JSON, removing the create-default-pollers task then PUTing it back. This failed due to nodeId being null.

I feel that this should be far more easy to disable than it is. At the very least, any graph that I fetch out of the system should be capable of being put back into the system without modification.

**Comment by leoyjchang** [comment]
It looks a valid use request to me. Add @RackHD/corecommitters to see any technical solution for it.

**Comment by leoyjchang** [comment]
Story created in Maglev backlog at https://www.pivotaltracker.com/story/show/134759575.

**Comment by brianparry** [comment]
@jeamland @leoyjchang I'd suggest we modify the API so that the schemas accept post/patch/put data as rendered by the view.  In this case, either names or URIs.

**Comment by anhou** [comment]
@jeamland  RackHD has a default variable in graph `serviceGraph`  https://github.com/RackHD/on-taskgraph/blob/master/lib/graphs/poller-service-graph.js#L8   which could disable default running graphs. when RackHD on-taskgraph service startup, if it's false, the graph which all kinds of pollers wouldn't start. I think that's what you want. if it's not, let me know. just notice that if set `serviceGraph` to false, on-taskgraph needs to restart to take effect.

**Comment by yyscamper** [comment]
@anhou @jeamland : do you think whether need additional work for this issue, if not, I think we can close this issue.

**Comment by leoyjchang** [comment]
Close this issue based on what @anhou has been done.
