### ISSUE TITLE
Vagrantfile in example directory fails to map repos in specific cases

### ISSUE THREAD

**Issue by jeamland** [RackHD/RackHD#499]
In the Vagrantfile located in the example directory there is special handling when the `WORKSPACE` and `REPO` variables are set.

In the general case the intent appears to be to map the repo specified in `REPO` through to the Vagrant VM. If `REPO` is `on-tasks` or `on-core` then care is taken to map those into the node_modules directory of the various projects that rely on them... and then they are never mapped into the top-level workspace.

Patch to fix this attached.
[workspace-repo-fix.txt](https://github.com/RackHD/RackHD/files/596264/workspace-repo-fix.txt)

**Comment by leoyjchang** [comment]
The current vm sync configuration won't impact RackHD running as on-task/on-core are libraries. But it is still good to map them into top-level workspace. Do you like to submit a formal PR for this? :-)
