### ISSUE TITLE
create OpenSUSE installer tasks and workflow

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#51]
We had it working at one time, now distant, but a reference template for YAST and a profile for invoking an OpenSUSE installer still exist, as well as notes on making an OpenSUSE repository package mirror for remote/network installation. Making an equivalent basic OS Install for OpenSUSE should be primarily creating an OS.Install task for the OS, and an associated graph

**Comment by heckj** [comment]
Work effort assigned  https://github.com/RackHD/RackHD/wiki/proposal-sles-os-install

**Comment by anhou** [comment]
the PR https://github.com/RackHD/on-http/pull/174 has been submitted and merged, so close this enhancement issue
