### ISSUE TITLE
[ORFS-97]RackHD should return error when the user input invalid "installDisk" value

### ISSUE THREAD

**Issue by sunnyqianzhang** [RackHD/RackHD#53]
Installed the OS with invalid value of "installDisk" in the json payload, the on-taskgraph should return an error to warn the user.

**Comment by heckj** [comment]
Hi @sunnyqianzhang 

Can the system know if the value of installDisk is invalid up front, or is this something that fails at runtime (while the workflow is operating)? If the later, the workflow does presumably fail - is that correct? 

If the workflow fails, what error does it include today related to this failure case, and what error are you suggesting it should provide?

**Comment by sunnyqianzhang** [comment]
@heckj Sorry for causing confusion. This is something that fails at runtime, that is when the workflow is running. In this case the workflow should fail instead of continuing. The front could do some check to ensure the value given is correct, but I'd request the RackHD do some check.

The ideal error in my mind is- RackHD gives a warning like  "the value you entered for  parameter 'installDisk'  is invalid"

**Comment by heckj** [comment]
Thanks @sunnyqianzhang - marking this issue with "enhancement" as well, as I think this should be a relatively small, constrained change to put in a better error message and have the task fail as you suggest instead of continuing on without issue
