### ISSUE TITLE
microkernel build process doesn't include req HW drivers when made in VMs

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#57]
The microkernels created using cloud resources (in a VM, or through TravisCI) don't include all the underlying drivers for the kernel such that booting some physical machines fails - the discovery kernel hangs at boot up.

Steve Mendes ran into this with Cisco UCS gear (interactive chat on Slack), and we're investigating if https://github.com/RackHD/RackHD/issues/52 with @gary15 is this same issue.

The older microkernels at https://www.dropbox.com/s/ph372nd29fw320s/old_microkernel.zip?dl=0 resolved the issue for Steve with the Cisco UCS gear.

**Comment by heckj** [comment]
@gary15 also ran into this issue with #52, which was closed as a duplicate of this core issue

**Comment by heckj** [comment]
@benbp we've had a couple of folks hit their heads on this again, so we need to figure out what we're missing in our initrd creation process - we're definitely missing something, but still don't quite know which.

**Comment by benbp** [comment]
@heckj Inspecting a filesystem diff between an initramfs built by a physical machine vs. a virtual one: the initramfs built on virtual literally does not include the `lib/modules/<kernel_ver>/kernel` directory, so there are no kernel drivers included at all... (FYI @jlongever)

**Comment by benbp** [comment]
This bug seems relevant: https://lists.debian.org/debian-kernel/2015/03/msg00283.html. I'm not sure if this is the same problem, but it appears that initramfs-tools was having trouble in this user's case with compressed kernel modules because of the `.gz` appended to the filename (https://lists.debian.org/debian-kernel/2015/03/msg00332.html). Going to investigate whether this is the reason.

**Comment by jlongever** [comment]
Not sure why that would be different between a VM vs. physical system unless Ubuntu is changing that kernel compress option when installed on a VM platform?  I'd prefer to control the kernel build myself and install directly to the initrd.  Maybe we should try that in on-imagebuilder?

**Comment by jlongever** [comment]
Actually,  easy enough check the config option CONFIG_MODULE_COMPRESS after installing the kernel on a VM?

**Comment by benbp** [comment]
Looking a little more I don't think the compress option is relevant to us. I think the suggestion to control the kernel build ourselves is good, though I'd still like to know the root cause here, especially if it turns out to be a trivial one.ˆ

**Comment by benbp** [comment]
Actually, I lied...

I just looked at the latest initrd build from travis and it DOES have the kernel modules. I must have been inspecting a bad image *runs and hides*

**Comment by jlongever** [comment]
Doh!

**Comment by jlongever** [comment]
I still prefer to avoid the walled garden approach when I build kernel images.

**Comment by benbp** [comment]
So yeah, did more analysis of physical vs. virtual, doesn't seem to make a difference, identical filesystem diff.

Analyzed the old image again, it's pretty obvious now that we're just missing hardware drivers. We *do* install the kernel into the initrd build chroot, but it seems like there's a lot more missing that was on our original build server installation that isn't loaded into the build chroot or reflected in the old build scripts. The `modules.alias` file on the working initrd is over 3000 lines whereas the one from on-imagebuilder is only around 800. Luckily, we still have the old build server, so I'm just going to try being really greedy with installing kernel drivers into the initrd based on the diff and see what happens.

**Comment by benbp** [comment]
General diff between what gets installed from the debootstrap chroot build environment vs. the old working build server:

https://gist.github.com/benbp/0971990632b28db30934

**Comment by heckj** [comment]
Is there a configuration option or something we're missing where we specify `ALL THE DRIVERS` when building this? It's getting something implicitly from the environment in which it's built, but for the life of me I don't know what or where

**Comment by benbp** [comment]
That's my next step. Going to look at ironic and razor for clues as you suggested.
