### ISSUE TITLE
some finding in set_bmc_credentials.sh

### ISSUE THREAD

**Issue by wangzhizheng** [RackHD/RackHD#593]
1, when creating a new user, we need to check if exists users have reach the MAX user Count 
userNumber=$((userNumber + 1))

2, 
myarray1=(${cmdReturn1//$'\n'/ })
userNumber=${myarray1[8]}

userNumber should not be the max "Enabled User"
If there are some "Disable Users" exists, userNumber will not be the correct number.
and it will be an error when create a new user.

**Comment by johren** [comment]
Opened https://rackhd.atlassian.net/browse/RAC-4122

**Comment by wangzhizheng** [comment]
submited a PR for this one
https://github.com/RackHD/on-http/pull/587
