### ISSUE TITLE
BMC credentials are not being set on discovered nodes

### ISSUE THREAD

**Issue by tgelter** [RackHD/RackHD#602]
After discovering a node (with **autoCreateObm** set to **true**), there is no BMC user \_\_rackhd\_\_ being created, and subsequently, the OBM settings are not getting set for the node.
Here's the example "user list" output from a discovered node:
`ipmitool -I lanplus -H $i -U admin -P redacted user list; done
ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
1                    false   false      true       USER
3   Admin            true    true       true       ADMINISTRATOR
5   admin            true    true       true       ADMINISTRATOR`

@keedya asked me to open this ticket after we spent some time looking into the issue.
If any logs, configuration, or any other details are needed, please let me know.

**Comment by keedya** [comment]
@tgelter  can you include the servers u are using in your setup?

**Comment by keedya** [comment]
@uppalk1 @tannoa2 any idea why set bmc credentials is failing to create the default __rackhd__ user ?

**Comment by tgelter** [comment]
@keedya server models in question:
- ZTSYSTEMS (custom build)
- Quanta D51B-1U (dual 1G LoM)
- Dell R630

**Comment by amymullins** [comment]
Resolution to this issue is being tracked in JIRA: https://rackhd.atlassian.net/browse/RAC-4088

**Comment by amymullins** [comment]
PR posted by @keedya : https://github.com/RackHD/on-taskgraph/pull/210

**Comment by amymullins** [comment]
PRs have been merged.
