### ISSUE TITLE
 "virtualDisk" field is missing in driveId catalogue on Platform-P

### ISSUE THREAD

**Issue by sunnyqianzhang** [RackHD/RackHD#63]
If no raid is configured, the "virtualDisk" field should be "". However, on Platform-P, the field is missing for non-sata-DOM drive.

**Comment by sunnyqianzhang** [comment]
onrack@ora:~$ curl http://localhost:8080/api/common/nodes/568ac59f94e11f0106e15c                                                                                                                               2e/catalogs/driveId | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   955  100   955    0     0  76898      0 --:--:-- --:--:-- --:--:-- 79583
{
    "createdAt": "2016-01-04T19:20:38.605Z",
    "data": [
        {
            "devName": "sda",
            "esxiWwid": "t10.ATA_____SATADOM2DSL_3SE__________________________20                                                                                                                               141004AAAA94514589",
            "identifier": 0,
            "linuxWwid": "/dev/disk/by-id/ata-SATADOM-SL_3SE_20141004AAAA9451458                                                                                                                               9",
            "scsiId": "2:0:0:0",
            "virtualDisk": ""
        },
        {
            "devName": "sdc",
            "esxiWwid": "naa.5000cca01d8d5e68",
            "identifier": 1,
            "linuxWwid": "/dev/disk/by-id/scsi-35000cca01d8d5e68",
            "scsiId": "7:0:1:0"
        },
        {
            "devName": "sde",
            "esxiWwid": "naa.5000cca01d8ec0e4",
            "identifier": 2,
            "linuxWwid": "/dev/disk/by-id/scsi-35000cca01d8ec0e4",
            "scsiId": "7:0:3:0"
        },
        {
            "devName": "sdd",
            "esxiWwid": "naa.5000cca01d8f0ae4",
            "identifier": 3,
            "linuxWwid": "/dev/disk/by-id/scsi-35000cca01d8f0ae4",
            "scsiId": "7:0:2:0"
        },
        {
            "devName": "sdb",
            "esxiWwid": "naa.5000cca02b2b64e0",
            "identifier": 4,
            "linuxWwid": "/dev/disk/by-id/scsi-35000cca02b2b64e0",
            "scsiId": "7:0:0:0"
        }
    ],
    "id": "568ac606c1f800fd05dcb526",
    "node": "568ac59f94e11f0106e15c2e",
    "source": "driveId",
    "updatedAt": "2016-01-04T19:20:38.605Z"
}

**Comment by yyscamper** [comment]
I prefer to remove the "virtualDisk" field if it is not a RAID.

**Comment by heckj** [comment]
@sunnyqianzhang we intentionally leave the catalogs free-form - there's no defined schema for them. I agree with @yyscamper that if there's no related virtualDisk disk file, then missing that key should be quite acceptable
