### ISSUE TITLE
set_bmc_credentials.sh doesn't create valid user account on HP CloudLine server

### ISSUE THREAD

**Issue by tgelter** [RackHD/RackHD#631]
When our sample HP CL2100 server is discovered, RackHD correctly tries to set up a **__rackhd__** IPMI user account, with an auto-generated password (in this case: **7ac28c84**).
However, the password doesn't meet the minimum password policy requirements set in the MergePoint EMS Embedded Management Software, which HP has selected to implement (manage?) their BMC for this server.
I'm not sure how to submit logs, however I did test setting the password manually after grabbing it from the on-http error log (shown below), and the WebUI threw the error when I tried to change it to that password.
`            "acd7ecfa-ad9f-484a-bd1d-938cdb24e0be": {
                "error": "Error: Command failed: /usr/bin/ipmitool -I lanplus -U __rackhd__ -P 7ac28c84 -H 10.<omitted> chassis bootdev pxe\nError: Unable to establish IPMI v2 / RMCP+ session\r\nError setting Chassis Boot Parameter 0\r\nError setting Chassis Boot Parameter 4\r\n\n    at ChildProcess.exithandler (child_process.js:213:12)\n    at emitTwo (events.js:92:20)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:827:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)",
                "friendlyName": "Set Node Pxeboot",
                "ignoreFailure": true,
                "implementsTask": "Task.Base.Obm.Node",
                "injectableName": "Task.Obm.Node.PxeBoot",
                "instanceId": "acd7ecfa-ad9f-484a-bd1d-938cdb24e0be",`
Below you'll see that the user was created:
`$ ipmitool -I lanplus -U ADMIN -P ADMIN -H 10.<omitted> user list 1
ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
2   ADMIN            true    true       true       ADMINISTRATOR
3   __rackhd__       true    true       true       ADMINISTRATOR`
And here's an example of me trying to set the user password to the one generated by RackHD:
`$ ipmitool -I lanplus -U ADMIN -P ADMIN -H 10.<omitted> user set password 3 7ac28c84
Set User Password command failed (user 3): Unknown (0x8F)`
Once I deselect **Password Policy Check Enable**, it works:
`$ ipmitool -I lanplus -U ADMIN -P ADMIN -H 10.<omitted> user set password 3 7ac28c84
$ ipmitool -I lanplus -U __rackhd__ -P 7ac28c84 -H 10.<omitted> chassis power status
Chassis Power is on`
I've so far been unable to find any information regarding the password requirements for MergePoint EMS Embedded Management Software.
Please let me know if there is any other detail I can provide.
Thanks!

**Comment by pscharla** [comment]
@tgelter: Closing this issue and replacing it with this jira issue:
https://rackhd.atlassian.net/browse/RAC-4722
