### ISSUE TITLE
In docker-compose build: use newly build rackhd/files image instead of download directly is not user friendly

### ISSUE THREAD

**Issue by keedya** [RackHD/RackHD#636]
use newly build rackhd/files image instead of download directly  made building the images locally mandatory and not so user friendly

**Comment by keedya** [comment]
@changev

**Comment by changev** [comment]
Can you please explain more about "user friendly".
Do you mean this take disadvantage to user locally build?

**Comment by amymullins** [comment]
Moving issue to Jira: https://rackhd.atlassian.net/browse/RAC-4356
