### ISSUE TITLE
Task ID 404's during Node Workflow

### ISSUE THREAD

**Issue by GaryPWhite** [RackHD/RackHD#693]
Hey all,

We're having an issue where we are running a workflow against a node to verify that we're using the right endpoints to publish and run a workflow. The intended flow for our testing purposes are:

`PUT /api/2.0/workflows/graphs` with workflow injectable name and workflow body.
`POST /api/2.0/nodes/{id}/workflows` with nodeID, and workflow request body.

the workflow is recognized in the RackHD API, and we can see from the output of `on-tftp` that there's an issue finding the `taskID` for a given task in our workflow.

An example of the output we see for a workflow:
```
0|on-taskg | [error] [2017-03-30T15:07:14.488Z] [on-taskgraph] [Task.Task] [Server] Task failed
0|on-taskg |  -> /node_modules/on-tasks/lib/task.js:346
0|on-taskg | error:          NotFoundError: Lookup Record Not Found (findOneByTerm)
0|on-taskg | taskId:         58de2e9a-7eff-4d3c-bb90-c29ed0f9fbb8
0|on-taskg | graphId:        fc1f9bc7-b3fe-4ca0-a25a-096887ea0ef9
0|on-taskg | injectableName: Task.Obm.Node.PxeBoot
0|on-taskg | node:           58dd1d30bbd977190806ad41
0|on-taskg | [info] [2017-03-30T15:07:14.508Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task finished
```

When we look up the taskID given, we can see that the task doesn't exist. The given graph id does specify the taskID shown, and the InjectableName exists in the task repository. 

Wondering if this is a mongoDB timing issue of if there's a simple solution.

**Note:** The versions we intend to run this workflow on include from commit `6b895265545545264fc8583605f71492e35e6eaa` to current master (2.0.0-rc to master), and we have the same problem throughout the releases and current commit.

**Comment by pscharla** [comment]
Closing this out and replacing it with this RAC:
https://rackhd.atlassian.net/browse/RAC-4721
