### ISSUE TITLE
http proxy support susceptible to transfer failures with slow/long downloads

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#90]
While working through the Vagrant based demonstration of installing, the download of the CoreOS install through the on-http proxy functionality failed somewhat consistently, resulting in an iPXE error while that installer OS bootstrap loading process was running. (downloading `coreos_production_pxe_image.cpio.gz` specifically)

The iPXE error seen was: 
![screen shot 2016-02-11 at 10 51 14 am](https://cloud.githubusercontent.com/assets/43388/12986683/71bb002c-d0ad-11e5-90e6-ee6ebd649ae9.png)
 - http://ipxe.org/420c6001

In debugging this, I pulled down the files into RackHD directly and modified the CoreOS install profile, and the process worked flawlessly. While downloading these files, I noticed the bandwidth of pulling down these specific example files was relatively slow, resulting in a > 5 minute download for the CoreOS production image.

There may be a lingering error for extra-long downloads that make this susceptible to failures in acting as a proxy.

**Comment by ytjohn** [comment]
I too have encountered this, with the same number of progress dots following coreos_production_pxe_image.cpio.gz.  Downloading and locally hosting the 2 files allows me to boot past the image loading.

**Comment by yyscamper** [comment]
+ @pengz1 for awareness.

**Comment by heckj** [comment]
I've hit this in the office with good bandwidth (but those quirkly firewalls) and at home (with relatively poor bandwidth). The initial file always downloads fine, but the larger `.cpio.gz` is consistently failing on me. I suspect the failure is related to size of the file, not bandwidth based on this detail, but haven't yet exhaustively tested to determine where a failure might be occurring.

I'm going to start testing by hosting HTTP files on my local workstation to remove networks from consideration in the isolation here, and try out some different sized files. I have verified the file is on the remote end, and is correct, using WGET to get it directly myself and verified it all still boots together by hosting it in the RackHD vagrant image directly

**Comment by heckj** [comment]
For debugging, I set up a local HTTP server and added a proxy configuration, then cat'd the vmlinuz file together to get incremental files:

```
-rw-rw-r-- 1 vagrant vagrant  30334576 Feb 16 19:42 test1
-rw-rw-r-- 1 vagrant vagrant  60669152 Feb 16 19:42 test2
-rw-rw-r-- 1 vagrant vagrant  91003728 Feb 16 19:42 test3
-rw-rw-r-- 1 vagrant vagrant 121338304 Feb 16 19:42 test4
-rw-rw-r-- 1 vagrant vagrant 151672880 Feb 16 19:47 test5
-rw-rw-r-- 1 vagrant vagrant 182007456 Feb 16 19:47 test6

vagrant@vagrant-ubuntu-trusty-64:/usr/share/nginx/html$ md5sum test*
3257697d78d9111445b3d35917759391  test1
e9e6b03739b2339df4751c99448aaf63  test2
ecd6d6953edee984b933a5d47c2af57f  test3
1ce7a3c1103b23ff32f6855f3eb1ecd3  test4
5a92e7c639663d7ae85234253d8f2090  test5
c548059ada2605d884149bf49380b627  test6
```

Using `curl` to test this, there's no chunked progress - the file appears all at one shot, making me think the files are getting loaded entirely into memory before being processed through. The throughput (not surprisingly) was highly variable

using commands like `curl http://172.31.128.1:8080/test/test5 -o test5`, the first four files were able to download successfully, but test5 failed repeatedly, as did test6. No errors appeared in the on-http logs during any of these transfers, successful or failed.

Files that transferred successfully did so with all data intact and correct (verified via MD5 sum), failures resulted in no data transferred at all after the http was open for exactly 2:00 minutes:

Details:

```
vagrant@rackhd-demo:~$ curl http://172.31.128.1:8080/test/test1 -o test1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.9M  100 28.9M    0     0  4081k      0  0:00:07  0:00:07 --:--:-- 7319k
vagrant@rackhd-demo:~$ curl http://172.31.128.1:8080/test/test2 -o test2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57.8M  100 57.8M    0     0  1208k      0  0:00:49  0:00:49 --:--:-- 12.4M
vagrant@rackhd-demo:~$ curl http://172.31.128.1:8080/test/test3 -o test3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 86.7M  100 86.7M    0     0  1190k      0  0:01:14  0:01:14 --:--:-- 20.9M
vagrant@rackhd-demo:~$ curl http://172.31.128.1:8080/test/test4 -o test4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  115M  100  115M    0     0  18.0M      0  0:00:06  0:00:06 --:--:-- 27.7M
vagrant@rackhd-demo:~$ curl http://172.31.128.1:8080/test/test5 -o test5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0
curl: (52) Empty reply from server
vagrant@rackhd-demo:~$ curl http://172.31.128.1:8080/test/test4 -o test4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0
curl: (52) Empty reply from server
vagrant@rackhd-demo:~$ curl http://172.31.128.1:8080/test/test4 -o test4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  115M  100  115M    0     0  1779k      0  0:01:06  0:01:06 --:--:-- 36.4M
vagrant@rackhd-demo:~$ curl http://172.31.128.1:8080/test/test6 -o test6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0
curl: (52) Empty reply from server
```

The marker of failure appears to be related to 2:00 duration of the http request, not the size of the request, since `test4` failed once, identical to failing on `test5` and `test6`, but succeeded when it managed to transfer the data in under 2:00 minutes

**Comment by heckj** [comment]
Side note: the proxy functionality in Vagrant with the existing monorail.json configuration doesn't appear to work at all with the latest code on master branches. On the vagrant instance, when I ran:

```
cd ~/src
./scripts/clean_all.bash && ./scripts/reset_submodules.bash && ./scripts/link_install_locally.bash
cd ~
sudo nf start
```

And then re-run these tests, all of the requests provide a response of `Cannot GET /test/test1`

I'll open a separate issue for this revelation...

**Comment by yyscamper** [comment]
@heckj : I did the preliminary testing in my system with latest code, but no coreos installation and no vagrant, all rackhd services run in a virutal machine.

This is my proxy config:
```json
    "httpProxies": [
        {
            "localPath": "/coreos",
            "server": "http://stable.release.core-os.net",
            "remotePath": "/amd64-usr/current/"
        },
        {
            "localPath": "/test",
            "server": "http://10.62.59.209",
            "remotePath": "/static/rhel"
        }
    ]
```

The server *10.62.59.209* is a local HTTP service setups in local lab.

I tried to download some large files (the largest file is around 260MB), all file downloading via proxy successed:
```
onrack@~/tmp> wget http://10.62.59.200:8080/test/7/os/x86_64/LiveOS/squashfs.img
--2016-02-18 17:31:35--  http://10.62.59.200:8080/test/7/os/x86_64/LiveOS/squashfs.img
Connecting to 10.62.59.200:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 272293888 (260M) [application/octet-stream]
Saving to: ‘squashfs.img’

100%[===========================================================================================================================================================>] 272,293,888  521MB/s   in 0.5s

2016-02-18 17:31:36 (521 MB/s) - ‘squashfs.img’ saved [272293888/272293888]

onrack@~/tmp> wget http://10.62.59.200:8080/coreos/coreos_production_pxe_image.cpio.gz
--2016-02-18 17:31:56--  http://10.62.59.200:8080/coreos/coreos_production_pxe_image.cpio.gz
Connecting to 10.62.59.200:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189959560 (181M) [application/x-cpio]
Saving to: ‘coreos_production_pxe_image.cpio.gz’

100%[===========================================================================================================================================================>] 189,959,560  727MB/s   in 0.2s

2016-02-18 17:31:59 (727 MB/s) - ‘coreos_production_pxe_image.cpio.gz’ saved [189959560/189959560]
```

If I tried to download some file that as large as 2GB, it eventually failed with error "out-of-memory" or the system hangs due to exhaust memory.

I went through the proxy library we used, it should first download all the request file to memory buffer  from real address and then send the buffer to proxy address. So If the file is large enough, the memory will sure be exhausted.

**Comment by heckj** [comment]
Thanks @yyscamper  - I'm glad you're at least seeing success here. I suspect it's related to the more constrained resources I have applied to the Vagrant setup. The VM running RackHD on my laptop is configured to use 4 virtual cores and 4096MB of RAM, with the target VM doing the download using a base of 512MB of RAM, but I've also tried it with having allocated it 2GB of RAM and seeing the same result.

It's the vagrant based demo that's showing the failure per some comments on the slack channel too - @kacole2 run into this issue as well. The tests I did above moved the hosting of the external proxy to a VM on the same local network as my laptop to remove "network latency" to a remote site from the possibilities in doing the isolation work above.

**Comment by heckj** [comment]
Hey @yyscamper ,

Let me know how you're coming along with reproducing the Vagrant setup - even with my PR's to update the Vagrant demo to the latest code, I'm still seeing this issue, and worse - we've had folks pulling down the code to run demos that are hitting the same issues as well. I'm wondering if it makes sense to just deprecate this http proxy game due to it's unreliability and updating the Ansible roles in packer to install and configure Squid or something as a proxy replacement that will be reliable.

**Comment by yyscamper** [comment]
@heckj :
I had never practice the vagrant setup, this is my first time and I have just let it run and begin the proxy testing.

No matter how my testing result is, I do see a problem about current proxy design. Just as I said before, It download the whole file into memory and then redirect to the local address. This will require much memory usage. At least we should change it to operate in stream way, and this need to find another proxy library or customize current library. 

Meanwhile, before the proxy enhancement ready, I think we can switch to use the NAT, it's package level proxy, so require much less memory. Of course, the NAT setup should be outside RackHD at present.

I am trying to practice the NAT setup and will provide the guide after success.

**Comment by yyscamper** [comment]
@heckj : below is a guide about how to bootstrap from external repo via NAT, I just tried, it will success:

(1)  Download this script (https://gist.github.com/yyscamper/49b8f030da48329c8567) and run in RackHD appliance, so that NAT service will be ready, the computer node will have the ability to access the external world via interface "eth0". 

(2) Set the `repo` to an external repo, make sure the "eth0" has the ability to access this repo. For example, this one "http://stable.release.core-os.net/amd64-usr/current/" for CoreOS, and this one for CentOS 7 "http://mirror.centos.org/centos/7/os/x86_64/"

(3) Run the bootstrap as normal.

Since, CoreOS doesn't support external repo at present, so I will submit PR to add this feature for CoreOS. You can first have a try for CentOS.

**Comment by yyscamper** [comment]
The external repo support for CoreOS has been included in following PRs:
- https://github.com/RackHD/on-http/issues/146
- https://github.com/RackHD/on-tasks/issues/131

**Comment by heckj** [comment]
@yyscamper while this certainly works, I don't think this is the best pattern to encourage. You're basically making the instance of RackHD a one-way traffic router for all requests from hosts. 

I think a better solution would be to specifically encourage and support the installation of Squid or related http proxy in RackHD (or on the same layer2 network) and then utilize the `repo` pieces that you're putting into on-http and on-tasks to point to an alternate mirror endpoint or relevant proxy.

Is it fair to assume that this feature is rather hopelessly blocked due to the lack of "good support" by NodeJS proxy libraries, and that it would be better to use an alternative mechanism?

**Comment by ytjohn** [comment]
Copying this in from the mailing list.  

I was originally advocating to put up a separate proxy like squid, or a dynamically controlled one like vulcand.

But I discovered [redbird](https://github.com/OptimalBits/redbird). Redbird is written in Node, controlled by API, and looks pretty awesome. But since it's in javascript just like on-http, I looked at the [proxy code](https://github.com/OptimalBits/redbird/blob/master/lib/proxy.js) and see that it's using [httpp-proxy](https://www.npmjs.com/package/httpp-proxy) as the library. 

I think that we should try redbird as  a proxy to see if it does the job. If so, it might be rather trivial to switch from `express-http-proxy` to `httpp-proxy` and gain the better functionality.

**Comment by yyscamper** [comment]
The external repo support doesn't mean I plan to abandon http proxy. A better proxy design need some investigatation and I even hear some voice that proxy shoud be function outside RackHD. Thanks for these tool or library proposal, I will have a try on them.

No matter proxy is bad or good, the external repo support will be a common feature for all OS installation, so I submit the PRs, and you can have alternative way for CoreOS before proxy is enough good.

Felix

-----Original Message-----

**Comment by yyscamper** [comment]
PR has been merged
