### ISSUE TITLE
docker image on-taskgraph includes the DHCP Server

### ISSUE THREAD

**Issue by rbuckland** [RackHD/RackHD#99]
A recent change created a set of Docker Images (good work!)

but we have found that the on-taskgraph includes the dhcp server by default.

To make these docker images more flexible are you able to mount the "dhcp.leases" file into the taskgraph service.. 

either from the host the docker container is running on, or from another container running just the dhcp server.

This way the "choice" or location of the dhcp server is not tied to the on-taskgraph

**Comment by rolandpoulter** [comment]
Yes, we could move the dhcp server outside of the on-taskgraph image and mount the dhcp.leases file as a volume. It would make it easier to make the dhcp server into a separate container.

I agree that would be much better.

**Comment by benbp** [comment]
@rbuckland we're also moving the lease parsing out of the on-taskgraph project together (CC @tldavies) and into the on-dhcp-proxy container. So we still would probably want to do a volume mount, but just an FYI.

**Comment by rolandpoulter** [comment]
@heckj @rbuckland Updated the docker example to make the DHCP server run in a separate container. See https://github.com/RackHD/RackHD/tree/master/docker#dhcp-server-runs-by-default
